### ISSUE TITLE
Recallibration on switching monitor.

### ISSUE THREAD

**Issue by Twelve-60** [digitalcreations/MaxTo#36] opened 2015-01-11 22:48 UTC
When I switch from my laptop display (3200 x 1800) to a 30" external monitor (2560 x 1600), the regions I've set out don't quite match up, and the white translucent preview pane goes beyond the lower boundary and into the taskbar. If I restart Maxto they are perfect again, suggesting there should be a hook when you change displays to recallibrate the specific region pixel dimensions.

I'm running Windows 8.1 64bit.

**Comment by vegardlarsen** [comment] 2015-01-12 06:57
@Twelve-60 I am assuming you have your laptop display setup as a high-DPI display and your external monitor as a standard display? I have the exact same setup, and am aware of the problem.

See issue #30.

**Comment by Twelve-60** [comment] 2015-01-12 07:09
Correct.

**Comment by vegardlarsen** [comment] 2015-01-12 07:26
Well, this is still caused by MaxTo's handling of high-DPI screen being non-existant. I'm bundling this with issue #30 and closing this.

**Closed by vegardlarsen** 2015-01-12 07:26 UTC
