### ISSUE TITLE
Windows update - MaxTo.Hook.x64.dll

### ISSUE THREAD

**Issue by Newtt** [digitalcreations/MaxTo#465] opened 2019-09-02 10:50 UTC
**Describe the bug**
Since the windows update (10.0.18362 Build 18362) I have this error when opening multiple programs (here notepad++). Apparently, you have an issue with your dll Hook.x64.dll.

**To Reproduce**
Update computer, 
Install MaxTo
Open another program such as Notepad++

**Expected behavior**
No error displayed

**Screenshots**
![64109585-2f06e600-cd80-11e9-9ccf-5a91a8572421](https://user-images.githubusercontent.com/16168409/64109918-fddae580-cd80-11e9-93c7-36f6c0a764f3.png)

**System information:**
 - Windows version: (10.0.18362 Build 18362)
 - MaxTo version 2.0.1 (latest today)

**Comment by vegardlarsen** [comment] 2019-09-03 08:13
This is the same issue as #415. I am closing this one.

Note that re-installing Notepad++ will fix the issue. It is caused by a file that it seems Windows Update places automatically when it upgrades, that only contain zeroes.

**Closed by vegardlarsen** 2019-09-03 08:13 UTC
