### ISSUE TITLE
MaxTo TrayIcon dissapears

### ISSUE THREAD

**Issue by lk-smit-ag** [digitalcreations/MaxTo#600] opened 2020-08-07 08:19 UTC
I had/have problems with MaxTo since a 2-3 weeks. MaxTo shows every time on startup "view the log files", but i cant find an issue related to the logs.
Now i have reinstalled the software and used the beta3, because it was described that the bug was fixed in this version. But it doesnt look so.
Here are some FATAL's from my logs:

![image](https://user-images.githubusercontent.com/61590827/89624883-35a6b300-d897-11ea-9ce2-f96479400b14.png)

![image](https://user-images.githubusercontent.com/61590827/89624969-540cae80-d897-11ea-94a0-abb8c5dbca0f.png)

![image](https://user-images.githubusercontent.com/61590827/89624997-5bcc5300-d897-11ea-99cf-eb61b98d8275.png)

A reply would be nice - thank you!

**Comment by vegardlarsen** [comment] 2020-08-07 09:16
Thank you for the log files, they are most helpful in diagnosing issues like these. In the case of the first exception, what were you doing at the time it occured?

The second crash seems like it should be reproducible by me. I will have to have a look at it next week.

**Comment by lk-smit-ag** [comment] 2020-08-07 11:37
I am not doing anything special - maybe the full log of today can help you.
I restarted my laptop right now, and the start message with the log was again.

I checked the "Send error report...". This is activated maybe you find some related information.

I will send the log of today to support@maxto.net. With this Issue as reference.
If you need something else, feel free to contact me.

**Comment by vegardlarsen** [comment] 2020-08-13 11:20
These issues have been fixed (presumably, as I could not reproduce both of them locally), and I have sent a test build to @lk-smit-ag via e-mail.

Closing this issue.

**Closed by vegardlarsen** 2020-08-13 11:20 UTC
Labels: bug
