### ISSUE TITLE
MaxTo can no longer manipulate Outlook 2013 windows

### ISSUE THREAD

**Issue by sflanagan180251** [digitalcreations/MaxTo#87] opened 2015-07-30 17:51 UTC
I've tried multiple key combinations, but none work.  OneNote windows can be moved between regions,  so the issue isn't Office itself, but outlook and any email windows seem to ignore any keypresses.

**Comment by vegardlarsen** [comment] 2015-07-30 18:03
This may very well be a bug. 

- Which keyboard combinations did you use? 
- Can you manipulate it via drag and drop (hold Shift)? 
- Did you receive a compatibility notice?
- Which Windows version?

**Comment by basshead22** [comment] 2015-07-30 19:24
Same problem for me. Ill also add that the Outlook main window is overlapping on another region when maximize.

Keyboard combination didn't work
Drag and drop doesn't work
No notice
Windows 10
Yes

**Comment by sflanagan180251** [comment] 2015-07-30 19:32
* I tried using the default keyboard combination as well as ctrl-win-arrow which is what I had mostly working with the last version of MaxTo.
* shift-dragging the window seems to work on the parent outlook window, but any child windows created from that parent window will not work with shift-dragging.  I tried opening a second inbox window from the main and opening an actual email and both failed.
* What is a compatibility notice?  Should that come from outlook or MaxTo?  Either way, I got no notice.
* I'm using windows 8.1
* The first thing I tried was a reboot.  then I completely uninstalled and installed again hoping something went wrong.  Still no luck.

**Comment by glat** [comment] 2015-08-06 12:52
+1

**Comment by TexasGitHubber** [comment] 2015-08-06 12:53
I'm having the same problem.

**Comment by seelenfrieden** [comment] 2015-08-07 14:17
same to me. issue since updating to the new version today.

**Comment by llinfeng** [comment] 2015-08-12 18:35
Well, this issue resembles issue #31 very well. In the `shims.xml`, an additional line prohibiting any maneuver on "Outlook" window was introduced on line 46 of the file named `c:\Program Files\MaxTo\shims.xml`, which goes as follows:
```
    <process title="Outlook">OUTLOOK</process>
```
In additional to this, the following processes are also "ignored" by MaxTo:
* Quickbooks
* KakaoTalk
* ManicTime
* iTunes
* The Windows taskbar
* Sidebar gadgets
* Adobe Acrobat
* UltraMon

Removing the corresponding lines that specify such ignorance (defined on line 28) will solve this, and other similar issues.

Note that, MaxTo must have been ignoring these processes for a reason. Removing corresponding lines may bring up potentially **serious** issues. Nevertheless, I think the most "serious" case should be countered upon a simple restart of MaxTo. :)

**Comment by basshead22** [comment] 2015-08-12 18:56
Thanks, this have kinda resolve the issue where the window wouldn't go into its region, but Outlook is still overlapping on the next region.

**Comment by vegardlarsen** [comment] 2015-08-13 05:46
@llinfeng Good catch! There should be no disastrous effects from removing Outlook from that list.

@basshead22 Your overlapping window issue is one we are working on. Basically the borderless windows in Windows 10 makes it necessary to adjust where we put windows. By default (discovered by trial and error) this offset is 7 pixels. It changes if you have a different DPI. Since we couldn't get Microsoft to fix this, or at least provide us correct guidance before the Windows 10 launch, we hard-coded the 7 pixels value. We are on our way to resolving this with Microsoft now, but a few things remain in limbo before I can release it.

**Comment by sflanagan180251** [comment] 2015-08-13 13:10
This appears to restore the functionality to the main outlook window as well as child windows it creates.  Thanks!

**Comment by vegardlarsen** [comment] 2015-09-30 05:50
Also confirmed on Windows 7 from customer via e-mail.

**Comment by RealRaven2000** [comment] 2015-09-30 10:40
Removing <process title="Outlook">OUTLOOK</process> from the "ignore" section in shims.xml worked for me too, with Outlook 2010 on Windows 7 Pro. Well done!

**Comment by mas-co** [comment] 2015-10-30 19:43
Still having problems with Outlook 2013 and Windows 10.
version 2015.7.1.0

**Comment by CCKS** [comment] 2015-11-02 13:58
I am having this issue with Outlook 2013 & W7x64.

I noticed that Outlook (and other office products) install as 32-bit even on 64-bit systems because of the impact on Add-Ins (according to a TechNet article).  I went to the Options->Diagnostics tab of MaxTo and ran a self-test.  32-bit system hook & keyboard shortcuts fail the test.  MaxTo.Helper32.exe is running.  Not sure what the issue is...

For those who have the transparency issue, I had that, and when I disabled Options->Window transparency -> Fade animation, the transparency issues went away (possibly coincidentally).

**Comment by vegardlarsen** [comment] 2015-11-03 07:28
The issue with Outlook will be fixed in the upcoming release. For now, use the workaround listed above regarding modifying the `shims.xml` file.

**Comment by mas-co** [comment] 2015-11-03 23:56
By the way, I have made changes to the shims.xml file.  I commented out the record for Outlook.  At first, it seemed to be working.  However, this has stopped working for some inexplicable reason.  (I double checked the shims.xml file and it is still commented out.
I will be waiting for the upcoming release that hopefully fixes this problem.

**Comment by vegardlarsen** [comment] 2015-11-04 06:47
You may need to exit MaxTo, exit Outlook, and then restart MaxTo to make the change take effect. MaxTo tags open windows if they shouldn't be touched. The tags are normally removed when MaxTo exits, but to be sure you need to exit Outlook.

**Comment by mas-co** [comment] 2015-11-05 23:30
Ok.  This does work if I ensure that MaxTo is opened first.
Now I just need MaxTo to start when Windows10 starts....

**Closed** 2015-11-09 12:44 UTC
Labels: bug, fixed, version-2015.07.1, windows-10, windows-7, windows-8.1
