### ISSUE TITLE
Swap and Move window with activate window on mouse hover

### ISSUE THREAD

**Issue by rastkov** [digitalcreations/MaxTo#706] opened 2021-02-20 22:34 UTC
**Describe the bug**
When using the Windows option "Activate a window by hovering over it with the mouse" the Move and Swap windows, MaxTo ignores the new window position and the previously used window (window in focus) is no longer in focus and the mouse stays in the previous position.

**To Reproduce**

1. Go To: Control Panel\Ease of Access\Ease of Access Center\Make the mouse easier to use
2. Enable option "Activate a window by hovering over it with the mouse" 
3. Apply Settings
4. Open two applications
5. Focus on App1
6. Move App1 do another region
7. Swap App1 with App2
8. Notice that the in both 6. and 7.  the window focus is lost and mouse pointer stays in the same position

**Expected behavior**
If App1 is the selected and focused application (window), then the focus on that App (window) should remain after moving it or swapping it. The mouse pointer should follow the active app because of the Windows Ease of Access setting.

**System information:**
- Windows version: Windows 10 Version 1909 (OS Build 18363.1256)
- MaxTo version: 2.2.0-beta1

**Comment by rastkov** [comment] 2021-02-21 01:06
I can achieve the desired result with the ingredient "Move Mouse Cursor". However, I can't seem to force from the UI to position relative to a window.
If I add the ingredient "Launch program" and use MaxTo CLI:  "mouse position /Window 50%,50%" (but I get a console window to pop up each time. And I don't see an option from the UI to tell to position relative to a window.

I still think that this should be default behavior in terms that the window being moved should be focused on after the operation if Ease of access mouse hover is enabled.

**Comment by vegardlarsen** [comment] 2021-02-22 15:46
I am not sure that this can be considered a bug; it is more a feature of how "Activate a window by hovering over it with the mouse" works.

You should be able to [position the mouse cursor relative to a window](https://docs.maxto.net/reference/commands/mouse/position), but you need to specify which window you want it relative to. It would be something like `maxto mouse position /Position center /Window "App A"` or similar. You can't rely on variables to determine the window (e.g. `$foreground`) in this case, since it will change "randomly".

I am closing this issue because I don't consider this to be a fault in MaxTo. Please feel free to ask further questions here even though the issue is closed.

**Closed by vegardlarsen** 2021-02-22 15:46 UTC
