### ISSUE TITLE
Chrome Window forgets size 

### ISSUE THREAD

**Issue by Sterling177** [digitalcreations/MaxTo#548] opened 2020-04-16 01:17 UTC
Chrome window when minimised forgets position 

set position minimise chrome > maximise chrome 

keeps position 

Windows 10 Pro 
1909
18363.720

Same issue with Blender windows

**Comment by vegardlarsen** [comment] 2020-04-18 07:47
If by "maximise chrome" you mean "restore Chrome" (e.g. by clicking its icon in the taskbar), I cannot reproduce this issue. I tested with MaxTo version 2.1.0-alpha.4 ([currently in preview](https://maxto.net/release/alpha)).

I am afraid you are going to have to be a little more specific with the details:

- version of MaxTo
- version of Chrome
- details about the exact steps you take that are reproducible.

**Comment by Sterling177** [comment] 2020-04-20 00:56
MaxTo 2.0.1
Chrome Version 80.0.3987.163 (Official Build) (64-bit)
Start Chrome and Chrome starts Full Screen - Win Key arrow right Snap to position. 
Minimise Chrome - Maximise Chrome back to Full screen

**Comment by vegardlarsen** [comment] 2020-05-18 11:02
Thank you for reporting this issue, @Sterling177.

I have uncovered the cause, and it appears MaxTo will not notify a maximized window that it is being restored when we moved it into a region when using the move command.

When the window is then re-opened from a minimized state, it believes it was maximized, and Windows will happily oblige.

This issue will be fixed in 2.1.0-beta.2.

**Closed by vegardlarsen** 2020-05-18 11:02 UTC
Labels: bug
