### ISSUE TITLE
windows remain transparent when using Max-to

### ISSUE THREAD

**Issue by iamsoot** [digitalcreations/MaxTo#646] opened 2020-11-05 08:28 UTC
Hey, last 2 days when using max to the window of opend programs remains "transparent" (only on my extended screen - not on my laptop)

![image](https://user-images.githubusercontent.com/73988243/98216364-4247af80-1f49-11eb-89eb-227000fb2d17.png)

**Comment by vegardlarsen** [comment] 2020-11-05 08:30
@iamsoot I think this is a duplicate of #643, so I am closing this issue. Send me an e-mail at support@maxto.net to get a copy of the private build.

**Closed by vegardlarsen** 2020-11-05 08:30 UTC

**Comment by iamsoot** [comment] 2020-11-05 09:23
Hey,

Thank you for getting in contact, i had to disable Max to because it
was'nt workable anymore.
Would like to use it again, i can't work without it anymore :-)


Kind regards,
Vriendelijke groeten,

Steven Bertels

bertelssteven@gmail.com
0474 591645


Op do 5 nov. 2020 om 09:30 schreef Vegard Andreas Larsen <
notifications@github.com>:

**Comment by iamsoot** [comment] 2020-11-05 09:43
Hi Steven,

here is a private build:
https://sky.vegard.name/s/BzpGfEpxeMqNbTe

The file is digitally signed, so you can verify it is authentic.

To install it, you need to follow this process (or it won't
work):
* Uninstall the current version of MaxTo
* Reboot
* Install the private build

Please let me know if the issue is still present.

Best regards

Vegard

The MaxTo team at Digital Creations AS

Steven Bertels on November 5, 2020 at 10:23am wrote:

Hey,

Thank you for getting in contact, i had to disable Max to because
it was'nt workable anymore.
Would like to use it again, i can't work without it anymore :-)

Kind regards,

Vriendelijke groeten,

Steven Bertels

bertelssteven@gmail.com
0474 591645
