### ISSUE TITLE
Custom recipe with same name as built in

### ISSUE THREAD

**Issue by npapandreou** [digitalcreations/MaxTo#734] opened 2021-06-14 04:48 UTC
When creating a recipe with exactly the same name as a built-in (ex. "Move window left") there is a bug that replaces the custom recipe with the built-in and now you have 2 built-in recipes and they are not working.

**Comment by vegardlarsen** [comment] 2021-06-14 19:59
I can confirm that this is happening on version 2.2.0.

**Comment by vegardlarsen** [comment] 2021-11-21 20:06
I believe this is the same issue as #766. Since I've already tackled that one separate from this one, I'll close this one as a duplicate (even though it is strictly the other way around).

**Closed as completed by vegardlarsen** 2021-11-21 20:06 UTC
Labels: bug, duplicate
