### ISSUE TITLE
Since Windows Update MaxTo Crases with some apps.

### ISSUE THREAD

**Issue by vidalrica** [digitalcreations/MaxTo#466] opened 2019-09-06 14:14 UTC
Since the latest update of Windows, MaxTo crashes with some apps like iTunes and a a few other more.

![error](https://user-images.githubusercontent.com/54990689/64434691-bf963c80-d086-11e9-9f9d-c673dbd7f8f5.png)

**Comment by vegardlarsen** [comment] 2019-09-06 14:35
This is a duplicate of #415. Please see that issue for a workaround and up to date information.

**Closed by vegardlarsen** 2019-09-06 14:35 UTC
