### ISSUE TITLE
Focus Window recipe does not work

### ISSUE THREAD

**Issue by fatherofinvention** [digitalcreations/MaxTo#425] opened 2019-06-05 17:37 UTC
**Describe the bug**
Focus on window recipe does not actually make the window "active", instead it just flashes the programs icon in the task bar.

**To Reproduce**
Create a recipe that focuses a window, assign it a shortcut. For example, if you are in Firefox (active window) but have a recipe triggered by "Windows+SHIFT+N" to focus on Notepad, pressing this key combination only causes the Notepad icon to blink but now actually being the active/focused/foreground window. 

**Expected behavior**
Focusing a window should make it the active window without requiring mouse clicks to bring it into focus.

**Screenshots**

**System information:**
 - Windows version: Windows 10 1809 Build 17763.292
 - MaxTo version: 2.0.1

**Comment by fatherofinvention** [comment] 2019-06-05 17:40
Maybe there needs to be a "bring to front" option available after focusing the window?

**Comment by fatherofinvention** [comment] 2019-06-05 18:12
Alright, after some more testing I see that the feature only works if the program to be focused is minimized. So if I have two programs side-by-side, Firefox and Notepad, with Firefox being the active window, running the recipe will *only* activate Notepad if it is minimized. If they are both visible on the screen the Notepad icon will flash in the task bar (presumable indicating that the program is already up). 

It would be great if we could focus regions and/or programs that are already visible on screen, to essentially navigate from screen to screen and program to program without touching the mouse.

**Comment by vegardlarsen** [comment] 2019-06-06 07:58
@fatherofinvention After testing for a bit now, this feature appears to work on my machine. I created a recipe that focuses on Notepad based on a keyboard hotkey; and it works whether Notepad is minimized or not.

My recipe: 

```json
{
      "name": "Focus Notepad",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Control+Windows+N"
        }
      ],
      "ingredients": [
        {
          "command": "window:focus",
          "parameters": {
            "window": "Untitled - Notepad"
          }
        }
      ]
    }
```

**Comment by vegardlarsen** [comment] 2019-06-07 10:33
@fatherofinvention Did this recipe help you out at all?

**Comment by fatherofinvention** [comment] 2019-06-08 18:07
Hi there @vegardlarsen 

Unfortunately it does not. For example, if I open notepad, and then open Firefox on top of it so essentially both programs have windows open on the desktop but Firefox is "layered over top" the Notepad window, it will not change focus. It will just blink/flash the Notepad icon in the task bar to indicate that they Notepad app is not minimized (presumably). However, as I said before, if I minimize Notepad to the task bar and run the receipt, it will bring Notepad up and set focus on it.

It seems that if the program window to be focused is not minimized, the recipe is unable to set it as the active foreground window. 

Thanks for the response.

**Comment by vegardlarsen** [comment] 2019-06-12 08:48
Do you have any other programs installed that do window management (or add functionality to other programs in general)? Do you have any windows set to be always on top?

Are you running MaxTo as admin or a standard user?

**Comment by thewavelength** [comment] 2019-06-16 19:23
I also have the same issue. I am running in elevated mode with Windows 1903 64bit. No other programs are running which are dedicated to be Windows utility tools. It doesn't work with any window.

Any way we can provide debug info to tackle it down?

**Comment by vegardlarsen** [comment] 2019-06-17 08:44
Do you get anything in the log file at the exact time this happens? 

[Documentation on finding log files](https://maxto.net/documentation/troubleshooting).

**Comment by fatherofinvention** [comment] 2019-06-17 16:33
> 
> 
> Do you have any other programs installed that do window management (or add functionality to other programs in general)? Do you have any windows set to be always on top?
> 
> Are you running MaxTo as admin or a standard user?
> 
> I have tried this on 2 different machines, with different Windows builds and both Firefox and Notepad, and the behavior seems to be correct here.

No, Maxto is the only shortcut/window management software installed. It didn't matter if I ran as a standard user or admin, the results were the same. 

Not sure what timezone you are in but I am happy to show host a screenshare sometime if you can't repro yourself.

**Comment by thewavelength** [comment] 2019-06-18 11:10
`2019-06-16 20:55:31 [Core@2.0.1.499] [Information] Recipe '"Focus WhatsApp"' executed successfully.
2019-06-16 20:55:37 [Core@2.0.1.499] [Information] Executing recipe '"Focus WhatsApp"' with 1 ingredients
2019-06-16 20:55:37 [Core@2.0.1.499] [Information] Recipe '"Focus WhatsApp"' executed successfully.
2019-06-16 20:55:38 [Core@2.0.1.499] [Information] Executing recipe '"Focus WhatsApp"' with 1 ingredients
2019-06-16 20:55:38 [Core@2.0.1.499] [Information] Recipe '"Focus WhatsApp"' executed successfully.`

As you can see, I tried it multiple times. The focus didn't change. I tried both while being on the same virtual desktop and being on another. No more log entries are available regarding focus.

**Comment by fatherofinvention** [comment] 2019-06-18 16:57
The key here that would make this feature killer is to actually set the application window as the active foreground. For example, if I want to assign a keyboard shortcut to VS Code, activating the recipe would immediately bring VS Code into the foreground and allow me to start typing in my open editor window without clicking around first. 

In addition to focusing a specific application, the ability to focus on a region would be useful as well. That way if you happen to use one region for multiple apps, you can just focus the region instead of setting up multiple recipes to focus the different apps that may be running in a given region. Just a bit of simplification.

Once this is fixed you have another paying customer. Otherwise, I think Maxto is great!

**Comment by thewavelength** [comment] 2019-06-18 18:44
Regarding your suggestion, please see issue #324

**Comment by fatherofinvention** [comment] 2019-06-22 14:26
@vegardlarsen can you provide an estimate on when the next build will be released that includes this fix?

**Comment by vegardlarsen** [comment] 2019-06-24 08:39
@fatherofinvention As I haven't even been able to reproduce this issue on machines I can debug on, it would be very difficult for me to give an estimate that is even close to accurate.

**Comment by schkr** [comment] 2019-07-21 01:50
Set Focus Down (Win+Down) = Focus on Window, Foreground Window, Direction: Down.
Set Focus Down (Win+Up) = Focus on Window, Foreground Window, Direction: Up.
Set Focus Down (Win+Left) = Focus on Window, Foreground Window, Direction: Left.
Set Focus Down (Win+Right) = Focus on Window, Foreground Window, Direction: Right.

Screen set with 3 regions. -|  Upper Left, Lower Left, and Right Region.
I'm able to focus on any window I have populated in the 3 regions except Google Chrome.
I can focus Up, Down, L/R on any other program except Chrome.

**Comment by schkr** [comment] 2019-07-21 05:18
I apologize for the many edits.

Max.To Ver 2.0.1


//Problem
Screen set with 3 regions. -|  Upper Left, Lower Left, and Right Region.
I'm able to focus on any window I have populated in the 3 regions if the larger Right region has the initial focus. Once focus switches to any of the Left two regions, I am only able to switch focus between the two Left region windows.

//Duplicate
Setup 1 monitor with the regions specified above. Populate all 3 regions with windows.
- Select the larger Right Region, then Win+ Left to switch focus left. Works.
- Win+ Up moves focus up, Win+ Down moves focus down. Works.
- Win + Left or Win + Right cycles focus between the two Left regions, unable to get the focus back to the Right region.

// Recipe Setup
Set Focus Down (Win+Down) = Focus on Window, Foreground Window, Direction: Down.
Set Focus Up(Win+Up) = Focus on Window, Foreground Window, Direction: Up.
Set Focus Left (Win+Left) = Focus on Window, Foreground Window, Direction: Left.
Set Focus Right (Win+Right) = Focus on Window, Foreground Window, Direction: Right.


![Max To Example](https://user-images.githubusercontent.com/39759051/61587282-22b22b00-ab3c-11e9-835a-73e92f4a36c0.png)
![Max To Regions](https://user-images.githubusercontent.com/39759051/61586492-787dd780-ab2a-11e9-8d97-b79fbd345775.png)

**Comment by vegardlarsen** [comment] 2020-05-18 12:26
I have tried to reproduce this repeatedly with different programs, and cannot reproduce this issue at all (version 2.1.0-beta.1). Please try this version and let me know if the issue still persists.

I am closing this issue, but if you can reliably reproduce it, feel free to comment again.

**Closed by vegardlarsen** 2020-05-18 12:26 UTC
Labels: bug

**Comment by thewavelength** [comment] 2020-05-21 09:17
Still doesn't work with 2.1.0-beta2. I used Notepad (clearly a Win32 native application) to test. Only information in log file is that it executed successfully. So it did find the window by title.

**Comment by vegardlarsen** [comment] 2020-05-25 12:56
Focusing a window brings it to the front (unless you have an always on top window that covers it, of course). It is basically a call to [`SetForegroundWindow`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow).

There are edge cases where it may not work, but I cannot reproduce any from the information above. Please try to create a new issue with exact steps taken.
