### ISSUE TITLE
MaxTo not showing up in notification area

### ISSUE THREAD

**Issue by gnychis** [digitalcreations/MaxTo#153] opened 2016-10-05 19:39 UTC
After a clean reboot of my machine, MaxTo does not properly show up in my notification area when it is in fact running.  This prevents me from accessing the menus:

![image](https://cloud.githubusercontent.com/assets/1406044/19128574/eb1fc730-8b11-11e6-91e2-62a8497501a9.png)

If I kill the process and then launch it again, it will show up.

I am using Windows 10 Pro, 10.0.10586 Build 10586

**Comment by vegardlarsen** [comment] 2016-10-06 13:48
I have had a few reports of this in private as well, but I have never been able to reproduce it on any of my machines. I will be looking into what may be the cause of this.

**Comment by drossian** [comment] 2016-12-14 14:43
I am having this same issue. Running Win 7 Enterprise / 64-bit

**Comment by datune** [comment] 2016-12-18 22:38
I had it running for the trial period without any issue. I bought it, supply the serial, and from that exact moment forward I can not get it to work properly anymore. It does not show up in the notification area, but all 3 processes are running. Obviously, if I kill it and restart it has none of the system hooks available. This issue has been reported all the way back in 2015!

**Comment by vegardlarsen** [comment] 2017-05-08 10:04
I have figured out a case where this can happen; if MaxTo is started before `explorer.exe`, which in theory can happen on some machines where `explorer.exe` starts slowly.

The solution is to remove and re-add the notification icon (systray icon) if Windows tells us that the taskbar has been created (which it does by sending us a `TaskbarCreated` custom window message.

This will be fixed in the upcoming release of MaxTo. Because we are waiting for Advanced Installer to update to support .NET Framework 4.7, I am providing the fixed version here.

If you want to try this out as a "pre-release" you can download and unzip these files over your existing MaxTo installation. For it to run, you will need to install the following dependencies:

- [.NET Framework 4.7](https://www.microsoft.com/en-us/download/details.aspx?id=55170)
- [Visual C++ Redistributable for Visual Studio 2017 x64](https://go.microsoft.com/fwlink/?LinkId=746572)
- [Visual C++ Redistributable for Visual Studio 2017 x86](https://go.microsoft.com/fwlink/?LinkId=746571)

[MissingNotificationIconBugFix.zip](https://github.com/digitalcreations/MaxTo/files/983095/MissingNotificationIconBugFix.zip)

**Closed by vegardlarsen** 2017-05-08 10:04 UTC
Labels: bug, fixed, version-2015.11, version-2015.11.1, windows-10, windows-7, windows-8.1, windows-vista

**Comment by drossian** [comment] 2017-05-08 14:27
Thanks for the follow-up, I really appreciate it. I had made just part of my routine when starting up my computer to end MaxTo through Task Manager and restart. I will for sure try this new solution.

Thanks

Derek Ossian

**Comment by vegardlarsen** [comment] 2017-05-08 20:22
Please let me know if this indeed does solve it for you. It is always good to have separate confirmation before shipping it to everyone.
