### ISSUE TITLE
Focus on Window stops working if I change tab in browser

### ISSUE THREAD

**Issue by SonnyCampbell** [digitalcreations/MaxTo#408] opened 2019-05-08 10:14 UTC
**Describe the bug**
If I set a "Focus on window" recipe to focus on Firefox, then change tab within Firefox, the recipe stops working.

![image](https://user-images.githubusercontent.com/4961041/57368088-3d524600-7182-11e9-8a79-ea0fc25155ed.png)

**To Reproduce**
Open Firefox.
Create recipe to focus on Firefox window.
Open a new tab within Firefox and go to any other website.
Attempt to use recipe to focus back on Firefox window.
"Could not find window matching xxx"

**Expected behavior**
I would expect it to focus on the browser window regardless of which tab I'm on.

**System information:**

    Windows version: 10
    MaxTo version 2.0.1

**Comment by vegardlarsen** [comment] 2019-05-08 11:24
Thank you for reporting this. It is not really a bug in MaxTo, more of a feature, but one that I can understand quite well that you experience as a bug.

The problem is of course that in Firefox (and Chrome, and any other tabbed browser), the window title changes when the tab changes. So the recipe you targeted for one tab does not work on another.

In the current version there is only one way of working around this; use the window class instead of the window title. For Firefox, I believe this is `MozillaWindowClass`, but I may be mistaken.

We are making this better in version 2.1, where we intend to support regular expressions for window titles. That means you'll be able to specify something like `.* - Mozilla Firefox` to search for any window ending in ` - Mozilla Firefox`.

I am closing this issue as it is not really a bug.

**Closed by vegardlarsen** 2019-05-08 11:24 UTC
