### ISSUE TITLE
Problem with 2 monitos and monitor wake up

### ISSUE THREAD

**Issue by HenkeSoftware** [digitalcreations/MaxTo#162] opened 2016-12-31 07:58 UTC
Hi,

I am having 2 monitors, a primary 40" and another 21".

When I wake up the monitors from standby (system is up) at first the 21" monitor is recovering, the 40" needs some seconds longer. Because of this, Windows give the 21" monitor the primary role for 1-2 seconds, before the 40" is fully recognized again and gets primary role back.

Having this, MaxTo seems to get in trouble. After this switch fore and back, I am not able to maximize any windows anymore. The maximize button of any window is not reacting.

This will be solved when I shut down MaxTo and start it again. Afterwards all is fine again.

So, can you have a check, why this switch of primary monitor (at least my impression to be the root cause) is leading to stop of functionality?

Thanks,
Thorsten Henke (license got in November 2016)

**Comment by vegardlarsen** [comment] 2016-12-31 08:49
Thanks for reporting this. I am afraid I know exactly what causes it, and it won't be fixed for a while. You are right in that the problem is related to Windows disconnecting one monitor for a few seconds.

When that happens, MaxTo treats it as a hardware change. On hardware changes, MaxTo should reload its configuration. However, the .NET Framework is very "helpful" in this case and seems to cache the display configuration with the first value it sees (containing one monitor). After that MaxTo cannot see the second monitor when it reappears, even though it gets notified that a monitor change happened.

As a workaround for now, I would suggest you disable the "Start with Windows" feature in Options, and create a shortcut to start MaxTo after you've logged in.

**Closed by vegardlarsen** 2016-12-31 08:49 UTC

**Comment by HenkeSoftware** [comment] 2016-12-31 10:25
Hey,

thanks for that really fats feedback. I appreciate!

Well, it is not about starting the PC, just when I come back to the PC after a while and the monitors are in sleep mode. When starting the PC, MaxTo is working correct, as monitors are recognized correct form the beginning..

I basically understand the technical issue you describe for .Net Framework. Just, is the problem you face about timing/trigger (find right moment to reload config), or will you not get the handled for both monitors afterwards anymore?

As a work around, could you ping the monitor setup a while (10-20 sec.) after MaxTo recognized HW change? And when you see there another HW change, then reload the config again?

BR, Thorsten

**Comment by vegardlarsen** [comment] 2017-01-02 07:23
Unfortunately, this seems to be a bug in the .NET Framework. `System.Windows.Forms.Screen.AllScreens` seem to return the same value even after Windows fires its global `WM_DISPLAYCHANGE` message. Note that this caching only happens when you use it multiple times in a process, which is what MaxTo does. I am looking into solving this issue (probably by avoiding or rewriting the `Screen` class).

**Comment by HenkeSoftware** [comment] 2017-01-02 07:52
I assume your issue is related to this?
http://stackoverflow.com/questions/5020559/screen-allscreen-is-not-giving-the-correct-monitor-count

**Comment by vegardlarsen** [comment] 2017-01-02 07:53
Correct. :)

**Comment by HenkeSoftware** [comment] 2017-03-03 10:43
Hi,

meanwhile I wrote a little program that is checking for screen changes periodically. If changes occure, MaxTo will be restarted by my program. If you are interested, I can forward to you.

BR, Thorsten
