### ISSUE TITLE
Virtual desktop features doesn't work under Windows 11

### ISSUE THREAD

**Issue by airens** [digitalcreations/MaxTo#781] opened 2022-02-20 19:01 UTC
When I try to move window to another desktop (using `Ctrl->Windows->Alt->Right` or `...Left` combination), the program tells me, that "Virtual desktops are only supported on Windows 10", which is really strange, because I'm using Windows 11. Also I can only chose one profile for all Virtual Desctops which is completely inconvinient.

**Comment by flyingwolf79** [comment] 2022-02-20 20:37
I am not sure what is strange about it? You are using windows 11, the virtual desktops feature of maxto only works on windows 10.

**Comment by vegardlarsen** [comment] 2022-03-06 20:11
This is a duplicate of #770, so I am closing this one.

Unfortunately, we've relied on some undocumented parts of Windows 10 when it comes to virtual desktops, and Microsoft decided to change those in Windows 11.

**Closed as completed by vegardlarsen** 2022-03-06 20:11 UTC
Labels: duplicate
