### ISSUE TITLE
Snapping to window or monitor eges doesn't work correctly in Windows 10

### ISSUE THREAD

**Issue by Robbson** [digitalcreations/MaxTo#143] opened 2016-06-30 16:55 UTC
Because of the border-less windows style in Windows 10 there is always an annoying big gap when you try to align a window to the screen border or the edges of another window. So to use screen space most efficiently I need to disable those features on Windows 10.

**Comment by vegardlarsen** [comment] 2016-06-30 19:52
I haven't noticed these myself, but I will see if I can reproduce this. It could be that Windows 10 has changed its behavior since the last release of MaxTo.

Which build of Windows are you experiencing this on?

**Comment by Robbson** [comment] 2016-07-01 09:51
Version 1511, Build 10586.420.
Should be the latest before the big anniversary launch.

**Comment by vegardlarsen** [comment] 2016-08-09 09:39
Is this still the case on the Anniversary Update?

**Comment by Robbson** [comment] 2016-08-09 10:20
Can't say. My trial license expired a while ago and I haven't bought it so far.

**Comment by vegardlarsen** [comment] 2017-05-05 13:04
This has been fixed, and will be included in the next release. We are waiting for an update to Advanced Installer before we can deploy this.

If you want to try this out as a "pre-release" you can download and unzip these files over your existing MaxTo installation. For it to run, you will need to install the following dependencies:

- [.NET Framework 4.7](https://www.microsoft.com/en-us/download/details.aspx?id=55170)
- [Visual C++ Redistributable for Visual Studio 2017 x64](https://go.microsoft.com/fwlink/?LinkId=746572)
- [Visual C++ Redistributable for Visual Studio 2017 x86](https://go.microsoft.com/fwlink/?LinkId=746571)

[RegionEdgesBugFix.zip](https://github.com/digitalcreations/MaxTo/files/979080/RegionEdgesBugFix.zip)

**Closed** 2017-05-05 13:44 UTC
Labels: bug, fixed, version-2015.11.1, windows-10, windows-7, windows-8.1, windows-vista
