### ISSUE TITLE
Restoring a reduced window in a region moves the window to the main screen

### ISSUE THREAD

**Issue by terrybr** [digitalcreations/MaxTo#441] opened 2019-07-07 23:43 UTC
**Describe the bug**
I put a window in a region (secondary screen), and then reduce it to the taskbar.  One I click on its icon to restore it, the window is moved and maximized to the main screen.

**To Reproduce**
1. Put a window to a region on a secondary screen by using a "recipe"
2. Reduce the window to the taskbar
3. Click on the window icon to restore it
4. The window is restored and maximized to the main screen.

**Expected behavior**
The window should keep its position on the screen's region it was moved to once it's restored.

**System information:**
 - Windows 10 Pro
 - MaxTo version 2.01

**Comment by vegardlarsen** [comment] 2019-07-15 10:56
I apologize for the slow response on this; I am currently on vacation.

I was unable to reproduce this issue with Notepad on my machine. Is this something that only happens with specific programs? Was both monitors connected to the machine the entire time?

**Comment by terrybr** [comment] 2019-07-15 16:20
No need to apologize. 

It doesn't happen all the time.  I'm using Firefox a lot for my work, so it happens mostly with Firefox.  I have three monitors and they're connected to my PC at all time.

Enjoy your vacation! :)

**Comment by vegardlarsen** [comment] 2020-05-18 12:31
I believe this issue will be fixed for version 2.1.0.  It appears to be the same issue as #548. I am closing this one as a duplicate (even though you were first). :)

**Closed by vegardlarsen** 2020-05-18 12:31 UTC
