### ISSUE TITLE
Window becomes transparent

### ISSUE THREAD

**Issue by rustamsh** [digitalcreations/MaxTo#661] opened 2020-11-17 17:55 UTC
Hi,

Sometimes application windows become transparent but I couldn't find the actual steps to reproduce that issue.
That issue appeared in recent days actually That never happened before maybe MaxTo got updated recently.
The effect as the MaxTo "Windows transparency" setting is turned on, even though that setting is turned off for me.

Maxto version 2.1.1
Apps, where it appears, are Zoom, Sublime merge.

Thanks

**Comment by TomTrek99** [comment] 2020-11-17 18:21
I have the same problem even if I don't use a MaxTo function actively, but the program is active. Occurs with Microsoft Office 365 applications and Visio. Also the latest version installed. What can you do ?

**Comment by vegardlarsen** [comment] 2020-11-17 18:38
This is a duplicate of issue #656. Please see that issue for a workaround, or restart MaxTo twice to automatically update to 2.1.2, which fixes this issue.

**Closed** 2020-11-17 18:38 UTC
Labels: duplicate
