### ISSUE TITLE
Resize renders some windows transparent

### ISSUE THREAD

**Issue by Achnazoor** [digitalcreations/MaxTo#647] opened 2020-11-05 12:18 UTC
Lately, when I resize the Slack desktop application window, it becomes about 50% alpha-blended and won't go back to fully opaque until I close the application and start it again.

This also happens with the WireShark window.

I'm running MaxTo 2.1.0 on a Windows 10 Pro in an Intel i7 with 48gb of ram

**Comment by vegardlarsen** [comment] 2020-11-05 12:20
This is a duplicate of #643. Closing this issue, and feel free to contact us at support@maxto.net to receive a private build that will hopefully fix the issue.

**Closed by vegardlarsen** 2020-11-05 12:20 UTC
