### ISSUE TITLE
Not working on Chrome, Edge (insider preview) or Brave version 78 or later

### ISSUE THREAD

**Issue by johnkamau** [digitalcreations/MaxTo#476] opened 2019-10-07 11:22 UTC
MaxTo regions are not observed by the latest chrome and firefox dev versions. 

https://www.google.com/chrome/dev/
https://www.mozilla.org/en-US/firefox/developer/

**Comment by vegardlarsen** [comment] 2019-10-07 11:32
Does this issue persist after a reboot?

**Comment by johnkamau** [comment] 2019-10-07 11:50
> Does this issue persist after a reboot?

Yes it does on chrome. A reboot seems to have fixed firefox.

**Comment by artesea** [comment] 2019-10-10 11:39
Just came to report a similar problem, had assumed the issue was with all apps, however testing and it's only happening to Chrome 78.0.3904.50 (Beta)

**Comment by KnightDemons** [comment] 2019-10-22 20:20
Chrome version 78.0.3904.70 updated today and will not snap to location when I hold shift and drag it to there spot..

**Comment by vegardlarsen** [comment] 2019-10-24 13:58
Diagnosis so far: Chromium does publish window messages for their windows; however, the CBT and CallWndProc hooks do not receive any notifications from any of Chromium windows, and therefore no MaxTo functionality initializes.

This is all very strange, because I can see the window messages in Spy++, which means that Spy++ is able to get hold of them in some manner.

**Comment by tarpaha** [comment] 2019-10-25 09:19
Same issue, Chrome Version 78.0.3904.70 (Official Build) (64-bit)
Very sad because I use MaxTo commonly for Chrome positioning.

**Comment by NicholasConrad** [comment] 2019-10-25 19:08
Same behavior from Brave browser version 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)

Has persisted through several reboots.

**Comment by artesea** [comment] 2019-10-26 10:34
Just to add that the Win+Left and Win+Right keyboard shortcuts are successfully resizing and moving my Chrome windows

**Comment by 50l3r** [comment] 2019-10-26 20:14
I have the same problem in 78.0.3904.70 (Build oficial) (64 bits)

**Comment by vegardlarsen** [comment] 2019-10-28 12:56
I have confirmed that this issue happens for version 78 or later of

- Chrome
- Edge (insider preview)
- Brave

Our global `CBT` and `CallWndProc` hooks do not pick up any events from these processes; although Spy++ can spy on its window messages.

I have created [an issue with the Chromium project](https://bugs.chromium.org/p/chromium/issues/detail?id=1018714) to try to get their help to track down this issue.

At the moment, there does not appear to be anything I can do on my end to fix this. I am going to have to wait for the Chromium project to respond.

As a workaround, MaxTo's keyboard shortcuts should work for quickly repositioning these browser windows, but most other functionality will be broken.

**Comment by vegardlarsen** [comment] 2019-10-28 19:39
This is referenced in the following Groove conversation:
https://dc.groovehq.com/tickets/13475

**Comment by vegardlarsen** [comment] 2019-10-29 09:09
Someone from the Chromium team pointed out that this has already been reverted in later versions, and that they disabled hooking on purpose as a security measure. 

See [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1017694) for details, which points to [the following change in their source code](https://chromium.googlesource.com/chromium/src/+/f87359ae7be2906bf1b361ba4bdbd9308f7fcd9f). It is puzzling to me that they would do this, at this also disables IME input (basically on-screen keyboards for Asian languages), and that they stated that they were OK with it.

The feature has an "emergency off switch". It is different for each browser, but here is a registry file that disables this feature for all 4 affected browsers:

```ini
Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Edge Dev\BrowserSboxFinch]
[HKEY_CURRENT_USER\SOFTWARE\Chromium\BrowserSboxFinch]
[HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\BrowserSboxFinch]
[HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Brave-Browser\BrowserSboxFinch]
```

Create a new file with the `.reg` extension, copy and paste in the contents above, save the file, and then run it. You'll need to accept up to a two security prompts. Then restart the affected browser completely, and MaxTo should work again.

We will be including a fix for this by default in the next update of MaxTo.

**Comment by Gappa** [comment] 2019-10-29 09:19
Thanks, hotfix confirmed working (Chrome).

**Comment by vegardlarsen** [comment] 2019-10-29 13:28
I have implemented the above workaround in our codebase, and it will be in the next release of MaxTo. I am therefore closing this issue.

**Closed by vegardlarsen** 2019-10-29 13:28 UTC
Labels: bug, compatibility

**Comment by NicholasConrad** [comment] 2019-11-01 18:18
I applied the fix on the 30th, and it worked for a while, but this morning Brave had reverted to the error condition. Re-running the .reg file then closing all instances of Brave restored the desired behavior.

**Comment by nickallevato** [comment] 2019-11-01 19:10
The registry fix 'fixed' the recurring issue. Thank you for the information.
However, if I middle-click or left-click on a link, I 'lose' the proper 'region' sizing and the window returns to it's pre-max-to'ed size.

**Comment by nickallevato** [comment] 2019-11-01 21:47
@vegardlarsen I am also experiencing this when muting/un-muting VLC. 
I am max'ed to a region, but when I come back to the window and click it seems to un-max-to the window.

**Comment by NicholasConrad** [comment] 2019-11-04 20:23
FYI, brave was exhibiting the error behavior again this morning. Re-runing the registry file and restarting the browser restored the expected behavior. This seems to be a recurring issue, will maxto be able to automatically fire off the reg script as needed in the proposed 'fix' implementation? if not it may be wise to add some kind of user-accessible button to regain control of these browsers on demand.

**Comment by shinmai** [comment] 2019-11-08 08:17
The referenced issue above that was closed as a duplicate is not affected by the registry fix in this issue, and is also present with Chrome 78.0.3904.97. 
Can reproduce 100% consistently by:

1. Snap Chrome window to a region
2. Shift focus away from chrome
3. Shift focus back to the Chrome window

Expected behaviour: Chrome window gains focus but doesn't change it's position or dimensions.
Actual behaviour: Chrome window gets popped out of the region, resized to it's original size and positioned with it's horizontal centre as close to the mouse cursor as possible while still staying inside the same display.

The window can be popped back into place with shortcuts, but it's still a massive hassle, since even if the browser window has some passive content like a monitor of some kind, it's easy to accidentally shift focus to the window when navigating between apps, etc.
Does not happen with any other application I've tested.

**Comment by vegardlarsen** [comment] 2019-11-08 08:25
@shinmai Are you on MaxTo version 2.1.0-alpha.1 or 2.0.1? Have you tried re-running the registry fix and restarting Chrome? How about restarting your computer?

**Comment by shinmai** [comment] 2019-11-08 08:44
I'm on 2.1.0-alpha1.
I've tried merging the registry keys a number of ways (merging while Chrome is running, merging with all Chrome processes killed, restarting the browser or rebooting after merging, and any combination of the above I could think of) same experience throughout.

For now I'm using Edge for browser windows I need to stay in regions, but would obviously like to return to my preferred browser ASAP.

**Comment by vegardlarsen** [comment] 2019-11-08 08:56
@shinmai Ah, if you are on 2.1.0-alpha.1, it is an issue just in that version (and it affects more than just Chrome). See #487, which will be fixed in the next release.

**Comment by shinmai** [comment] 2019-11-08 09:09
Oh, good to hear! I'll eagerly await alpha2, then.

**Comment by thewavelength** [comment] 2020-01-14 12:39
@vegardlarsen Path for the Chromium-based Iridium browser:

`[HKEY_CURRENT_USER\SOFTWARE\Iridium\BrowserSboxFinch]`

**Comment by vegardlarsen** [comment] 2020-03-15 13:47
@thewavelength Took me a while, but I've added Iridium to the automatic patch list for MaxTo as well.
