### ISSUE TITLE
RDP fullscreen ignores MaxTo Region

### ISSUE THREAD

**Issue by smiziara** [digitalcreations/MaxTo#796] opened 2022-11-01 16:33 UTC
**Describe the bug**
I split the monitor in 2 regions and drag my RDP Session window to one of them. Then i try to maximize it, but the session just use the entire monitor, not respecting the region.
Is this behaviour expected or its an issue?

**To Reproduce**

1. Connect to a machine using Remote desktop
2. Split the monitor into 2 regions
3. Drag the remote desktop into one of the regions and try to make it fullscreen

**Expected behavior**
The fullscreen should be limited to the region, not get the entire monitor.

**System information:**
- Windows version: 21H1 Build 19043.1348
- MaxTo version: 2.2.1

**Additional context**
Remote Desktop options used.
[rdptions.txt](https://github.com/digitalcreations/MaxTo/files/9912268/rdptions.txt)

**Comment by vegardlarsen** [comment] 2022-11-06 09:34
Thanks for writing. Unfortunately, this is "by design" (but not really because we want it to be this way). There is a difference between apps that maximize, and apps that "go fullscreen". MaxTo is only able to intercept maximize events, but RDP "goes full screen".

There are unfortunately no good mechanisms that we know of to intercept fullscreen apps when they happen. So unfortunately, I have to close this one as by design.

**Closed as not planned by vegardlarsen** 2022-11-06 09:34 UTC
Labels: wontfix
