### ISSUE TITLE
Maximized window cannot be moved left

### ISSUE THREAD

**Issue by dzieciou** [digitalcreations/MaxTo#428] opened 2019-06-14 12:24 UTC
**Describe the bug**
Maximized window cannot be moved left. It needs to be moved right and only then it can be moved left.

**To Reproduce**
1. Maximize any application window to monitor with <kbd>Win</kbd>+<kbd>Alt</kbd>+<kbd>M</kbd>.
2. Move the window left with <kbd>Win</kbd>+<kbd>Left</kbd>.
3. Move the window right with <kbd>Win</kbd>+<kbd>Right</kbd>.
4. Again, move the window left with <kbd>Win</kbd>+<kbd>Left</kbd>.

**Expected behavior**
In step 2 the windows is not moved left, only in step 4. 

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.1

**Comment by vegardlarsen** [comment] 2019-06-14 12:57
@dzieciou Can you tell me anything about your region layout? Maybe a full-screen (all monitors) screenshot of how the regions are laid out, and which regions you cannot move between?

**Comment by dzieciou** [comment] 2019-06-16 18:16
Here's the [screen recording](https://drive.google.com/open?id=1fetsWo7aEhsvoLLJ9G0LYBT6-rhMUDRM) with keystrokes displayed in the bottom-right corner. Around 7s I'm pressing Win+Left and nothing happens.

My regions are as follows:

![MaxTo-Regions](https://user-images.githubusercontent.com/7452788/59567720-88108900-9071-11e9-84f1-28f214bc16db.png)

**Comment by vegardlarsen** [comment] 2019-06-17 08:46
Thank you for this screen recording. I missed the part where the window had to be maximized before trying to move it left; I can consistently reproduce this.

**Comment by vegardlarsen** [comment] 2019-06-17 13:43
Thank you for letting me know about this issue. It turned out to be a combination of two things:

1. Maximized windows (on Windows 10) has a size that is larger than the monitor they are maximized on when compensating for their invisible border. Say on a 1920x1080 primary monitor, the maximized window's coordinates would be (LTWH) -1,-1,1922,1082.
2. Due to the way MaxTo 2.0.1 calculates which regions are in the direction you want, it didn't find the region underneath it on the left. MaxTo uses the center of the window you are moving, and checks to see if there are any regions with a right edge to the left of the center, and then uses the center-to-center distance from the window to the region to determine which is closest. In your case there are no regions with a right edge to the left of the window center point, so the window doesn't move. You would get the problem moving to the right if you had mirrored the divider to the other side of the screen. Also, if you had had another monitor to the left of the current monitor, the window would immediately have jumped to that monitor's right-most region, which I think makes sense.

We are solving this by applying a different, more permissive "direction filter" in the cases where MaxTo doesn't find a a region. I have tested and implemented this solution, and it solves this problem.

**Closed** 2019-06-17 13:43 UTC
Labels: bug
