### ISSUE TITLE
PATH environment variable changed to include MaxTo but lost nvm-windows path location

### ISSUE THREAD

**Issue by cwgabel** [digitalcreations/MaxTo#688] opened 2021-01-02 20:18 UTC
New install on Windows 10.  Only installed Chrome with this fresh install, then nvm-windows, then MaxTo.

**C:\Users\cw>nvm**

Running version 1.1.7.

Usage:

  nvm arch                     : Show if node is running in 32 or 64 bit mode.
  ....
  nvm version                  : Displays the current running version of nvm for Windows. Aliased as v.

**C:\Users\cw>path**
PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\cw\AppData\Local\Microsoft\WindowsApps;C:\Users\cw\AppData\Roaming\nvm;C:\Program Files\nodejs

C:\Users\cw>

**********************************************************************************************************************************
Now after installing MaxTo: (of course I reloaded my cmd shell)

Microsoft Windows [Version 10.0.19042.631]
(c) 2020 Microsoft Corporation. All rights reserved.

**C:\Users\cw>nvm**
'nvm' is not recognized as an internal or external command,
operable program or batch file.

**C:\Users\cw>path**
PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;%NVM_HOME%;%NVM_SYMLINK%;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;%NVM_HOME%;%NVM_SYMLINK%;

**C:\Users\cw>set NVM_HOME**
NVM_HOME=C:\Users\cw\AppData\Roaming\nvm

**C:\Users\cw>set PATH=%PATH%;C:\Users\cw\AppData\Roaming\nvm**

**C:\Users\cw>path**
PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;%NVM_HOME%;%NVM_SYMLINK%;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;%NVM_HOME%;%NVM_SYMLINK%;;C:\Users\cw\AppData\Roaming\nvm

**C:\Users\cw>nvm**

Running version 1.1.7.

Usage:

  nvm arch                     : Show if node is running in 32 or 64 bit mode.
 ...
 nvm version                  : Displays the current running version of nvm for Windows. Aliased as v.

C:\Users\cw>

Clearly it is an easy fix on my part, but thought you would be interested.  NEVER had an app install impact my PATH variable.

Don't know what I could of done  on my new setup to make this happen....

**Comment by vegardlarsen** [comment] 2021-01-04 07:44
Thank you for reporting this issue. It is likely caused by the fact that `Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.User)` will replace all other environment variables in the `PATH` before returning it; so that we don't really know what the `PATH` was before we started. We try to compensate for this, by reversing the replacement of environment variables (I can't say exactly if that is the cause, but I believe it has to be).

OK then, so why doesn't MaxTo just use `SET path=%path%;(new path)` when it needs to update the `PATH`? This method is run quite often, so we don't want to append the new path repeatedly and all the time.

I will be looking into if there are ways we can do this where we don't have to do the reverse replacement of env. variables.

**Comment by vegardlarsen** [comment] 2021-01-24 14:26
Having finally had the time to investigate this a bit more thoroughly, I have found the bug in MaxTo that causes this, and the fix for it will be in version 2.2.0. It turns out we were trying to be a bit to clever and were looking up the `PATH` in the registry instead of through `Environment.GetEnvironmentVariable`, and my statement above was slightly wrong (it will sometimes replace environment variables in the returned string, but it appears only under certain conditions).

**Closed** 2021-01-24 14:27 UTC
Labels: bug
