### ISSUE TITLE
Application unable to launch

### ISSUE THREAD

**Issue by justinh109** [digitalcreations/MaxTo#134] opened 2016-04-05 16:23 UTC
Max to gives a MaxTo.exe Error:

"The application has crashed and it will be dismissed. a bug report has been sent...."

This happens every time i launch the executable and on startup as maxto.exe is on the startup queue.
I have tried uninstalling, updating, installing to different hard drives, and checking my software security for anything that may be blocking it. 

This has been happening for some time now and Im out of idea. I've tried looking for crash reports but I dont see any under the MaxTo folder in programfiles. Below is the only trace of a bug report I can find from NBug.log;

NBugTrace: Starting to handle a System.AppDomain.UnhandledException.
NBugTrace: Starting to generate a bug report for the exception.
NBugTrace: As per setting 'Settings.StopReportingAfter(120)', bug reporting feature was enabled for a certain amount of time which has now expired: Bug reporting is now disabled.

the entire log consists of a chain of entries identical to the one above, please help.

**Comment by vegardlarsen** [comment] 2016-04-06 07:22
Thank you for reporting this. It would be useful to try to get a crash report from MaxTo for this. The easiest way to do that is to disable your Internet connection, make MaxTo crash, and then look in `C:\Program files\MaxTo` for any `Exception_xxx.zip` files. 

With that said, the exception mentioned in the log has never made it to our bug-tracking system, so it could be another exception in disguise.

If it is the most common one, deleting your configuration may help. You'll find it in `%AppData%\Local\Digital_Creations_AS\MaxTo\MaxTo.exe_url_<some gibberish>\<version>\user.config`. The easiest solution would be to rename the entire `Digital_Creations_AS` folder before starting MaxTo, and then you could move it back if that doesn't solve the problem.

Please let me know how it goes.

PS! I am currently in the mountains in a cabin on vacation. I am typing this because everyone else is asleep... Therefore, I may be somewhat slow to reply... :smile:

**Comment by justinh109** [comment] 2016-04-08 00:02
First off Enjoy your vacation, I don't mind waiting a few days for a
response so no pressure.

I took the steps mentioned above and nothing is working. I disabled the
internet connection and crashed maxTo, but no exception files were made in
the maxTo folder. Again I tried uninstalling everything, deleting the
tempdata, rebooting and reinstalling a fresh version and making sure it is
allowed through the firewall but still no luck.

**Comment by vegardlarsen** [comment] 2016-04-08 06:23
I think I figured it out. You need to change a setting for the component that MaxTo relies upon for bug reporting. Find the file `C:\Program files\MaxTo\MaxTo.exe.config`. Open it in Notepad (or another editor of your choice) as an Administrator. Search for "StopReportingAfter" and change the `<value>120</value>` to `<value>99999</value>`. Then start MaxTo, and it should generate an Exception file. Now, the next time you start it it should be logged to our bug reporting system.

**Comment by justinh109** [comment] 2016-04-08 15:08
ah ha!

**Comment by justinh109** [comment] 2016-04-14 00:01
Has any one had the chance to look at the crash-log I sent?

**Comment by vegardlarsen** [comment] 2016-04-14 06:40
@justinh109 I haven't received it. Can you try to capture the Exception.zip file before restarting MaxTo after a crash, and e-mailing it to me?

**Comment by justinh109** [comment] 2016-04-14 16:01
It was attached to to the email I sent you one April 8th. It is also
attached to this email and the exception.xml is copied below:

<?xml version="1.0"?>
<SerializableException xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ExtendedInformation>
    <HResult>-2146233079</HResult>
  </ExtendedInformation>
  <Message>SplitterDistance must be between Panel1MinSize and Width -
Panel2MinSize.</Message>
  <Source>System.Windows.Forms</Source>
  <StackTrace>   at
System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
   at System.Windows.Forms.SplitContainer.ApplyPanel2MinSize(Int32 value)
   at System.Windows.Forms.SplitContainer.set_Panel2MinSize(Int32 value)
   at MaxTo.MainForm.InitializeComponent()
   at MaxTo.MainForm..ctor()
   at MaxTo.Program.Main(String[] args)</StackTrace>
  <TargetSite>Void set_SplitterDistance(Int32) @
System.Windows.Forms.SplitContainer</TargetSite>
  <Type>System.InvalidOperationException</Type>
</SerializableException>

**Comment by vegardlarsen** [comment] 2016-04-15 06:24
Aha. Any attachments you send here to Github are stripped, so that is why I didn't see it.

I think you can temporarily fix your problem by deleting the settings for MaxTo. You can find the settings file in `%LocalAppData%\Digital_Creations_AS\MaxTo`. Simply remove all the files in that folder, and restart MaxTo.

I am aware of this issue, and it will be fixed in the next release. If you could e-mail me the configuration files before you delete them (support at maxto dot net), I can try to reproduce this on my machine and be certain that this works correctly for the next release.

**Comment by justinh109** [comment] 2016-04-16 14:49
I have deleted all the files in the folder with the address
%LocalAppData%\Digital_Creations_AS\MaxTo
to no avail. The folder contained one folder named 2015.11.1.0 inside that
folder was the config file I just sent to your support adress. Deleting
this file has no effect on the behavior of maxto. I Listed some system
specs below for your reference:

OS: Windows 8.1
Monitors: 2 4k monitors side by side
also the system has a dedicated nvidia GPU that runs aside the intel
integrated graphics.

**Comment by justinh109** [comment] 2016-04-16 14:52
I just took a look at the config file in Microsoft visual studio and
noticed the config file is very short:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings"
type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="MaxTo.UserSettings"
type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089"
allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <MaxTo.UserSettings>
            <setting name="LastVersionRun" serializeAs="String">
                <value>2015.11.1.0</value>
            </setting>
        </MaxTo.UserSettings>
    </userSettings>
</configuration>

Thats the entire thing. It looks like the config file is not being
generated correctly, but i could be wrong.

**Comment by vegardlarsen** [comment] 2018-05-23 12:53
As we are abandoning this configuration system in version 2.0.0, I am closing this issue. See #220 to try out the alpha release.

**Closed by vegardlarsen** 2018-05-23 12:53 UTC
