### ISSUE TITLE
Does not work with vertically aligned monitors

### ISSUE THREAD

**Issue by papadi** [digitalcreations/MaxTo#139] opened 2016-05-10 07:56 UTC
I have my main screen horizontally aligned and my second one vertically. It seems that MaxTo does not detect the orientation of the latter, therefor changing the regions is not possible.

**Comment by vegardlarsen** [comment] 2016-05-11 06:40
@papadi Thank you for writing. Do you have a screenshot or a picture of your display?

If the display is rotated in Windows, MaxTo should see it correctly.

**Comment by papadi** [comment] 2016-05-11 11:44
Here is the screenshot. Yes, it is rotated in Windows.

![untitled](https://cloud.githubusercontent.com/assets/3359377/15179852/7013b742-177e-11e6-8f86-94526004ac40.png)

**Comment by vegardlarsen** [comment] 2016-05-11 12:03
Wow, that is strange. Are either of your screens 4K/high DPI monitors?

**Comment by papadi** [comment] 2016-05-11 13:00
Yes, the left one is 4K

**Comment by vegardlarsen** [comment] 2016-05-11 13:14
Then this is the same as issue #30. The problem is that WinForms, which MaxTo is built with, does not support per-monitor DPI scaling, This is a large problem for us, and ditching WinForms isn't an easy undertaking, but I am working on it.

Technically, this shouldn't affect the actual regions, it is "just" the editing of them that is incorrect. I am closing this case since we already have an open one for this.

**Closed by vegardlarsen** 2016-05-11 13:14 UTC

**Comment by papadi** [comment] 2016-05-11 13:42
Hmmm, I temporarily changed DPI scaling to 100% on my 4K screen and then editing of the regions was ok. Then I reverted the scaling back to 125% and it kind of works... not perfect but better than before. It will do for now. Thanks.
