### ISSUE TITLE
Win+Shift+S snipping tool breaks when maxto is running

### ISSUE THREAD

**Issue by kat1689** [digitalcreations/MaxTo#386] opened 2019-04-02 20:13 UTC
**Describe the bug**
Running the latest version of MaxTo. Using the shortcut to take a snip of the screen (win shift s causes the PC to hang and the image does not copy to the clipboard. Closing MaxTo and using the snipping tool works as expected

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**
 - Windows version: [e.g. 10, 8, 8.1]
 - MaxTo version [e.g. 22]

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by vegardlarsen** [comment] 2019-04-03 11:59
Thank you for your feedback. I am assuming you are talking about the Snip & Sketch tool in the latest version of Windows 10?

**Comment by kat1689** [comment] 2019-04-03 19:38
Yes. Thanks
-Katrina Thompson

**Comment by Sawtaytoes** [comment] 2019-04-09 00:03
Just as an additional verification, I also noticed this the over the last few days with MaxTo 2.0.1 in Windows 10 64-bit. The Snipping Tool does not have this issue so it's something with the newer Snip & Sketch.

If it was happening in earlier versions, I didn't notice because MaxTo didn't run properly for me in 2.0.0 builds.

**Comment by vegardlarsen** [comment] 2019-04-11 13:50
I am hoping to be able to tackle this before 2.1 ships. :)

**Comment by vegardlarsen** [comment] 2019-05-15 08:34
I am unable to reproduce this issue with these versions:

- Snip&Sketch version 10.1901.10521.0
- Windows 10 version 1809 (OS Build 17763.475)
- MaxTo 2.0.1

I have tried Win+Shift+S, it works the same on my machines with or without MaxTo. I have tried setting up PrintScreen, it also works well. I have tried the different snipping modes (freeform, rectangular, fullscreen), and the window that opens with your snip in it also opens up correctly.

Is this an intermittent issue, or does it happen all the time?

@Sawtaytoes @kat1689

**Comment by Sawtaytoes** [comment] 2019-05-15 21:51
It happens every time. The entire computer freezes when the screen turns grey and is unable to be used during this period of time.

**Comment by Sawtaytoes** [comment] 2019-05-15 21:53
As an extra bit of info, I did upgrade from the alphas.

**Comment by brunogc** [comment] 2019-05-18 03:36
I'm experiencing the same problem with the "Snip&Sketch" program. After trying to use the tool, the screen freezes with the gray background. The problem started from the last update of Windows.

I detected that the problem was in MaxTo, from the Windows Log report, and confirmed it by turning off MaxTo, and then it all worked again.

- Windows 10 Pro version 1809 Build  17763.503
- MaxTo 2.0.1
- Screenshoot of Windows Log: https://www.dropbox.com/s/sjp42hewltdvdov/Anota%C3%A7%C3%A3o%202019-05-18%20002922.jpg

**Comment by vegardlarsen** [comment] 2019-05-20 12:00
After the weekend I was able to reproduce this issue, and isolate it. It appears that it was caused by MaxTo not checking for a specific error code, and then preceding to try to read uninitialized memory in specific cases.

I have made a fix that appears to work, and the changes will be in version 2.1.0.

**Closed by vegardlarsen** 2019-05-20 12:00 UTC
Labels: bug
