### ISSUE TITLE
Windows 10: each "virtual desktop" uses the same MaxTo layout

### ISSUE THREAD

**Issue by dramamask** [digitalcreations/MaxTo#543] opened 2020-03-09 15:43 UTC
MaxTo 2.01
Windows 10.0.18363

Previously, MaxTo would remember a layout for each "virtual desktop". If you loaded a layout it would only effect that particular "virtual desktop"... which was great because I use different layouts for each of my four desktops.

Since about two weeks ago the same layout is used on each of the "virtual desktops". When I load a MaxTo layout on any of my desktops, it now applies to all desktops.

I don't see any errors in the logs.

**Comment by vegardlarsen** [comment] 2020-03-11 08:31
@dramamask Have you enabled it in the settings (bottom of screenshot)?

![image](https://user-images.githubusercontent.com/436508/76397268-130d7e00-637b-11ea-9558-45b1e535acc7.png)

**Comment by vegardlarsen** [comment] 2020-03-15 08:53
Closing this due to no feedback. Will re-open if requested.

**Comment by dramamask** [comment] 2020-03-20 14:49
Sorry for the late reply. Yes, that is enabled: 

![image](https://user-images.githubusercontent.com/16373074/77175025-9455c680-6a87-11ea-95db-525e330da5f6.png)

This used to work for me, until the latest Windows 10 update.

**Comment by vegardlarsen** [comment] 2020-03-20 14:51
OK, then it could be a problem with an underlying change in the Windows 10 APIs. We use some undocumented APIs to enable this support, and Microsoft has been known to change it before.

**Comment by vegardlarsen** [comment] 2020-03-22 11:38
I can reproduce this locally, and I am looking at it.

**Comment by vegardlarsen** [comment] 2020-03-22 15:14
Thank you for this report, @dramamask. This boils down to a bug in a library we are using. Specifically [this bug](https://github.com/Grabacr07/VirtualDesktop/pull/43).

I have successfully managed to fix the issue locally; but since we need to fork that project and set up our own builds of it; I do not have a test build ready for you at this time. 

If you are interested in a preview build of this fix, please e-mail support AT maxto DOT net with a reference to this issue, and I'll send it over as soon as I have it ready. PS! Due to the corona lockdown I will not be working for the coming 4 days; so this may take a while.

**Comment by dramamask** [comment] 2020-03-23 17:45
Thank you for jumping on this! Much appreciated.

**Comment by vegardlarsen** [comment] 2020-03-25 08:16
This issue has been solved, and will be in 2.1.0-alpha.4.

**Closed** 2020-03-25 08:15 UTC
Labels: bug

**Comment by shie-erlich** [comment] 2020-11-13 17:47
this is happening to me on 2.1.1.
is there a workaround?
