### ISSUE TITLE
MaxTo Crashes when trying to open the layout config on this monitor setup

### ISSUE THREAD

**Issue by emanborg** [digitalcreations/MaxTo#664] opened 2020-11-18 20:32 UTC
![image](https://user-images.githubusercontent.com/996673/99584611-7b6e2e00-29e5-11eb-9afa-2f8fef19bb08.png)

**Comment by vegardlarsen** [comment] 2020-11-23 09:30
Wow, that is quite the setup. Can you send me the log files from when it crashes? You should be able to find them in `%AppData%\MaxTo\maxto<date>.log`?

**Comment by emanborg** [comment] 2020-11-23 09:37
Hi Vegard,

It crashes as soon as I click on the icon to set positions, even with new
config it does the same.

Note it used to work when the top 2 monitors were set sideways on the left
hand side of the 3x 4K monitors but now that I changed layout it stopped
working

logs attached

*  Eman Borg*

[image: LogicPassSimplyifinyTechnol] <http://www.logicpass.com/>



*LogicPass Ltd*

*Mimosa Street,**G’Mangia*

* Tel: **356 20333302*



This message contains confidential information and is intended solely for
the use of the individual or entity to whom they are addressed. If you are
not the intended recipient you are notified that disclosing, copying,
distributing or taking any action in reliance on the contents of this
information is strictly prohibited. E-mail transmission cannot be
guaranteed to be secure or error-free as information could be intercepted,
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses.
The sender, therefore, does not accept liability for any errors or
omissions in the contents of this message, which arise as a result of
e-mail transmission. If verification is required please request a hard-copy
version.

**Comment by vegardlarsen** [comment] 2020-11-23 09:39
@emanborg Unfortunately, attachments do not survive when you respond via e-mail on Github. Please upload them on the website, or e-mail to support@maxto.net if you fear they may contain sensitive information. :)

**Comment by vegardlarsen** [comment] 2020-11-23 10:53
After receiving logs from @emanborg via e-mail, it is clear that this is a duplicate of #631. Closing this issue.

**Closed by vegardlarsen** 2020-11-23 10:53 UTC
