### ISSUE TITLE
When trying to move a region-maximized window, it automatically maximizes to the whole screen

### ISSUE THREAD

**Issue by drizo72** [digitalcreations/MaxTo#265] opened 2018-10-27 14:30 UTC
When moving a previously maxed to a specific region window, it should retain its region-maximized dimensions. As it is right now, it maxes out to the totality of the screen real-estate available.

For example, I have a 4K screen. When I try to move a previously maxed to a region window, at the moment I click on it to move it, it resizes and turns into a huge 4K window.

When I use a triple screen setup with various resolutions, it does the same thing and maxes out horizontally not just to one screen but it expands across all screens horizontally and across the smallest one vertically.

Please fix this, it is very annoying...

Thanks

Dimitris

**Comment by vegardlarsen** [comment] 2018-11-06 08:49
Thank you for writing. I think this is related to you having multiple monitors with different DPI. What happens as far as I can tell is that when you drag a window out of a region, we remember the previous size of the window (so we can downsize it). Somehow Windows decides that this size should be "scaled" to fit the monitor. The problem is that it is inconsistent; it doesn't happen every time (e.g. I have a 4K monitor and the problem seems intermittent).

I am looking into this, but I am unsure that I can fix it.

**Comment by vegardlarsen** [comment] 2019-03-06 14:12
@drizo72 I believe this issue was fixed in 2.0.0-rc.1. Can you try that version and confirm?

**Comment by vegardlarsen** [comment] 2019-03-19 08:48
I am closing this issue due to lack of feedback.

**Closed by vegardlarsen** 2019-03-19 08:48 UTC
Labels: bug
