### ISSUE TITLE
Monitor resolutions detected incorrectly

### ISSUE THREAD

**Issue by AdamTakvam** [digitalcreations/MaxTo#116] opened 2015-11-20 00:44 UTC
OS: Windows 10 Pro 64-bit with "service pack"
Monitor 1: Asus PB287Q @ 3840x2160
Monitor 2: ViewSonic VX2475 @ 3840x2160

MaxTo detects the resolution of both of these displays differently, causing different issues. So I'll take each separately:

Monitor 1 (mostly works): 
Profile: 3 vertical splits with the leftmost pane split horizontally.
Profile Issues: With a single pane (no splits) the reported area fills the screen and reports as 3072x1688. As I configure the profile as above, the height of the regions changes. By the end, the 3 vertical columns report as 1670, 1680, 1684, respectively.
Behavior: Windows maximized on the bottom pane of the leftmost region (which is split horizontally) run very far off the bottom of the monitor area. I can't tell exactly how far, but it's far. Through the taskbar and way beyond. Windows maximized on the other two regions seem to be fine.

Monitor 2 (completely busted):
Profile: None / 1 region
Profile Issues: The shading for the profile definition only covers a portion of the screen starting at the upper-left side. The size reported is 2560x1440. That size appears about right for the area that the MaxTo region is covering with respect to the real resolution. 
Behavior: MaxTo does not seem to have any effect on the behavior of monitors on this monitor, thankfully. No matter the position, all windows maximize to full screen.

I'm happy to perform any diagnostic measures and/or workarounds you would like to try.

**Comment by vegardlarsen** [comment] 2015-11-20 07:16
@AdamTakvam Thanks for reporting this. There are a few things I want to try. First, I am guessing you are running both these monitors as high-DPI? Are they both using the same DPI scaling settings?

MaxTo has some issues with DPI scaling, especially if the monitors are on different DPIs. It doesn't sound like that should be the issue here, though.

I'd like you to download [LINQpad](https://www.linqpad.net/) and [run this little script I've prepared](https://dl.dropboxusercontent.com/u/12591686/MaxTo-diagnostics.linq). At the moment that script only lists out the monitor sizes as reported by Windows, but that gives me a starting point to work from. In LINQpad you can export the values as HTML, so you can paste it in here, or send it to me by e-mail (address is in the About dialog).

**Comment by idrake** [comment] 2015-11-20 23:24
I noticed the same thing.  Surface Pro 4 at 150% scaling and a 40" 4K TV at 100% scaling.  Where the screens have a virtual seam between them, the window on the 4K tv adjacent to the Surface is overhanging the tiniest bit onto the Surface, seemingly causing the window to size (height at least) to the Surface's scaling.

The Surface is new, so I'm still installing my dev tools, which includes LINQpad.  I'll get you the file soon.  Setting both displays to 100% scaling fixes the problem.

Love your site's copy.  "Please take my money" and you did!

**Comment by AdamTakvam** [comment] 2015-11-21 00:05
The issue with the bottom panel on Monitor 1 seems to be specific to Internet Explorer. I tried Chrome and other random things and they size correctly. So Monitor works fine except for reporting the wrong resolution, which is benign at this point.

The scaling on the monitors is: 
Monitor 1: 125%
Monitor 2: 150% 

Setting both monitors to 125% scaling causes Monitor 2 to report 3072x1728 in MaxTo, but the entire screen area is now recognized. After playing with a few region configurations, the monitor now appears to work correctly for all practical purposes.

With a DPI scaling of 100% on Monitor 2, MaxTo reports a resolution of 3840x2160, precisely what it really is. But I'm going to set to back to 125% for now since that seems to work and the font size at 100% is too small to read on a 24" display.

So I guess for my exact situation, this is a viable workaround. However, I can imagine there will be many other people this will not work for. I will paste the result of the LINQpad query in the next comment.

**Comment by AdamTakvam** [comment] 2015-11-21 00:06
<!DOCTYPE HTML []>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="Generator" content="LINQ to XML, baby!" />
    <style type="text/css">
body {
	margin: 0.3em 0.3em 0.4em 0.4em;
	font-family: Verdana;
	font-size: 80%;
	background: white;
}

p, pre {
	margin:0;
	padding:0;
	font-family: Verdana;
}

table {
	border-collapse: collapse;
	border: 2px solid #17b;
	margin: 0.3em 0.2em;
}

table.limit {
	border-collapse: collapse;
	border-bottom: 2px solid #c31;
}

td, th {
	vertical-align: top;
	border: 1px solid #aaa;
	padding: 0.1em 0.2em;
	margin: 0;
}

th {
	text-align: left;
	background-color: #ddd;
	border: 1px solid #777;
	font-family: tahoma;
	font-size:90%;
	font-weight: bold;
}

th.member {
	padding: 0.1em 0.2em 0.1em 0.2em;
}

td.typeheader {
	font-family: tahoma;
	font-size: 100%;
	font-weight: bold;
	background-color: #17b;
	color: white;
	padding: 0 0.2em 0.15em 0.1em;
}

td.n { text-align: right }

a:link.typeheader, a:visited.typeheader, a:link.extenser, a:visited.extenser {
	font-family: tahoma;
	font-size: 90%;
	font-weight: bold;
	text-decoration: none;
	background-color: #17b;
	color: white;
	float:left;
}

a:link.extenser, a:visited.extenser {
	float:right; 
	padding-left:2pt;
	margin-left:4pt
}

span.typeglyph, span.typeglyphx {
	padding: 0 0.2em 0 0;
	margin: 0;
}

span.extenser, span.extenserx {	
	margin-top:1.2pt;
}

span.typeglyph, span.extenser {
	font-family: webdings;
}

span.typeglyphx, span.extenserx {
	font-family: arial;
	font-weight: bold;
	margin: 2px;
}

table.group {
	border: none;
	margin: 0;
}

td.group {
	border: none;
	padding: 0 0.1em;
}

div.spacer { margin: 0.6em 0; }

table.headingpresenter {
	border: none;
	border-left: 3px dotted #1a5;
	margin: 1em 0em 1.2em 0.15em;
}

th.headingpresenter {
	font-family: Arial;
	border: none;
	padding: 0 0 0.2em 0.5em;
	background-color: white;
	color: green;
	font-size: 110%;        
}

td.headingpresenter {
	border: none;
	padding: 0 0 0 0.6em;
}

td.summary { 
	background-color: #def;
	color: #024;
	font-family: Tahoma;
	padding: 0 0.1em 0.1em 0.1em;
}

td.columntotal {
	font-family: Tahoma;
	background-color: #eee;
	font-weight: bold;
	color: #17b;
	font-size:90%;
	text-align:right;
}

span.graphbar {
	background: #17b;
	color: #17b;
	margin-left: -2px;
	margin-right: -2px;
}

a:link.graphcolumn, a:visited.graphcolumn {
	color: #17b;
	text-decoration: none;
	font-weight: bold;
	font-family: Arial;
	font-size: 110%;
	letter-spacing: -0.2em;	
	margin-left: 0.3em;
	margin-right: 0.1em;
}

a:link.collection, a:visited.collection { color: green }

a:link.reference, a:visited.reference { color:blue }

i { color: green; }

em { color: red; }

span.highlight { background: #ff8; }

code { font-family: Consolas }

code.xml b { color:blue; font-weight:normal }
code.xml i { color:maroon; font-weight:normal; font-style:normal }
code.xml em { color:red; font-weight:normal; font-style:normal }
    </style>

    
  </head>
<body><div class="spacer"><table id="t1"><tr><td class="typeheader" colspan="5">Screen[] (2 items)</td></tr><tr><th title="System.Int32">BitsPerPixel</th><th title="System.Drawing.Rectangle">Bounds</th><th title="System.String">DeviceName</th><th title="System.Boolean">Primary</th><th title="System.Drawing.Rectangle">WorkingArea</th></tr><tr><td class="n">32</td><td><table id="t2"><tr><td class="typeheader" colspan="2">Rectangle</td></tr><tr id="sum3"><td colspan="2" class="summary">{X=0,Y=0,Width=3840,Height=2160}</td></tr><tr><th class="member" title="System.Drawing.Point">Location</th><td><table id="t4"><tr><td class="typeheader" colspan="2">Point</td></tr><tr id="sum5"><td colspan="2" class="summary">{X=0,Y=0}</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>True</td></tr><tr><th class="member" title="System.Int32">X</th><td>0</td></tr><tr><th class="member" title="System.Int32">Y</th><td>0</td></tr></table></td></tr><tr><th class="member" title="System.Drawing.Size">Size</th><td><table id="t6"><tr><td class="typeheader" colspan="2">Size</td></tr><tr id="sum7"><td colspan="2" class="summary">{Width=3840, Height=2160}</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>False</td></tr><tr><th class="member" title="System.Int32">Width</th><td>3840</td></tr><tr><th class="member" title="System.Int32">Height</th><td>2160</td></tr></table></td></tr><tr><th class="member" title="System.Int32">X</th><td>0</td></tr><tr><th class="member" title="System.Int32">Y</th><td>0</td></tr><tr><th class="member" title="System.Int32">Width</th><td>3840</td></tr><tr><th class="member" title="System.Int32">Height</th><td>2160</td></tr><tr><th class="member" title="System.Int32">Left</th><td>0</td></tr><tr><th class="member" title="System.Int32">Top</th><td>0</td></tr><tr><th class="member" title="System.Int32">Right</th><td>3840</td></tr><tr><th class="member" title="System.Int32">Bottom</th><td>2160</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>False</td></tr></table></td><td>\\.\DISPLAY1</td><td>True</td><td><table id="t8"><tr><td class="typeheader" colspan="2">Rectangle</td></tr><tr id="sum9"><td colspan="2" class="summary">{X=0,Y=0,Width=3840,Height=2110}</td></tr><tr><th class="member" title="System.Drawing.Point">Location</th><td><table id="t10"><tr><td class="typeheader" colspan="2">Point</td></tr><tr id="sum11"><td colspan="2" class="summary">{X=0,Y=0}</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>True</td></tr><tr><th class="member" title="System.Int32">X</th><td>0</td></tr><tr><th class="member" title="System.Int32">Y</th><td>0</td></tr></table></td></tr><tr><th class="member" title="System.Drawing.Size">Size</th><td><table id="t12"><tr><td class="typeheader" colspan="2">Size</td></tr><tr id="sum13"><td colspan="2" class="summary">{Width=3840, Height=2110}</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>False</td></tr><tr><th class="member" title="System.Int32">Width</th><td>3840</td></tr><tr><th class="member" title="System.Int32">Height</th><td>2110</td></tr></table></td></tr><tr><th class="member" title="System.Int32">X</th><td>0</td></tr><tr><th class="member" title="System.Int32">Y</th><td>0</td></tr><tr><th class="member" title="System.Int32">Width</th><td>3840</td></tr><tr><th class="member" title="System.Int32">Height</th><td>2110</td></tr><tr><th class="member" title="System.Int32">Left</th><td>0</td></tr><tr><th class="member" title="System.Int32">Top</th><td>0</td></tr><tr><th class="member" title="System.Int32">Right</th><td>3840</td></tr><tr><th class="member" title="System.Int32">Bottom</th><td>2110</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>False</td></tr></table></td></tr><tr><td class="n">32</td><td><table id="t14"><tr><td class="typeheader" colspan="2">Rectangle</td></tr><tr id="sum15"><td colspan="2" class="summary">{X=-3840,Y=12,Width=3840,Height=2160}</td></tr><tr><th class="member" title="System.Drawing.Point">Location</th><td><table id="t16"><tr><td class="typeheader" colspan="2">Point</td></tr><tr id="sum17"><td colspan="2" class="summary">{X=-3840,Y=12}</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>False</td></tr><tr><th class="member" title="System.Int32">X</th><td>-3840</td></tr><tr><th class="member" title="System.Int32">Y</th><td>12</td></tr></table></td></tr><tr><th class="member" title="System.Drawing.Size">Size</th><td><table id="t18"><tr><td class="typeheader" colspan="2">Size</td></tr><tr id="sum19"><td colspan="2" class="summary">{Width=3840, Height=2160}</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>False</td></tr><tr><th class="member" title="System.Int32">Width</th><td>3840</td></tr><tr><th class="member" title="System.Int32">Height</th><td>2160</td></tr></table></td></tr><tr><th class="member" title="System.Int32">X</th><td>-3840</td></tr><tr><th class="member" title="System.Int32">Y</th><td>12</td></tr><tr><th class="member" title="System.Int32">Width</th><td>3840</td></tr><tr><th class="member" title="System.Int32">Height</th><td>2160</td></tr><tr><th class="member" title="System.Int32">Left</th><td>-3840</td></tr><tr><th class="member" title="System.Int32">Top</th><td>12</td></tr><tr><th class="member" title="System.Int32">Right</th><td>0</td></tr><tr><th class="member" title="System.Int32">Bottom</th><td>2172</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>False</td></tr></table></td><td>\\.\DISPLAY2</td><td>False</td><td><table id="t20"><tr><td class="typeheader" colspan="2">Rectangle</td></tr><tr id="sum21"><td colspan="2" class="summary">{X=-3840,Y=12,Width=3840,Height=2160}</td></tr><tr><th class="member" title="System.Drawing.Point">Location</th><td><table id="t22"><tr><td class="typeheader" colspan="2">Point</td></tr><tr id="sum23"><td colspan="2" class="summary">{X=-3840,Y=12}</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>False</td></tr><tr><th class="member" title="System.Int32">X</th><td>-3840</td></tr><tr><th class="member" title="System.Int32">Y</th><td>12</td></tr></table></td></tr><tr><th class="member" title="System.Drawing.Size">Size</th><td><table id="t24"><tr><td class="typeheader" colspan="2">Size</td></tr><tr id="sum25"><td colspan="2" class="summary">{Width=3840, Height=2160}</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>False</td></tr><tr><th class="member" title="System.Int32">Width</th><td>3840</td></tr><tr><th class="member" title="System.Int32">Height</th><td>2160</td></tr></table></td></tr><tr><th class="member" title="System.Int32">X</th><td>-3840</td></tr><tr><th class="member" title="System.Int32">Y</th><td>12</td></tr><tr><th class="member" title="System.Int32">Width</th><td>3840</td></tr><tr><th class="member" title="System.Int32">Height</th><td>2160</td></tr><tr><th class="member" title="System.Int32">Left</th><td>-3840</td></tr><tr><th class="member" title="System.Int32">Top</th><td>12</td></tr><tr><th class="member" title="System.Int32">Right</th><td>0</td></tr><tr><th class="member" title="System.Int32">Bottom</th><td>2172</td></tr><tr><th class="member" title="System.Boolean">IsEmpty</th><td>False</td></tr></table></td></tr><tr><td title="Total=64&#xD;&#xA;Average=32" class="columntotal">64</td><td title="Totals" class="columntotal"></td><td title="Totals" class="columntotal"></td><td title="Totals" class="columntotal"></td><td title="Totals" class="columntotal"></td></tr></table></div></body>
</html>

**Comment by vegardlarsen** [comment] 2015-11-23 08:28
@AdamTakvam If I understand you correctly, only MaxTo's UI is affected by this, which is what I have seen on other high-DPI systems. I am working on this, however, it seems to be technically impossible with the technology stack MaxTo is currently based on (WinForms). We are working on a WPF update of MaxTo, which will work a lot better with high-DPI.

@idrake Oh, my. I'm suspecting this is an interaction between two different things, which may be very hard to get rid of on Windows 10. On Windows 10, Microsoft introduced "borderless" windows. The way that they did that, was by making the borders of a window invisible (you can see that by placing the cursor just outside a window edge, it will become a resize arrow).

That means that when MaxTo places a window, it has to take into account the invisible portion of the window as well, and make it slightly larger. When you have two monitors next to each other, that means that the window will technically (hopefully not visibly) be on the other monitor, and that may cause DPI-scaling. I was under the impressions that the window kept the DPI scaling of the monitor that contains the greatest part of its surface area, but I may be mistaken.

**Comment by idrake** [comment] 2015-11-23 13:28
<img width="395" alt="capture" src="https://cloud.githubusercontent.com/assets/697306/11336814/51a210ea-91b6-11e5-874f-976b36d3875f.PNG">

@vegardlarsen I see what you mean by the borderless windows.  I've attached a screen shot of my linq results.  

When I drag a window onto the higher DPI screen it scales to which ever screen it is on the most, like you said.  In fact, my problem isn't that the window scales, just that it overhangs onto my second screen a little and the height is larger than the region I'm docking to.  The link below is a video that shows the screen in action.

http://1drv.ms/1SVvHnM

**Comment by vegardlarsen** [comment] 2015-11-23 13:38
@idrake That video really clarified what happens. Does this happen no matter what window you put in that region? How about re-arranging your monitors (logically) so that the Surface screen is on the left-hand side of your main monitor? Does the problem still happen then?

BTW, I think you are one release behind our current one. Try upgrading to see if your problem with the size not matching the region you set up goes away (after you update you may need to setup your regions again).

**Comment by idrake** [comment] 2015-11-23 15:44
@vegardlarsen Does this happen no matter what window you put in that region? I'll have to try a universal app, but I've tried several win32 apps and they all react the same.

I will update maxTo tonight to answer your questions fully.  Thanks!

**Comment by idrake** [comment] 2015-11-24 02:14
@vegardlarsen I have the latest version 2015.11.1.0.  I tried a universal app and it behaves the same way, so yes all apps have the same issue.

I switched the Surface to the other side of the monitor and the problem switched sides too.  Strangely, the problem on the other side effects the width of the screen and not the height.  The pic should show how the window sized compared to the region.  I also re-ran your linq script with the monitor switched.

![20151124_020602087_ios](https://cloud.githubusercontent.com/assets/697306/11355954/148c5276-9227-11e5-89a8-5a680a3a10cd.jpg)

**Comment by idrake** [comment] 2015-11-24 02:15
<img width="396" alt="capture" src="https://cloud.githubusercontent.com/assets/697306/11355988/588b3e7e-9227-11e5-9183-767bed51e2c2.PNG">

**Comment by idrake** [comment] 2015-12-01 23:57
If it helps any, I just docked my VS.NET tool windows to the right hand side of my monitor and had no issue.  I assume that because of the way Windows calculates tool window sizes it didn't have the problem normal windows have.

**Comment by vegardlarsen** [comment] 2015-12-02 07:14
I am stumped on this. I have a machine that I can test this on with different DPIs on the different screens. I will have a look, but I suspect as I mentioned before that this may be a WinForms issue. The only problem with that assumption is that I've only seen that affect the size of MaxTo's UI, not the size of external applications.

**Comment by Natanji** [comment] 2016-04-03 17:57
Chiming in here because I've just installed MaxTo, and have a problem with it that sounds similar (though maybe not the same?) as this one.

I am running two monitors, one 21:9 monitor (3440x1440) and one 16:9 monitor (1920x1080). The first is set to 150% DPI, the second to 125% DPI. When I open MaxTo, the MaxTo window on the second monitor has a huge margin of about one third of the screen towards the left side - it is just moved waaay too far to the right. ![Screenshot](https://cloud.githubusercontent.com/assets/887286/14233913/21aab83c-f9d6-11e5-9712-4597a19db2c4.jpg)

Is this the issue present here, or should I open a new issue?

**Comment by vegardlarsen** [comment] 2016-04-04 06:41
That would be the same issue. It is all caused by the Windows Forms framework not handling this correctly on multiple monitors. My guess is that it is only the user interfaces that is wrongly placed, the actual regions should be placed correctly on the screen.

I am working on a completely new MaxTo that will not have this issue, but the work is hard and slow.

**Comment by YammYcoding** [comment] 2016-09-17 23:44
I'm still having this issue a year after the issue popped.
windows 10 > video > personalize video > change text and things size > 125%
If I change it to anything other than 100%, the region sizes are calculated wrong. Maybe this is just a math problem ?
What if you try to check if this setting has changed, if yes, add the 25% size to the regions proportion as well ?
ideas ? will it be fixed any time soon ?

thanks

**Comment by vegardlarsen** [comment] 2016-09-19 06:33
This is a problem with Windows Forms, which MaxTo is based on. I am afraid I do not currently have an ETA on this.

**Comment by idrake** [comment] 2016-09-19 21:43
I wonder if anniversary update helped at all?







On Mon, Sep 19, 2016 at 2:33 AM -0400, "Vegard Andreas Larsen" <notifications@github.com> wrote:





This is a problem with Windows Forms, which MaxTo is based on. I am afraid I do not currently have an ETA on this.

**Comment by vegardlarsen** [comment] 2016-09-20 05:53
No, it most definitely did not. Quite the opposite in fact. :)

**Comment by jdunham22** [comment] 2016-10-19 21:58
I just got a new laptop with one high-dpi display, which I use with some regular monitors, and I see similar problems. It seemed to help things if I set all the display text sizes to 100% for all displays, then arranged my MaxTo partitions, and then reset the text sizes, but there is still some weirdness.

I think it's usable enough for now, but if I can help with debugging, please let me know.  Good luck on the WPF version!

**Comment by gorbunovav** [comment] 2016-12-22 18:38
@vegardlarsen maybe it is possible to introduce some manual configurable ratio for each monitor as a workaround for multi-DPI combinations ?

**Comment by vegardlarsen** [comment] 2016-12-24 10:12
@gorbunovav Considering this only happens when configuring regions, and not when resizing windows, I don't think that would be necessary?

The problem here is related to Windows Forms not being able to handle per-monitor DPI.

**Comment by gorbunovav** [comment] 2016-12-26 13:42
> Considering this only happens when configuring regions, and not when resizing windows

@vegardlarsen actually, it happens when resizing windows too. The top position of window is calculated correctly, but width & height are too big (looks like 1.5x, since my primary display has 150% zoom).

So I thought - maybe introducing a way to apply some manual adjustment could be a quick workaround, while we are waiting for the new version.

**Comment by vegardlarsen** [comment] 2016-12-31 09:00
@gorbunovav Then in your case this is the same as issue #30: 4K/hi-DPI support. This is a very tricky issue that I cannot do anything about until I get to exchange Windows Forms (which all of MaxTo is currently based on) for WPF. This is a big change, which is why it is taking so much time.

**Comment by Alsoknownasjazz** [comment] 2017-01-19 17:52
Also having the same issue - the "change regions" UI is so off-kilter I can't define regions effectively. Only my laptop screen was set to non-100% dpi (must've been Windows automagic) and I can live with the DPI dialed down for now. Having all monitors set to 100% DPI fixed this instantly for me.

**Comment by vegardlarsen** [comment] 2017-05-05 12:34
Please see my comment on issue #30 for a possible (likely) fix for this issue. I am closing this issue since I believe them to have the same resolution.

**Closed by vegardlarsen** 2017-05-05 12:34 UTC

**Comment by vegardlarsen** [comment] 2017-05-10 11:45
1. When you move the windows with the shortcut keys, do the controls of that window scale up in size so it looks correctly sized on your high-DPI monitor, but very large on your normal DPI monitor? Does it behave the same when you are dragging the windows?

2. Could you please elaborate on the following quote? It seems to me that you meant to type that you **can't** assign those windows to a region?

> For "system-aware" applications it became worse - I can assign them to any region correctly.

**Comment by gorbunovav** [comment] 2017-05-10 12:00
>When you move the windows with the shortcut keys, do the controls of that window scale up in size so it looks correctly sized on your high-DPI monitor, but very large on your normal DPI monitor? 
@vegardlarsen yes. It looks the same as if you just drag the right margin to expand it to the right monitor.

>Does it behave the same when you are dragging the windows?
No - with dragging this part works good. Drag and then maximize manually works too.

2. Yes, sorry  - I can't assign them. Dragging for this case is broken too.

**Comment by vegardlarsen** [comment] 2017-05-10 12:03
I am not really sure I can do anything about this problem then, because Windows is supposed to handle this automatically when a window crosses a monitor boundary. When you drag a window, you can see the DPI change exactly as the mouse pointer moves to the next screen.

I will look into if this is something I can fake, and cause Windows (or the app itself) to re-evaluate the DPI state after moving with the keyboard.

**Comment by gorbunovav** [comment] 2017-05-10 12:16
@vegardlarsen wait, I think there are two issues. In the first case it is just width is set incorrectly
<img width="2460" alt="2017-05-10 15_12_24-store" src="https://cloud.githubusercontent.com/assets/2665015/25898161/8ffaf53c-3593-11e7-8cb1-a9ace9d38d25.png">
 and it happens with hot-keys only.

**Comment by gorbunovav** [comment] 2017-07-20 15:15
@vegardlarsen I was playing with the AutoHotKey script and have faced the same issue. The solution was to reduce window width by 1 pixel
