### ISSUE TITLE
MaxTo breaks "Epic Pen" screen annotation

### ISSUE THREAD

**Issue by mobelby** [digitalcreations/MaxTo#464] opened 2019-09-01 06:04 UTC
**Describe the bug**
If I have maxto running then as soon as I drag the Epic Pen toolbar it causes the application to crash and become unresponsive with a big black rectangle around that toolbar

**To Reproduce**
Have both apps installed and running and then attempt to drag the Epic Pen toolbar

**Expected behavior**
I should be able to move the Epic Pen toolbar and have the app still work
![190830_1256_18](https://user-images.githubusercontent.com/2020027/64072458-3f0bc080-ccc1-11e9-8f37-425719f2314c.png)

**Screenshots**
Attached showing black rectangle around toolbar

**System information:**
 - Windows version: 10 v 1903 incl cumulative update
 - MaxTo version 2.0.1

**Additional context**

**Comment by mobelby** [comment] 2019-09-01 06:09
My only workaround is to shut down maxto before the drag and then later reopen it when I need the maxto functionality

**Comment by mobelby** [comment] 2019-09-01 12:59
Orb from Tank support (makers of Epic Pen) told me they would be happy to work with you to solve this issue.  
![image](https://user-images.githubusercontent.com/2020027/64076760-67b0ac00-ccfb-11e9-85b9-f0758e4fd05a.png)

**Comment by vegardlarsen** [comment] 2019-09-01 14:05
Thanks for the feedback. Most likely this is due to Epic Pen reacting badly to MaxTo trying to subclass its window (this is usually the cause of crashes such as these). We can work around it by telling MaxTo not to subclass these windows, we'll loose some functionality by doing this, but it seems that these windows wouldn't really benefit from MaxTo's functionality anyway.

You'll need to edit a JSON file to help me test this out, open `%LocalAppData%\MaxTo\shims.json` in your favorite text editor and near the end of the file we'll add the following section:

```json
  {
    "id": "epicpen",
    "descriptions": {
      "en": {
        "title": "Epic Pen",
        "subtitle": "Prevent crashes",
        "description": ""
      }
    },
    "iconUrl": null,
    "url": null,
    "canDisable": true,
    "defaultEnabled": true,
    "ignore": false,
    "disableSubclassing": true,
    "disableSnapping": false,
    "disableTransparency": false,
    "emulatesMaximize": false,
    "windowClasses": [],
    "processes": ["epicpen"]
  }
```

I am assuming here that the process name of the Epic Pen program is `epicpen` (see the `processes` line), which basically means that the file is called `epicpen.exe`. If that is not correct, change that part to the correct name.

After saving this file, restart MaxTo, and see if the problem still exists. If it has been solved, we can work with the Tank folks (please direct them to this issue) to target only the affected the window instead of the entire program.

Please let me know how this works for you, so we can add this to the default shims.

**Comment by mobelby** [comment] 2019-09-01 14:25
Thank you for the reply.
I tried the json code but it does not solve the problem.
The only workaround is the one I mentioned above still.

BTW I have directed Tank Support to this issues page so they can participate

**Comment by battlebottle** [comment] 2019-09-16 12:13
Hi @vegardlarsen 

I'm the lead developer on Epic Pen. Is there anything I can do on my side to make Epic Pen behave better with MaxTo? Is there anything I can do to opt-out of the window sub-classing you describe?

Kind regards,

Brian

**Comment by mobelby** [comment] 2020-01-13 09:35
Hi
I've been waiting for a long time for this incompatibility to be fixed.
In the meantime I have found MaxTo to be rather buggy - eg it often forgets the currently chosen layout, it doesn't launch correctly on startup, it messes up my dual monitors etc

I have been extremely patient but I've given up on MaxTo.
It is a shame that I don't know how to get a refund.

Instead, I'm now using Microsoft PowerToys FancyZones, which are completely compatible with Epic Pen and are much more intuitive to me.

**Comment by vegardlarsen** [comment] 2020-04-11 12:43
I am extremely sorry this has taken so long to resolve.

After trying this with MaxTo 2.1.0-alpha.4, which [is currently in preview](https://maxto.net/release/alpha), I cannot reproduce this problem. Can someone who have experienced this issue please try upgrading to that release?

@mobelby

**Comment by simbalsyd** [comment] 2020-05-27 12:47
I had the same problem and I found this defect ( #464 ). I installed MaxTo 2.1.0-beta2 and now no problem with Epic Pen. Thanks!

**Comment by vegardlarsen** [comment] 2020-05-27 12:49
Thank you for the confirmation. I am closing this issue (as part of 2.1.0), as it seems to have been resolved. :)

**Closed by vegardlarsen** 2020-05-27 12:49 UTC
Labels: compatibility
