### ISSUE TITLE
Windows slightly too big

### ISSUE THREAD

**Issue by jglazer63** [digitalcreations/MaxTo#104] opened 2015-10-04 13:32 UTC
I have multiple monitors (3).  The right and left monitors are split horizontally.  When I place a window in one of these regions and maximize it to the split size, they "bleed" a little into the center monitor.  Only 1 or 2 pixels worth but its a little annoying.  This was after my upgrade to windows 10.  Prior to that it was perfect.

**Comment by vegardlarsen** [comment] 2015-10-05 06:08
@jglazer63 Thanks for reporting this. This happens because of the borderless appearance of windows in Windows 10. We have been working with Microsoft at resolving this.

Quickly summarized, we have to "offset" everything about a window position by 7 pixels, because even though you cannot see them, the window borders are still there. The problem is that the magical value of 7 isn't that magical once you start introducing monitors with different DPI settings. There will most likely be a fix out for this shortly.

**Comment by vegardlarsen** [comment] 2015-11-02 13:15
This should be fixed and ready in the next release.

**Closed** 2015-11-09 12:44 UTC
Labels: bug, fixed, version-2015.07.1, windows-10
