### ISSUE TITLE
Update version 2.2.0 have to select presets on each OS startup

### ISSUE THREAD

**Issue by andus58** [digitalcreations/MaxTo#742] opened 2021-06-18 23:01 UTC
**Describe the bug**
Since installing the last update, my preset selections are cleared on shutdown.
When I restart, I have to go into CHANGE REGIONS and reselect my saved preset for both monitors.

**To Reproduce**
Unable to reduce as a shutdown/restart issue.

1. 
2. 
3. 
4. 

**Expected behavior**
Expect my presets to come up automatically as before, without me having to think about it. :)

**Screenshots**

**System information:**
- Windows version: 10; 21H1 (OS Build 19043.1052)
- MaxTo version: 2.2.0
[MaxTo.zip](https://github.com/digitalcreations/MaxTo/files/6679579/MaxTo.zip)

**Additional context**

Cheers, André

**Comment by andus58** [comment] 2021-06-18 23:44
NOTE this happens only on OS restart. 
MaxtTo is set to autostart. Does not hold settings. 
However if I exit MaxTo, and restart the app, my settings are loaded.

**Comment by Torrad** [comment] 2021-06-19 14:04
Same issue also on my PC since 2.2.0!

**Comment by nativekative** [comment] 2021-06-20 16:32
Exactly same issue.

> NOTE this happens only on OS restart.
> MaxtTo is set to autostart. Does not hold settings.
> However if I exit MaxTo, and restart the app, my settings are loaded.

using 2.2.0

**Comment by vegardlarsen** [comment] 2021-06-21 18:58
This is a duplicate of #739. Closing this one.

The workaround is to turn off the "Use different regions on each virtual desktop" feature, under Settings, Monitor.

**Closed as completed by vegardlarsen** 2021-06-21 18:58 UTC
Labels: duplicate
