### ISSUE TITLE
error

### ISSUE THREAD

**Issue by winxp2600** [digitalcreations/MaxTo#549] opened 2020-04-18 03:36 UTC
![2020-04-18](https://user-images.githubusercontent.com/63891564/79627178-c9c60080-8168-11ea-8fce-ae07cccdb079.png)

**Comment by vegardlarsen** [comment] 2020-04-18 07:44
This is a duplicate of #415. 

In summary, to fix it you can uninstall the crashing package by running the following PowerShell command (as administrator):

```pwsh
get-appxpackage | ? {$_.packagefullname -like '*MicrosoftOfficeHub*'} | remove-appxpackage
```

I am closing this issue as it is a duplicate.

**Closed by vegardlarsen** 2020-04-18 07:44 UTC
