### ISSUE TITLE
Transparency is not removed. When you move the window, it changes its size.

### ISSUE THREAD

**Issue by bantour** [digitalcreations/MaxTo#676] opened 2020-12-07 07:59 UTC
1. When dragging the window border (resizing), the window becomes semi-transparent and remains so until the "Maximize" button is clicked.

https://vimeo.com/487993819/2bc03db3c0

2. When you move the window, it changes its size.

https://vimeo.com/487994452/1dd4928c19

After closing "MaxTo" (this can only be done by killing the process), new windows are created without the described defects.

**System information:**
- Windows version: Windows 10 (1809)
- MaxTo version: 2.1.5
- Two monitors are connected: 3440x1440 and 1920x1080
- Graphic card: Radeon RX 580, driver 26.20.15029.27017

**Comment by vegardlarsen** [comment] 2020-12-07 15:29
@bantour Thank you for this report. I've had this report about Notepad++ from other people privately, but I have not been able to reproduce the issue (until now). I have Notepad++ v7.9.1 (32-bit) running locally, and it does not happen here (Windows 10 20H2). You are running a very old version of Windows 10 (2 years old at this point). This could be a contributing factor, so if updating your Windows installation is going to happen shortly, this would definitely be something you could try.

I was able to reproduce this issue in Windows 10 1709 (on a VM I had lying around related to some other testing), so I will be investigating if that is actually the reason why I am not able to reproduce this locally.

**Comment by bantour** [comment] 2020-12-07 15:50
Hi,
I can reproduce this error with another app, such as Skype.
Andrey Banturov

**Comment by bantour** [comment] 2020-12-08 08:33
I have updated Windows. It didn't help.

**Comment by jaystarkey** [comment] 2020-12-14 19:38
I don't think my issue is an exact duplicate, because it does not affect notepad or skype, and it does not return to normal with maximizing (the only thing that returns it to normal is reopening).

Also, I have a different (newer?) version of Windows 10 than the other user.

**Comment by jaystarkey** [comment] 2021-01-13 16:44
Just FYI, I updated from Windows 10 1909 to 20H2 and the problem resolved.  I had to manually check for an update for the option to update to appear.

**Comment by rasmussen-andreas** [comment] 2021-01-27 15:47
I have the same problem with the entire Microsoft office suite that windows become transparent, with makes the software unusable at the moment. Will try updating tho.

**Comment by artesea** [comment] 2021-03-08 10:12
Just realised that it was this bug and not some random setting within Outlook which was causing the problem for me.
For now I've just changed the setting in MaxTo under Window behavior -> Window transparency to Off.

Windows 10 Enterprise - 1903 (I know that this is end of life, but I have no control over the OS install)
MaxTo 2.1.5

**Comment by vegardlarsen** [comment] 2021-04-25 18:06
If anyone is still experiencing this issue, please try updating to version 2.2.0-beta.2. The easiest way to update is to set your Update channel to Beta in MaxTo's settings.

Please let me know if this is still the case when you are running version 2.2.0-beta.2 or later; as I believe this issue should be solved there (I have not been able to reproduce it using that version).

**Closed by vegardlarsen** 2021-04-25 18:06 UTC
Labels: bug

**Comment by ajrosen-rpci** [comment] 2021-05-11 18:49
I'm running the beta, and still having the issue with Outlook. For now, I've disabled the transparency setting.
