### ISSUE TITLE
Log in with Yahoo email

### ISSUE THREAD

**Issue by hashms0a** [digitalcreations/MaxTo#329] opened 2019-02-06 15:16 UTC
Why I can not log in with my Yahoo email. I ordered MaxTo with my Yahoo mail.
How can I retrieve my license?

**Comment by vegardlarsen** [comment] 2019-02-07 13:02
You can use the [Forgot my password](https://maxto.net/account/forgotpassword) functionality on the website to set a password for your account. 

Your license information is e-mailed to you after registration, so you should have received a copy by e-mail as well.

Closing this issue as it is not a bug or feature request.

**Closed by vegardlarsen** 2019-02-07 13:02 UTC
