### ISSUE TITLE
Some notes after upgrade to 2015 version

### ISSUE THREAD

**Issue by varnar** [digitalcreations/MaxTo#53] opened 2015-02-14 14:40 UTC
1. Issue with right task bar has been resolved
2. When MaxTo is in active mode, and I maximized in regions using shit key to maximize in region - it works fine, after I using Alt key to maximize in alternate mode(full screen) - it does.
   but when after I click and hold on title bar and pressing shift key - it does not work, I need like moving it out alternate region and then do click&hold and shift button.
3. If it is possible, please when I move to window, show me very light, very very light, style the border for active focus places.
4. Some times, when I double click on systray icon and the main region configuration is coming up, I dont see it in my first monitor, where is the Done button placed. My suggestion - have all buttons on both screen :)
5. Did not found diff between hotkeys in Movement and Swap

So far those things only, I will continue to use it and if found anything - I will let you know - than you very much :)

**Comment by vegardlarsen** [comment] 2015-02-15 10:41
2. I will have a look at this, and see what I can figure out.
3. If you hold the Shift key while dragging a window, it will show you an outline of where the window will be dropped.
4. It probably has been buried behind some other window. You can Alt+Tab to it when this happens. However, exactly what happens I don't know, and it happens so rarely that I haven't been able to figure out why.
5. Say you have two regions. There are two windows in the left region and one window in the right region. With the window in the right region in focus, press the Ctrl+Windows+Shift+Left, and that windows swaps position with both windows in the left region. The move shortcuts only move that single window.

**Comment by vegardlarsen** [comment] 2015-03-10 18:09
After having tried this for quite some time, I cannot reproduce the issue where shift+dragging a window docked in an alternate region doesn't work. I am closing this as not reproducible.

**Closed by vegardlarsen** 2015-03-10 18:09 UTC
Labels: bug
