### ISSUE TITLE
Unable to start MaxTo successfully half of the time

### ISSUE THREAD

**Issue by Rollyjoger85** [digitalcreations/MaxTo#305] opened 2018-12-10 09:26 UTC
After the installation of MaxTo (and every reboot) the application fails to start, it almost always gives "Byte array for GUID must be exactly 16 bytes long." error.

If i kill all MaxTo related processes I'm after a few attempts to get the application running, however whatever regions or settings i change are lost when the application starts the next time.

Whenever the application crashes it will usually have two of the 4 (i think it's 4) processes running.
MaxTo.Companion
MaxTo.Companion (32bit)

![2018-12-10 10_18_18-clipboard](https://user-images.githubusercontent.com/40987871/49722703-9feff600-fc65-11e8-926f-a2dbf3245a0b.png)

**System information:**
 - Windows version: Win10 Build 17134.407
 - MaxTo version 2.0.0 Beta 4

[maxto20181210.log](https://github.com/digitalcreations/MaxTo/files/2662457/maxto20181210.log)

**Comment by vegardlarsen** [comment] 2018-12-10 09:29
Raygun report https://app.raygun.com/crashreporting/16323dg/errors/3086505837 has more details about the error

**Comment by CharlieSierra24** [comment] 2018-12-21 16:06
I have the same issue.

**Comment by CharlieSierra24** [comment] 2018-12-21 16:09
[maxto.log](https://github.com/digitalcreations/MaxTo/files/2703411/maxto.log)

**Comment by vegardlarsen** [comment] 2019-01-09 14:39
Have you tried updating to beta 6? I can find no occurences of this issue in beta 4, 5 or 6. But it may just be something wrong with our crash reporting.

**Comment by vegardlarsen** [comment] 2019-01-18 13:32
We've made some changes in beta.8 that may or may not be relevant to this issue. Please update and let me know if the problem is still there.

**Comment by Rollyjoger85** [comment] 2019-01-21 08:14
After the initial fix all my problems were gone, but with beta 8 it's near impossible for me to get MaxTo running, beta 7 was able to run most of the time although it might fail the first couple of times.

Every time i start the application MaxTo.Core will start and attempt to start the MaxTo.Server several times but all instances will eventually be suspended.

[maxto20190121.log](https://github.com/digitalcreations/MaxTo/files/2778013/maxto20190121.log)

**Comment by Rollyjoger85** [comment] 2019-01-21 08:16
**Accidently closed this issue.**

With beta 8 i'm unable to start MaxTo at all, only Core will start all instances of Server will be suspended (and it tries a few times to start them).

Beta 6 was running fine no issues at all, 7 was a little hit and miss but for me 8 is impossible.

[maxto20190121.log](https://github.com/digitalcreations/MaxTo/files/2778020/maxto20190121.log)

**Comment by vegardlarsen** [comment] 2019-01-21 08:56
@Rollyjoger85 Are you running MaxTo elevated? Could the previous version still be running? Does this re-occur after a machine reboot?

**Comment by vegardlarsen** [comment] 2019-01-21 13:40
I see. I think I know the cause. I am looking into it.

**Comment by vegardlarsen** [comment] 2019-01-21 13:41
Marked this with a milestone by mistake. The original issue is still sometimes seen by some users, but I don't know why.

**Comment by vegardlarsen** [comment] 2019-01-22 12:44
So after some thinking here, the exception in our logs appear to be because you have two MaxTo.Server processes running (one of which is suspended). I think that terminating that process should solve your problem.

MaxTo uses an `EventWaitHandle` to synchronize when a started MaxTo process is ready. When a second MaxTo.Server process is started, this wait handle is already busy; and it fails to be created, effectively preventing two processes from being started.

I don't know the situation that caused the Server process to be started twice, however, so I will be looking out for that.

**Comment by CharlieSierra24** [comment] 2019-01-23 00:00
My system has stabilized, yes, after terminating it a few times it's been
reliable for some time now.

**Comment by vegardlarsen** [comment] 2019-01-28 12:45
@Rollyjoger85 is that the case for you as well?

**Comment by Rollyjoger85** [comment] 2019-01-28 15:18
Yes, after I let the application recreate the config file I haven't had any issues starting MaxTo

**Comment by vegardlarsen** [comment] 2019-03-07 11:23
I am closing this as it is no longer a problem for any of the original posters.

**Closed by vegardlarsen** 2019-03-07 11:23 UTC
Labels: bug
