### ISSUE TITLE
MaxTo Error from Windows May 2019 Update

### ISSUE THREAD

**Issue by mja09006** [digitalcreations/MaxTo#439] opened 2019-07-05 04:28 UTC
Error message pops up after starting Windows 10 and signing into my account. Issue began right after installing Windows 10 May 2019 Update. Software still works properly but error messages are annoying.

Prior to this update MaxTo worked perfectly with no pop up errors.

![Untitled](https://user-images.githubusercontent.com/52556927/60698097-c902fd00-9ebb-11e9-9e07-fc68248b2edc.png)

 - Windows 10
 - MaxTo 2.0.1

**Comment by vegardlarsen** [comment] 2019-07-07 13:53
Sorry for the slow response on this; this is the same issue as #415, and can probably be fixed by resetting or reinstalling the "GameLibraryAppService.exe" program (see details in the other thread). I don't know exactly what kind of program that is, but this error appears due to the Windows 10 1905 update, as you say.

**Comment by greenaar** [comment] 2019-07-09 17:03
I'm seeing this on a number of applications, in this case the entire office suite. a repair and reset on the suite seems to have fixed it, but it's pretty random as to which apps are affected.

**Comment by vegardlarsen** [comment] 2019-07-10 06:52
Closing as a duplicate of #415.

**Closed** 2019-07-10 06:51 UTC
