### ISSUE TITLE
MaxTo.Hook.x64.dll crash in clipboard service

### ISSUE THREAD

**Issue by ahupp** [digitalcreations/MaxTo#630] opened 2020-10-28 08:23 UTC
**Describe the bug**
I occasionally get into a state where taking a screenshot (via Win+Shift+S) takes 2 minutes, and then fails.  I found in the Event Log a crash in MaxTo.Hook.x64.dll in svchost.exe_cbdhsvc, which is I believe the clipboard service.  Restarting MaxTo fixed the problem.  

**To Reproduce**
It's not clear how to reproduce this.

**Expected behavior**
Taking a screenshot works.

**System information:**
- Windows version: 10.0.19041.572
- MaxTo version: 2.0.1

**Additional context**
I've attached the maxto log, and my event viewer entries.

[maxto20201028.log](https://github.com/digitalcreations/MaxTo/files/5450492/maxto20201028.log)

[maxto_hook_crash.zip](https://github.com/digitalcreations/MaxTo/files/5450499/maxto_hook_crash.zip)

**Comment by vegardlarsen** [comment] 2020-10-28 08:56
Thank you for reporting this. I believe this issue should be fixed in version 2.1.0-beta.5, available by setting your update channel to Beta and restarting MaxTo twice. Can you please check if that is the case?

**Comment by ahupp** [comment] 2020-10-28 16:06
I'll try that out.  This doesn't happen 100% of the time so won't be able to definitively say its fixed.

**Comment by vegardlarsen** [comment] 2020-10-28 20:34
After having been able to sit down on a computer, this is a duplicate of issue #386, which we've fixed for 2.1.0. I am closing this issue. Feel free to comment again if I am mistaken. :)

**Closed by vegardlarsen** 2020-10-28 20:34 UTC
Labels: needs-information
