### ISSUE TITLE
taskbar lost active app highlights

### ISSUE THREAD

**Issue by ferryperry** [digitalcreations/MaxTo#430] opened 2019-06-17 10:51 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**
 - Windows version: [e.g. 10, 8, 8.1]
 - MaxTo version [e.g. 22]

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

**Comment by vegardlarsen** [comment] 2019-06-17 13:13
Closing as duplicate of #431

**Closed by vegardlarsen** 2019-06-17 13:13 UTC
