### ISSUE TITLE
Crashed in Comodo Containment

### ISSUE THREAD

**Issue by sulpdang** [digitalcreations/MaxTo#391] opened 2019-04-05 04:09 UTC
**Describe the bug**
I use the comodo firewall for protecting my computer. When I launch the application in comodo containment, It crashed and generate error messages. To resolve it, I used to kill the process both 'MaxTo.Companion.X64.exe' and 'MaxTo.Companion.X86.exe'. 

**To Reproduce**
1. Execute application in comodo containment.
2. It crashed.

**Expected behavior**
Previous version of maxto can control the applications even if it runs in comodo containment or not.

**System information:**
 - Windows version: 10
 - MaxTo version : 2.0.0, 2.0.1

**Additional context**
2019-04-05 13:17:51 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #10592)
2019-04-05 13:17:52 [Core@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\sulpd\AppData\Roaming\MaxTo"
2019-04-05 13:17:52 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #10592)
2019-04-05 13:17:52 [Core@2.0.1.499] [Information] Read shims from "C:\Users\sulpd\AppData\Local\MaxTo\shims.json"
2019-04-05 13:17:52 [Core@2.0.1.499] [Information] Squirrel-installed app, so rewriting CLI batch file.
2019-04-05 13:17:53 [Core@2.0.1.499] [Information] No updates found
2019-04-05 13:17:53 [Core@2.0.1.499] [Information] Was started as normal user, expected elevated. Restarting.
2019-04-05 13:17:53 [Core@2.0.1.499] [Information] Restarting MaxTo with arguments "--elevated --waitforexit 10592"
2019-04-05 13:17:55 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #14020)
2019-04-05 13:17:55 [Core@2.0.1.499] [Information] Process #10592 was not running, continuing with startup.
2019-04-05 13:17:55 [Core@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\sulpd\AppData\Roaming\MaxTo"
2019-04-05 13:17:55 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #14020)
2019-04-05 13:17:56 [Core@2.0.1.499] [Information] Read shims from "C:\Users\sulpd\AppData\Local\MaxTo\shims.json"
2019-04-05 13:17:56 [Core@2.0.1.499] [Information] Squirrel-installed app, so rewriting CLI batch file.
2019-04-05 13:17:57 [Core@2.0.1.499] [Information] No updates found
2019-04-05 13:17:57 [Server@2.0.1.499] [Information] Logger setup (online logging: True, process #8388)
2019-04-05 13:17:57 [Core@2.0.1.499] [Information] Server up and running, client connected.
2019-04-05 13:17:57 [Core@2.0.1.499] [Information] 4 processes started
2019-04-05 13:17:58 [CompanionX64@2.0.1.499] [Information] Logger setup (online logging: True, process #4568)
2019-04-05 13:17:58 [CompanionX86@2.0.1.499] [Information] Logger setup (online logging: True, process #4676)
2019-04-05 13:17:58 [CompanionX64@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\sulpd\AppData\Roaming\MaxTo"
2019-04-05 13:17:58 [CompanionX86@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\sulpd\AppData\Roaming\MaxTo"
2019-04-05 13:17:58 [CompanionX64@2.0.1.499] [Information] Read shims from "C:\Users\sulpd\AppData\Local\MaxTo\shims.json"
2019-04-05 13:17:58 [CompanionX64@2.0.1.499] [Information] Enabled hook
2019-04-05 13:17:58 [CompanionX86@2.0.1.499] [Information] Read shims from "C:\Users\sulpd\AppData\Local\MaxTo\shims.json"
2019-04-05 13:17:58 [CompanionX86@2.0.1.499] [Information] Enabled hook
2019-04-05 13:17:58 [UserInterface@2.0.1.499] [Information] Logger setup (online logging: True, process #14140)
2019-04-05 13:17:59 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.ViewModels.NotificationIconViewModel"
2019-04-05 13:19:19 [Core@2.0.1.499] [Error] Process CompanionX64 exited without explanation
2019-04-05 13:19:19 [Server@2.0.1.499] [Warning] Lost connection to "c23e1160-d282-4ffb-a187-517bd457b640"
System.IO.IOException: 파이프가 끊어졌습니다.
   위치: System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   위치: System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)

**Comment by sulpdang** [comment] 2019-04-05 04:22
I accidentally click the closed button... Sorry.

**Comment by vegardlarsen** [comment] 2019-04-05 13:43
Unfortunately there is not much I can see from those logs, but I will try to figure out what happens to see if this can be remedied. There does however not appear to be any open version of Comodo Containment we can try this with?

**Comment by sulpdang** [comment] 2019-04-06 20:41
I use the Comodo Firewall 11 for protecting my computer. In Comodo Firewall 11, There is a function which name is Auto-Containment, it provides virtual environment for application. I used the word, Comodo Containment, to describe that function.(I'm sorry if I confused you).

In addition, it throws an error message.

0x000000003D095F8C에 있는 명령이 0x0000000000000004의 메모리를 참조했습니다. 메모리는 read될 수 없습니다.
* In English, 'The Instruction at 0x000000003D095F8C referenced memory at 0x0000000000000004. The memory could not be 'read'

And The Options of Comodo Firewall 11 that I use are 
- Firewall -> Safe Mode
- Auto-Containment -> Disabled
- HIPS -> Safe Mode
- VirusScope -> Enabled
- Website Filtering -> Enabled

If you require more specific options, I will comment it.
Also, I observed that MaxTo 1.x doesn't produce these error messages. It works well.
I hope this problem will resolve soon. Thanks!!

**Comment by vegardlarsen** [comment] 2019-04-11 13:44
I will investigate this issue, but it may very well be something that is not fixable on our end. MaxTo works by "injecting" its own running code into every program running on the system. It appears Comodo Auto-Containment works by creating separate containers that MaxTo cannot properly penetrate. In the best case we can prevent the application from crashing, but I am not sure yet.

**Comment by vegardlarsen** [comment] 2020-04-04 12:06
I cannot reproduce this issue. I installed Comodo Firewall (now at version 12) on a fresh install of Windows 10, and it does not put MaxTo in containment (I made sure to enable Auto-Containment).

As I cannot reproduce this, and the fact that running MaxTo "contained" from everything else in your system sort of defeats the purpose of running MaxTo, I am closing this issue as won't fix.

**Closed by vegardlarsen** 2020-04-04 12:06 UTC
Labels: bug
