### ISSUE TITLE
Installation error on windows 7

### ISSUE THREAD

**Issue by tricatch** [digitalcreations/MaxTo#181] opened 2017-07-05 00:22 UTC
![maxto_install_error](https://user-images.githubusercontent.com/21252282/27844900-3eea5722-6163-11e7-9000-07426773f781.png)
![maxto_install_error2](https://user-images.githubusercontent.com/21252282/27844911-721f2f14-6163-11e7-849e-b5480979de61.png)

**Comment by vegardlarsen** [comment] 2017-07-05 06:32
Hi, as of the latest release we only support Windows 7 SP1 and above. Which version are you running?

**Comment by tricatch** [comment] 2017-07-05 08:47
![windows7sp1](https://user-images.githubusercontent.com/21252282/27856769-135aa9d0-61aa-11e7-973e-645b0e32f5ea.png)

**Comment by vegardlarsen** [comment] 2017-07-06 13:39
Can you run `winver` to get the actual version?

**Comment by tricatch** [comment] 2017-07-06 23:55
![winver](https://user-images.githubusercontent.com/21252282/27937446-100fb952-62f2-11e7-8c8b-bcd1a7c04560.png)

**Comment by vegardlarsen** [comment] 2017-07-07 06:11
Can you try installing the .NET Framework version 4.7 and see if that helps?

**Comment by tricatch** [comment] 2017-07-07 08:52
.net4.7 already installed.

![net47](https://user-images.githubusercontent.com/21252282/27950634-03ee280c-633d-11e7-9d66-a3448f4e85d3.png)

**Comment by vegardlarsen** [comment] 2017-07-10 12:54
Can you try downloading and installing [this version of MaxTo](https://www.dropbox.com/s/1wmilsehk7h7emi/MaxToSetup-2017-07-1.exe?dl=0) instead? You can check that the file is digitally signed before installing.

**Comment by tricatch** [comment] 2017-07-11 03:32
17.07.01 same as 17.07

![maxto17 07 01](https://user-images.githubusercontent.com/21252282/28049858-0c083a96-6635-11e7-9b23-ee55f26d324b.png)

**Comment by tricatch** [comment] 2017-07-26 02:19
I had installed maxto 2017.7

1) MaxToSetup-2017-07.exe /a
then, extract all files in the \Digital Creations AS\MaxTo 17.07\install\80AB7EA

2) MaxToSetup-2017-07.exe

**Comment by vegardlarsen** [comment] 2017-08-07 10:47
Good to hear you got it to work. I still don't know what caused this, but I cannot reproduce it currently. I am closing this, but anyone else who may experience this is welcome to comment here.

**Closed by vegardlarsen** 2017-08-07 10:47 UTC
