### ISSUE TITLE
Can't Install Old Versions of MaxTo

### ISSUE THREAD

**Issue by allan-shoup** [digitalcreations/MaxTo#744] opened 2021-06-30 13:58 UTC
**Describe the bug**
I had MaxTo v2.2.0 installed and it seemed to cause my tray to disappear. I attempted to downgrade to [v2.1.5](https://files.maxto.net/releases/2.1.5/MaxToSetup-2.1.5.exe), but every time I attempted to install that version, version 2.2.0 would be installed instead.

**System information:**
- Windows version: 2004 build 19041.1052

**Comment by vegardlarsen** [comment] 2021-06-30 17:43
Thank you for writing. We are aware of this issue. It is caused by our installer, which is very diligent in updating you to the latest version. If you instead download the ZIP archive, and "install" MaxTo manually, this will no longer happen.

Since we already have issue #668 on this, I am closing this one as a duplicate.

**Closed as completed by vegardlarsen** 2021-06-30 17:43 UTC
Labels: duplicate
