### ISSUE TITLE
Software loses license. "Welcome" popup on boot.

### ISSUE THREAD

**Issue by afrorowan** [digitalcreations/MaxTo#444] opened 2019-07-16 06:52 UTC
**Describe the bug**
Sometimes after the computer boots, the "Welcome. Let's get started" popup comes up and it asks for a license key. This license key should already be known. I have a corporate license key with 2 seats for 3 years. It looks like the issue happens after the computer got an update via SCCM Software Center and the PC reboots. 

**To Reproduce**
1. Just happens randomly after a reboot. (Does not happen on every reboot)
2. Looks like it happens after windows updates

**Expected behavior**
The expectation is that the license is kept and filled at all times until expiry

**Screenshots**
Not applicable

**System information:**
 - Windows 10 Enterprise (Version 1803 Build 17134.829)
 - MaxTo version 2.0.1

**Additional context**
Log files do not show any signs of errors or strange behavior

**Comment by vegardlarsen** [comment] 2019-07-17 10:43
Thank you for your report. This is a duplicate of #314, so I am closing this issue.

Things to check:

1. Does the `%AppData%\MaxTo\license.txt` file exist after setting the license?
2. Is it deleted at some point?
3. Creating that file manually and pasting your entire license key into it, does that file also disappear?

Please follow up in issue #314.

**Closed by vegardlarsen** 2019-07-17 10:43 UTC
