### ISSUE TITLE
mouse cursor disappears

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#370] opened 2019-03-15 14:41 UTC
Not sure, quite how I managed that. But I suspect MaxTo had a role.
Don't really remember quite how that happened.
Did a restart and it was back, didn't feel like exploring that state.
And I'm not gonna try to hunt it down and try to reproduce.
Should it happen again, I'll probably pay more attention.

Though Windows sometimes does that to me, without MaxTo being installed.
So I don't know. Just a data point, should it crop up again, I guess.

**Comment by vegardlarsen** [comment] 2019-03-15 14:50
If this should happen again, and you can verify that this is an issue caused by MaxTo (in this case, you stated that it also happened without MaxTo installed).

I will close this issue as there is simply nothing I can do about it.

**Closed by vegardlarsen** 2019-03-15 14:50 UTC
