### ISSUE TITLE
Windows Transparency getting "stuck" - Reference closed issue #561

### ISSUE THREAD

**Issue by Alsoknownasjazz** [digitalcreations/MaxTo#665] opened 2020-11-19 14:35 UTC
**Describe the bug**
When dragging application windows around, they become transparent, and do not revert to full opacity when mouse-left is released. Once this has happened, almost no amount of moving, maximizing, snapping or resizing will bring the window back to normal - the application has to be closed now. Having Windows Transparency option in MaxTo disabled does not prevent this behavior. In fact, does not consistently prevent the windows from becoming transparent in the first place. This behavior is inconsistent, but frequent. I have recreated this behavior with Chrome (browser), Windows File Explorer, Dreamweaver 3. 

**To Reproduce**
1. Drag a window out of full-screen (maximized) via left click+hold on the application header bar at the top.
  a. The window will frequently, though not always, become transparent.
3. Release the left mouse button.
  a. The window will frequently, though not always, remain transparent.

**Expected behavior**
Windows should resume full opacity upon mouse-left release.
Windows should not become transparent in the first place if MaxTo>Window behavior>Window transparency> is set to Off

**Screenshots**
Screenshot of one File Explorer window on top of another -- the top one is transparent. Captured after MaxTo was set to Windows Transparency > Off, and MaxTo was restarted. 
![image](https://user-images.githubusercontent.com/5556960/99679887-755e6880-2a4a-11eb-8fea-a16c5d708a23.png)

**System information:**
- Windows version: Version 2004 (OS Build 19041.630)
- MaxTo version: 2.1.1

**Additional context**
Reference closed issue: Windows Stay Transparent after moving it. #561
[config.zip](https://github.com/digitalcreations/MaxTo/files/5567355/config.zip)

**Comment by vegardlarsen** [comment] 2020-11-19 15:07
@Alsoknownasjazz Please update to version 2.1.2. The easiest way is to restart MaxTo twice, and then reboot (to get rid of the windows that were stuck as transparent).

I am closing this issue as a duplicate of #656.

**Closed by vegardlarsen** 2020-11-19 15:07 UTC

**Comment by Alsoknownasjazz** [comment] 2020-11-19 18:28
Thanks for the quick response. Unfortunately, 2.1.1 was a typo, I'm running 2.1.2 already. :(
