### ISSUE TITLE
Apps resize improperly in multi-monitor, multi-resolution setups

### ISSUE THREAD

**Issue by SnoFox** [digitalcreations/MaxTo#186] opened 2017-09-16 20:44 UTC
Hi there,

Certain apps, such as Sublime Text, Franz, and Process Explorer do not resize properly in my setup.

Here's some information about my setup. Let me know if anything else is required -- MaxTo is super important to my workflow, so I'm happy to try dev/debug builds or find more software/hardware information.

- OS: Windows 10 Pro, version 1703 (build 15063.608)
- MaxTo: 2017.7.0.0, passive mode
- Monitors:
  - Center 2560×1440, (1440p landscape); UI scaling 125%
  - Left 1920x1080, (1080p landscape); UI scaling 100%
  - Right 1080x1920, (1080p portrait); UI scaling 100%

Behaviors observed:
- Scaling Sublime Text to left monitor does not set the top boarder properly; I generally lose the titlebar off the top of the monitor. (Trying with a 825x511 region in the top right and bottom right quadrants)
- Scaling Sublime Text/Franz to right monitor does not set the top nor left boarders properly; the app overflows into the center monitor (Trying with 1072x451 regions)

**Comment by vegardlarsen** [comment] 2017-09-18 06:17
Does it become better if you set UI scaling to 100% on the center monitor? It may be a result of having different UI scaling on the monitors.

**Comment by SnoFox** [comment] 2017-09-18 06:57
That does appear to solve the issue for a couple programs.

**Comment by vegardlarsen** [comment] 2017-09-18 08:46
Can you elaborate on that? Does apps behave differently when you put them in the same regions?

**Comment by SnoFox** [comment] 2017-09-18 20:19
That is correct. When I move misbehaving apps, like Sublime Text, into the same region, it reacts differently depending on the UI scale of my primary monitor.

At 100% scale, Sublime stays inside the bottom right region of the left monitor (although it doesn't entirely fill it, it's more preferential behavior). At 125%, Sublime overfills into the top right region. Example: https://youtu.be/y0eI8GuGllI

Similarly, Sublime text will fit itself correctly at 100% scale on my right monitor regions, but overflows left and up at 125% scaling. Example: https://youtu.be/gXEBWguiOqI

In both examples, I'm only changing the UI scale of my primary, center monitor.

**Comment by vegardlarsen** [comment] 2017-09-19 07:20
Thank you for the videos. They make the problem very clear.

It appears to me that Sublime Text ends up aligning the bottom of the menu bar with the top of the region. I am not sure why, but it may be related to the negative margins we apply to windows on Windows 10 to get rid of the invisible borders each window has. Basically we ask a window what size borders it has, and we apply negative margins to counter those borders (which are invisible). If Sublime Text reports the header and menu bar as "borders", this could cause this issue.

I will be looking into this more.

**Comment by rustamsh** [comment] 2018-01-28 13:00
I also experience the same issue. I have main monitor with 125% scale another 100%, when I move sublime or some other apps to the edge of my main monitor the app becomes larger. It would be great if you could provide us with the fix

**Comment by xxflop** [comment] 2018-03-21 15:36
I'm having problems also with the regions when the external monitor is powered off and on. The regions got adapted for fullhd resolution (laptop LCD resolution), but they don't get resized correctly to 4K when the external monitor is powered on again. I'm using just one display at a time. Restarting the program solve the problem, but it is not ideal. If I show the regions they appear at half size on the 4K display so they don't work as expected because the regions only cover the top left quarter of the screen:

![image](https://user-images.githubusercontent.com/30904656/37719553-98bae364-2d25-11e8-8b63-104af311d632.png)

**Comment by vegardlarsen** [comment] 2018-03-22 14:46
@xxflop Is this on Windows 10? Which update?

**Comment by xxflop** [comment] 2018-03-22 15:35
It is Windows 10 Enterprise, Version 10.0.16299. 

Just in case it is useful, these are the graphic cards & displays involved:

Name	Intel(R) HD Graphics 4600
PNP Device ID	PCI\VEN_8086&DEV_0416&SUBSYS_221E17AA&REV_06\3&33FD14CA&0&10
Adapter Type	Intel(R) HD Graphics Family, Intel Corporation compatible
Adapter Description	Intel(R) HD Graphics 4600
Adapter RAM	1,00 GB (1.073.741.824 bytes)
Installed Drivers	igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igd12umd64.dll
Driver Version	20.19.15.4835
INF File	oem9.inf (iHSWM_w10 section)
Color Planes	Not Available
Color Table Entries	4294967296
Resolution	**1920 x 1080 x 60 hertz**
Bits/Pixel	32
Memory Address	0xB3400000-0xB37FFFFF
Memory Address	0x80000000-0x9FFFFFFF
I/O Port	0x00005000-0x0000503F
IRQ Channel	IRQ 4294967289
I/O Port	0x000003B0-0x000003BB
I/O Port	0x000003C0-0x000003DF
Memory Address	0xA0000-0xBFFFF
Driver	c:\windows\system32\drivers\igdkmd64.sys (20.19.15.4835, 7,60 MB (7.972.320 bytes), 27/05/2016 21:15)

Name	NVIDIA Quadro K1100M
PNP Device ID	PCI\VEN_10DE&DEV_0FF6&SUBSYS_221A17AA&REV_A1\4&382AACEF&0&0008
Adapter Type	Quadro K1100M, NVIDIA compatible
Adapter Description	NVIDIA Quadro K1100M
Adapter RAM	(2.147.483.648) bytes
Installed Drivers	C:\WINDOWS\System32\DriverStore\FileRepository\nvltwi.inf_amd64_6fcf741763d67140\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvltwi.inf_amd64_6fcf741763d67140\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvltwi.inf_amd64_6fcf741763d67140\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvltwi.inf_amd64_6fcf741763d67140\nvldumdx.dll
Driver Version	23.21.13.9077
INF File	oem128.inf (Section070 section)
Color Planes	Not Available
Color Table Entries	4294967296
Resolution	**3840 x 2160 x 59 hertz**
Bits/Pixel	32
Memory Address	0xB2000000-0xB30FFFFF
Memory Address	0xA0000000-0xB1FFFFFF
Memory Address	0xB0000000-0xB1FFFFFF
IRQ Channel	IRQ 4294967288
Driver	c:\windows\system32\driverstore\filerepository\nvltwi.inf_amd64_6fcf741763d67140\nvlddmkm.sys (23.21.13.9077, 16,68 MB (17.493.824 bytes), 01/02/2018 9:14)

Is there any way (falg/configuration) to enable extra logging on Maxto so we can diagnose this easily?

**Comment by vegardlarsen** [comment] 2018-03-23 06:22
And you are running MaxTo 2017.07?

This was usually caused by the mixed-DPI of the two monitors, which Windows didn't add proper handling for until Windows 10 Creators Update and .NET Framework 4.7, and MaxTo hooks into this improved support if you have MaxTo 2017.07.

**Comment by xxflop** [comment] 2018-03-23 07:13
Yes, I'm running MaxTo 2017.07

![image](https://user-images.githubusercontent.com/30904656/37816093-ecb27a02-2e71-11e8-8741-721e931553c0.png)

Is there any way I can enable extra logging so we can diagnose this when it happens (it is not always, just sometimes)?

**Comment by xxflop** [comment] 2018-03-27 10:35
Even weirder... now it happened to 1/4 of the screen, like if happened the problem twice and the regions only covered now 1/16 of the screen, the top left 1/16:

![image](https://user-images.githubusercontent.com/30904656/37962190-a0cbae28-31ba-11e8-9115-3ec24014083e.png)

After restarting the app, the region come back to normal:

![image](https://user-images.githubusercontent.com/30904656/37962259-d245f2d8-31ba-11e8-9490-5465dc7c2732.png)

Is it possible to make Maxto to "autocheck" that the resolution/dpi is what it is expected every X seconds or something like that? I guess that you are hooking to some kind of change resolution/dpi event but maybe it is buggy/unreliable under some circumstances.

**Comment by vegardlarsen** [comment] 2018-04-23 05:54
The resolution check we are doing currently does have bugs (it is based on the `System.Windows.Forms.Screen` class in .NET Framework). One of them being that it caches any values it provides until the next screen change event is raised. This means that once it gets bad data, that data stays there until either MaxTo is restarted or the resolution is changed.

We are working around this issue in an upcoming release of MaxTo by avoiding this class entirely.

**Comment by xxflop** [comment] 2018-04-23 06:06
Perfect.

When the new version will be released? Will be any kind of notification
(email or in the app) when it is available?

Thanks.

**Comment by vegardlarsen** [comment] 2018-04-23 06:09
We do not have a set release date, but we are getting close to putting out an alpha release. A lot of things have changed (almost everything in MaxTo in fact). We will announce the alpha release on this issue tracker.

**Comment by vegardlarsen** [comment] 2018-05-25 07:08
This should be fixed in the preview releases (see #220). Please have a go to see if this fixes your issues.

**Closed by vegardlarsen** 2018-05-25 07:08 UTC
Labels: bug, version-2017.07, windows-10
