### ISSUE TITLE
v 2.1.0-alpha2 Some windows do not restore opacity after being moved

### ISSUE THREAD

**Issue by indigodreamer** [digitalcreations/MaxTo#521] opened 2019-12-17 11:30 UTC
**Describe the bug**
Some windows become progressively more transparent each time they are moved. Eventually they become completely invisible but moving the invisible window further cycles it back to opacity
Workaround: This does not happen when I switch off "Window Transparency" within MaxTo's settings

**To Reproduce**
Not all apps or even windows within the same app show this behaviour. 
Launch Notepad++  (v7.8.1 and 7.8.2, 64 bit)
Drag the window round several times

**Expected behavior**
Window should be restored to former opacity

**Screenshots**
I don't think this is necessary but can send screenshots if this is wrong

**System information:**
Windows v10, 64bit

**Additional context**
I don't think log files will help

**Comment by thewavelength** [comment] 2019-12-17 11:52
Same happens when just clicking once on the windows edges. Also happens on latest Firefox.

**Comment by vegardlarsen** [comment] 2019-12-19 08:25
I will attempt to reproduce this locally.

**Comment by lucaslink** [comment] 2019-12-20 20:04
This happens to me as well in the Adobe CC suite. Easiest steps to reproduce, open a photoshop document with layers, double click a layer to bring up the layer style modal, click and drag the window a few times. After a few clicks and drags it cycles through a few levels of transparency.

**Comment by vegardlarsen** [comment] 2020-01-03 13:33
@indigodreamer @lucaslink @thewavelength I am unable to reproduce this locally with both the latest internal builds and version 2.1.0-alpha.2. I tried Notepad++ 7.8.2, Firefox 71, and Photoshop CC as listed above, and it worked exactly the way it was meant.

Do any of you have a more reliable way of reproducing this?

**Comment by lucaslink** [comment] 2020-01-03 16:34
@vegardlarsen 
I'm not sure how you're not experiencing this or how to make reproducing this any easier. Have a look:
[https://imgur.com/a/p1l3Zlz](url)

Photoshop CC 20.0.08 (latest version, though this also happened with the two prior versions) on Windows 10 Pro (64) Build 18362 w/ MaxTo 2.1.0-alpha2.

**Comment by vegardlarsen** [comment] 2020-01-06 10:17
That is quite noticable indeed. Can you try updating to alpha-3, which was released on Friday? I don't think it will make a difference, but it might.

**Comment by yamlCase** [comment] 2020-01-18 17:14
I notice the same behavior with Aquasnap on Windows 10 1909

**Comment by vegardlarsen** [comment] 2020-03-17 21:27
This should be fixed in 2.1.0-alpha.4. Please download it once it is ready and let me know.

**Closed** 2020-03-17 21:27 UTC
Labels: bug

**Comment by kal10bach** [comment] 2020-07-18 09:12
hi, the same with me using 2.1.0 beta2
yet nothing found to reproduce it on demand
thx
georg
