### ISSUE TITLE
Maximized window drag bug

### ISSUE THREAD

**Issue by Dev1lDragon** [digitalcreations/MaxTo#729] opened 2021-06-02 16:38 UTC
When window is maximized and normal screen and maximized screen have distinct widths, window jump outside of pointer and in some cases, when not careful, this window can be lost outside of viewport.

![drag-bug](https://user-images.githubusercontent.com/9211475/120517910-e05d0480-c3c8-11eb-905f-5fba51b2db75.png)
Position of pointer is marked by red dot

MaxTo: 2.1.5
Windows:  Windows 10 Pro / 21H1 / 19043.985

**Comment by vegardlarsen** [comment] 2021-06-02 17:43
I think this is a duplicate of #650.

If you update to version 2.2.0-beta.2 (set your Update Channel to Beta in MaxTo's settings), I believe the problem should disappear.

**Closed by vegardlarsen** 2021-06-02 17:43 UTC
Labels: duplicate
