### ISSUE TITLE
GUI not starting

### ISSUE THREAD

**Issue by Resourn** [digitalcreations/MaxTo#337] opened 2019-02-11 13:00 UTC
Hi,

I am unable to start the GUI after we activated bitlocker on our domain computers. I tried to install the latest version but the issue remains. All processes appears to start as they should but the GUI is nowhere to be seen. I have attached the error log.

Currently running windows 10 1809 17763.253 and MaxTo Beta10

[maxto20190211_2.txt](https://github.com/digitalcreations/MaxTo/files/2851101/maxto20190211_2.txt)

**Comment by vegardlarsen** [comment] 2019-02-11 13:14
Do you have User Account Control disabled on your machine? Anything else special?

**Comment by vegardlarsen** [comment] 2019-02-11 13:14
Stack trace from log for my reference: 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaxTo.Core.UAC.UserAccountControl.get_IsEnabledOnMachine()
   at MaxTo.UI.Components.Settings.Startup.StartupViewModel..ctor(IMessageBus bus, IConfigurationManager configurationManager, IUserAccountControl uac)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Caliburn.Micro.SimpleContainer.ActivateInstance(Type type, Object[] args)
   at Caliburn.Micro.SimpleContainer.<>c__DisplayClass7_0.<RegisterSingleton>b__0(SimpleContainer container)
   at Caliburn.Micro.SimpleContainer.<GetAllInstances>b__12_0(Func`2 x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Caliburn.Micro.SimpleContainer.GetInstance(Type service, String key)
   at Caliburn.Micro.SimpleContainer.<DetermineConstructorArgs>b__22_0(ParameterInfo info)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Caliburn.Micro.SimpleContainer.DetermineConstructorArgs(Type implementation)
   at Caliburn.Micro.SimpleContainer.<>c__DisplayClass7_0.<RegisterSingleton>b__0(SimpleContainer container)
   at Caliburn.Micro.SimpleContainer.GetInstance(Type service, String key)
   at Caliburn.Micro.SimpleContainer.<DetermineConstructorArgs>b__22_0(ParameterInfo info)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Caliburn.Micro.SimpleContainer.DetermineConstructorArgs(Type implementation)
   at Caliburn.Micro.SimpleContainer.<>c__DisplayClass7_0.<RegisterSingleton>b__0(SimpleContainer container)
   at Caliburn.Micro.SimpleContainer.GetInstance(Type service, String key)
   at MaxTo.UI.AppBootstrapper.GetInstance(Type serviceType, String key)
   at Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType, IDictionary`2 settings)
   at MaxTo.UI.AppBootstrapper.<OnStartup>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at MaxTo.UI.App.Main()
```

**Comment by Resourn** [comment] 2019-02-11 13:16
UAC is enabled and nothing else special as far as i am aware. I am using Panda Adaptive defense which blocks unauthorized applications but according to those logs nothing has been blocked.

**Comment by vegardlarsen** [comment] 2019-02-11 13:28
And this worked on this machine just before you enabled Bitlocker? (It will take me a while to get Bitlocker up and running on my test machine, as it had Windows 10 Home installed.)

**Comment by Resourn** [comment] 2019-02-11 13:34
it had some issues with starting all processes (only core + companion32 started) but that solved itself after i installed beta 8 or 9. Other than that it has worked fine on this machine.

**Comment by vegardlarsen** [comment] 2019-02-11 14:17
So I have tried this on Windows 10 1803 OS build 17134.112, and there does not appear to be a problem with Bitlocker on my VM at least. I am applying updates to try to get the VM up to date with the latest Windows updates, but my guess would have to be that this is not Bitlocker related.

**Comment by vegardlarsen** [comment] 2019-02-11 14:40
The update seems to be taking a while. Will check back in on this tomorrow.

**Comment by Resourn** [comment] 2019-02-11 14:43
I cant for sure say it is caused by bitlocker however it worked fine this friday when we installed bitlocker but not after it. Hopefully you can find something. All your help is appreciated.

**Comment by vegardlarsen** [comment] 2019-02-12 08:19
I have confirmed that this is not directly Bitlocker related. My VM is now running the exact same Windows version you reported, and does not experience this crash.

Does your machine have any group policies set that may interfere with checking registry values?

**Comment by Resourn** [comment] 2019-02-12 08:25
just checked our gpo's and can verify that no such policy exists in our domain. Are there any other logs or diagnostics that may be of interest?

**Comment by vegardlarsen** [comment] 2019-02-12 08:26
Do you have UAC rights on your machine? Meaning, can you elevate programs? With or without a password prompt?

**Comment by Resourn** [comment] 2019-02-12 08:27
I am a local admin and i do not need a password to elevate programs.

**Comment by vegardlarsen** [comment] 2019-02-12 08:31
Can you try going back to beta.9 and let me know if that works? [Download links](https://maxto.net/release/beta)

I have a suspicion what may have happened is that you were upgraded to beta 10, which has a known bug in detecting which version of Windows you are running. It is a long shot, but may explain it.

**Comment by Resourn** [comment] 2019-02-12 08:37
I uninstalled version 10 and tried to install beta 9. Get an error message saying installation failed and a link to the log file. It appears to be a user rights issue when attempting to reach my profile? I also noted that the folder referenced is beta10 and not beta9?

The only file present in that folder is the one mentioned in the error message "MaxTo.Hook.X64.dll".


2019-02-12 09:30:37> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\myname.domain\AppData\Local\MaxTo\app-2.0.0-beta10\MaxTo.Hook.x64.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\myname.domain\AppData\Local\MaxTo\app-2.0.0-beta10\MaxTo.Hook.x64.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

**Comment by vegardlarsen** [comment] 2019-02-12 08:54
OK, so this is a known issue that I don't have a solution for other than uninstall, delete the entire `%LocalAppData%\MaxTo` folder (it may require a reboot or sign out before Windows will let you), and then installing again.

**Comment by Resourn** [comment] 2019-02-12 09:16
I was able to install beta9 but the issue remains. Still no GUI. I did however get two folders when reinstalling. Both Beta 9 and 10. I tried to remove beta10 but it made no difference.

**Comment by vegardlarsen** [comment] 2019-02-12 10:57
I think I was able to figure out what causes this issue when I tried to reproduce it. I am readying a private build that you can test if you would like. Please e-mail me at the support-address and I'll get you the private build. (I don't want to publish these private builds as they can sometimes be harder to install and cause issues with versioning.

**Comment by Resourn** [comment] 2019-02-12 12:07
mail sent

**Comment by Resourn** [comment] 2019-02-14 06:52
I havent received the private build yet. I am not trying to rush you, just making sure i am not missing something or doing something wrong :-)

**Comment by vegardlarsen** [comment] 2019-02-14 08:18
Resending the e-mail now with a link instead of the actual attachment. :)

**Comment by Resourn** [comment] 2019-02-14 08:29
Okay i got the file and i can now see the gui! It appears to be working just fine. Alltough when i go to the startup tab in settings it says "UAC is either disabled or not supported on your machine. These settings have therefore been disabled."
![image](https://user-images.githubusercontent.com/47526596/52773331-f9481d00-303a-11e9-81db-9df2fe28232c.png)

This is not an issue for me as long as i am able to use the software normally though :-)

**Comment by vegardlarsen** [comment] 2019-02-14 08:30
Yes, something on your machine makes it so MaxTo cannot read if UAC is supported, and thus we have to fall back to "no, this won't work". :)

**Comment by vegardlarsen** [comment] 2019-02-14 08:32
Closing this as fixed. Will be in 2.0.0 final. :)

**Closed by vegardlarsen** 2019-02-14 08:32 UTC
Labels: bug
