### ISSUE TITLE
Trouble with recognizing 2 Eizo displays

### ISSUE THREAD

**Issue by lulu9** [digitalcreations/MaxTo#455] opened 2019-08-16 19:31 UTC
Hi.

I presently testing MaxTo. I like the program, but I have a problem. I have two nearly similar EIZO, 1 Eizo EV 2750 and one EV 2780. Both WQHD.

MaxTo has problems recognizing the displays. Serialnumber is not working. I always start with the same one monitor starting the pc. After some time I start the second screen. Nevertheless MaxTo is mixing them up quite often. So suddenly Display 1 is 2 and Display 2 changes to 1.

How can I fix that?

Thanks a lot.

Regards

**Comment by vegardlarsen** [comment] 2019-08-19 09:28
Thank you for getting in touch. Can you get me a copy of the monitor details so I can have a look? The details are "Monitor details" when you are changing your regions.

**Comment by lulu9** [comment] 2019-08-20 13:05
No prob. here the details:

Monitor one: Eizo EV2750

Anzeigename: Generic PnP Monitor
Gerätename: \\.\DISPLAY2
Standort: \{42C85DE4-94F0-11E9-AB83-D57510B55FBE}\0001
Seriennummern: 
DPI (Punkte pro Zoll): 96×96
Auflösung: 2560×1440 @ 0, 0
Arbeitsbereich: 2560×1400 @ 0, 0

Monitor two: Eizo EV2780

Anzeigename: Generic PnP Monitor
Gerätename: \\.\DISPLAY1
Standort: \{42C85DE4-94F0-11E9-AB83-D57510B55FBE}\0000
Seriennummern: 
DPI (Punkte pro Zoll): 96×96
Auflösung: 2560×1440 @ 2560, 0
Arbeitsbereich: 2560×1400 @ 2560, 0

Sometimes name is changing between these two, and also the place within registry.

Both are recognized as generic pnp monitor within maxto.

Regards

**Comment by vegardlarsen** [comment] 2019-08-21 11:03
Thank you for these details. I have checked and this issue will be fixed in version 2.1. If you want, you can e-mail me at the support address with a reference to this issue and get a private preview build where the issue is fixed.

I am closing this as it has been fixed.

**Closed by vegardlarsen** 2019-08-21 11:03 UTC
