### ISSUE TITLE
Error running MaxTo on Windows 10.0.18362

### ISSUE THREAD

**Issue by mrluisrodriguez** [digitalcreations/MaxTo#435] opened 2019-06-25 13:25 UTC
Getting error when trying to move windows on new Windows 10.0.18362 update. 

Error says: "C;\...\MaxTo.Hook.x86.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or software vendor for support. Error statys 0xc000012f."

Tried re-installing but did not work. I'm not running recipes or anything... just trying to snap a window into place.

![MaxToError](https://user-images.githubusercontent.com/36720354/60102149-21ebcc00-972b-11e9-88bd-4276d0200fe8.PNG)

**Comment by vegardlarsen** [comment] 2019-06-25 13:28
Duplicate of #415.

This issue can usually be solved by reinstalling the crashing application (in this case Spotify), or by resetting the application from the Windows settings. See issue #415 for details.

**Closed by vegardlarsen** 2019-06-25 13:28 UTC

**Comment by mrluisrodriguez** [comment] 2019-06-25 13:32
Yup. Just found https://github.com/digitalcreations/MaxTo/issues/415 and was going to close this one. 

Thanks for the quick response.
