### ISSUE TITLE
MaxTo RDP forgets about Windows taskbar

### ISSUE THREAD

**Issue by damien-ylopo** [digitalcreations/MaxTo#591] opened 2020-07-02 01:59 UTC
**Describe the bug**
Using MaxTo on an RDP session, closing the RDP session and then logging into it again causes MaxTo to not respect the Windows taskbar, and when maximizing a window MaxTo  maximizes the window to the entire height of the screen which causes the lower part of the window to appear underneath the Windows taskbar. Closing MaxTo and restarting it fixes this issue.

**To Reproduce**
1. Open RDP session to a remote computer with MaxTo running (split screen horizontally, so MaxTo is 2 or more virtual areas wide. 
2. Maximize a window and note it respects the Windows taskbar and won't maximize the window to the full height of the RDP session.
3. Close the RDP window (not logout, just close the RDP window by clicking the X on the RDP window)
4. Login to the same RDP session, maximize a window and note it will maximize the window to the full height of the RDP screen, not respecting the Windows taskbar, the bottom part of the maximized window will appear behind the Windows taskbar.

**Expected behavior**
When reopening an RDP session to a remote computer, MaxTo should always respect the Windows taskbar and not maximize windows so part of them appears behind the Windows taskbar. 

**Screenshots**

![image](https://user-images.githubusercontent.com/26334474/86308130-40519680-bbcd-11ea-989d-29445cd4e066.png)

**System information:**
- Windows version: Windows 10 Pro 1809 17763.973
- MaxTo version: V2.1.0-beta2, and v2017.07

**Additional context**

My config.json file:

[config.zip](https://github.com/digitalcreations/MaxTo/files/4861553/config.zip)

**Comment by vegardlarsen** [comment] 2020-07-02 08:02
Thank you for the detailed report, @damien-ylopo.

I have tried this now with Windows 10 version 1909 running in a VM, and cannot reproduce it at all.

I am also somewhat confused by your screenshot; you have a very tall taskbar, so I dragged mine out to roughly match that height. However, my programs align to the top of the taskbar, not the bottom:

![image](https://user-images.githubusercontent.com/436508/86332571-fdce9f00-bc4a-11ea-87d4-ec7f43428404.png)

Could this be a Windows version issue?

I also suspect that resizing the taskbar would immediately fix the issue. MaxTo relies on messages from Windows to know how large the working area is, and it could be that one of those messages goes missing when you reconnect.

**Comment by damien-ylopo** [comment] 2020-07-06 20:31
Thank you for looking into this. This was a problem I had for the longest
time, consistently, every day, but it seems to maybe be fixed after
updating to the latest stable version. I had not tested the latest stable
version long enough when I submitted the bug report. I had tested one of
the alpha releases but then did a full uninstall and reinstall of the
latest stable version of MaxTo, and the problem seems to be fixed now. I
will keep an eye on it though, this was my #1 biggest problem with MaxTo
for the longest time, but very happy otherwise.

**Comment by damien-ylopo** [comment] 2020-07-21 20:04
I'm definitely still seeing the behavior noted above in the current beta V2.1.0-beta2, but since switching to the release branch it's been working much better. I just hope the next release (v2.1?)won't re-introduce the same bugs. The beta also frequently seems to forget all of my settings and act as if MaxTo isn't even running quite often, which requires I restart MaxTo and close my RDP session and reopen the RDP session, which fixes things >for a while< but eventually it just stops working again, and I have to repeat the same actions to get the beta start working again. Frustrating. But, the release branch is working better thankfully.

**Comment by damien-ylopo** [comment] 2020-07-24 18:54
I've had another problem during my experimentation with v2.1.0 - I uninstalled v2.1.0-beta2, and reinstalled v2.0.1 hoping it would be more stable. I downloaded the latest v2.0.1 installer and installed it and thought everything was good. But no, for some reason it was still running v2.1.0-beta2. I uninstalled it again, downloaded the v2.0.1 installer again, and installed that - sure that I was installing v2.0.1. Again, it was still somehow running v2.1.0-beta2. I noticed this today after MaxTo yet again stopped working, which has been happening about 10x a day (using v2.1.0-beta2 without realizing it). 

So today I looked up "maxto" using the "Everything" search tool (www.voidtools.com)  and after uninstalling v2.1.0-beta2 yet again, I found every file named like "MaxTo" and deleted all of them after rebooting. Then, I rebooted again, downloaded v2.0.1 again, and installed that version again. This time it seems to have installed v2.0.1 as I had wanted it to the previous 2 times. 

So maybe something is weird about uninstalling one version and installing another version. I don't know, I just hope v2.0.1 solves my problems and won't crash 10x a day like v2.1.0-beta2 seems to do.

**Comment by vegardlarsen** [comment] 2020-08-04 11:36
@damien-ylopo It could be that you had set your update channel to "beta", and that it auto-updated. If you install a beta release, the release channel will be set to that automatically.

PS! Sorry about the slow response, I have been away on vacation.

**Comment by damien-ylopo** [comment] 2020-08-04 16:11
I don't think that was the problem, I had never known there was a beta update channel before you mentioned it here. 

I did initially install the beta so maybe it defaulted to the beta update channel, and then when I uninstalled the beta and installed the stable version, the stable version could have picked up the previous preferences, and then auto-installed the beta over it? 

In any case, I've been using the stable version for a couple of weeks now and it's been working great. I love the snapping feature too, my productivity has returned. :)

**Comment by vegardlarsen** [comment] 2020-08-05 07:08
Correct; your settings remain when you uninstall or upgrade, but the update channel could have changed. I am still unable to reproduce the issue as originally reported, and the fact that Windows seemingly places the open apps in different positions in my and your screenshot seem to be related.

But since the problem has not returned, I will be closing this issue. Feel free to comment if it returns.

**Closed by vegardlarsen** 2020-08-05 07:08 UTC
