### ISSUE TITLE
Brave Browser not-maxing-to-regions

### ISSUE THREAD

**Issue by nickallevato** [digitalcreations/MaxTo#485] opened 2019-10-31 20:46 UTC
**Describe the bug**
Brave doesn't seem to respect the regions! It used to!

**To Reproduce**
Use Brave.
Try to use MaxTo regions.

**Expected behavior**
use regions

**Screenshots**
not applicable

**System information:**
 - Windows 10
 - MaxTo version 2.0.1

**Additional context**
[maxto20191031.log](https://github.com/digitalcreations/MaxTo/files/3795761/maxto20191031.log)

**Comment by nickallevato** [comment] 2019-10-31 21:02
![25010011572555685](https://user-images.githubusercontent.com/6791120/67985854-61518a00-fbef-11e9-9eac-254a585cc975.png)
Here is some process information for a single tab not running anything. Fresh boot of Brave.

**Comment by vegardlarsen** [comment] 2019-10-31 21:29
This is a duplicate of #476. Please see that issue for a resolution. Closing this one.

**Closed by vegardlarsen** 2019-10-31 21:29 UTC
