### ISSUE TITLE
Resizing after snapping is broken

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#569] opened 2020-05-20 14:02 UTC
**Describe the bug**
When snapping a window to a region and trying to resize it, the behaviour is completely weird and it moves instead of resizes. See screen recording for more information. ~When a window is not snapped to a region ("moved freely"), everything works fine.~ Even "free" windows are affected by this bug after they have been snapped once. This bug applies to all windows I tested.

**To Reproduce**
1. Use MaxTo 2.1.0-beta1
1. Snap a window to a region
1. Resize

**Expected behavior**
Same behaviour as in MaxTo 2.0.1.

**Screenshots**
In this example, I have 2 regions (left/right) and snapped the cmd window to a region.

![maxto](https://user-images.githubusercontent.com/1430997/82455212-fbf1b780-9ab2-11ea-8c84-083fc5455c2f.gif)

**System information:**
- Windows version: Windows 10 Version 1909 18363.836
- MaxTo version: 2.1.0-beta1

**Additional context**
There are no entries regarding this in the log file.

**Comment by vegardlarsen** [comment] 2020-05-20 18:25
I believe this is a duplicate of #555, which has already been fixed for beta.2.

**Closed by vegardlarsen** 2020-05-20 18:25 UTC
Labels: duplicate

**Comment by thewavelength** [comment] 2020-05-20 19:13
Is there a planned release date? Seems like beta1 is pretty much unusable with this bug existing.

**Comment by vegardlarsen** [comment] 2020-05-20 19:14
I am working on publishing it now. So hopefully within the hour.
