### ISSUE TITLE
Windows Explorer crashes

### ISSUE THREAD

**Issue by paul-777** [digitalcreations/MaxTo#75] opened 2015-06-04 09:49 UTC
Windows explorer consistently crashes when using start\Run to start a web address e.g. www.google.co.uk. If I exit MaxTo the problem goes away. The default browser is IE, if I set the default browser to Chrome it is ok. If I run the self diagnostics in MaxTo is shows red X for the 32-bit system hook and keyboard shortcuts. I am running Win7 64bit. But IE hosts most of its activity in 32bit processes which may be a clue? Note - it is Windows Explorer that will "Stop Working" an restart not IE, running a web address just seems to be the trigger, it doesn't happen every time but maybe 1 in 7 if I repeat the same Win+R, OK sequence to run www.google.co.uk

**Comment by paul-777** [comment] 2015-06-04 09:53
Some of the log info

Faulting application name: explorer.exe, version: 6.1.7601.17567, time stamp: 0x4d672ee4
Faulting module name: ntdll.dll, version: 6.1.7601.18839, time stamp: 0x553e8bfa
Exception code: 0xc0000374
Fault offset: 0x00000000000bfc22
Faulting process id: 0x5efc
Faulting application start time: 0x01d09eab772c8d67
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: c18d4389-0a9e-11e5-ba56-00237d46e6d4

Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: explorer.exe
P2: 6.1.7601.17567
P3: 4d672ee4
P4: StackHash_f939
P5: 6.1.7601.18839
P6: 553e8bfa
P7: c0000374
P8: 00000000000bfc22
P9: 
P10: 

Attached files:
C:\Users\Paul\AppData\Local\Temp\WER12F1.tmp.WERInternalMetadata.xml

These files may be available here:
C:\Users\Paul\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_explorer.exe_b9c87c787368cc489f44f16d8e4b2f4f5e55aea_f6e5298c

Analysis symbol: 
Rechecking for solution: 0
Report Id: c18d4389-0a9e-11e5-ba56-00237d46e6d4
Report Status: 1


Contents of files in that folder
Version=1
EventType=APPCRASH
EventTime=130778848683829243
ReportType=2
Consent=1
UploadTime=130778848684765244
ReportIdentifier=c18d438a-0a9e-11e5-ba56-00237d46e6d4
IntegratorReportIdentifier=c18d4389-0a9e-11e5-ba56-00237d46e6d4
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=explorer.exe
Sig[1].Name=Application Version
Sig[1].Value=6.1.7601.17567
Sig[2].Name=Application Timestamp
Sig[2].Value=4d672ee4
Sig[3].Name=Fault Module Name
Sig[3].Value=StackHash_f939
Sig[4].Name=Fault Module Version
Sig[4].Value=6.1.7601.18839
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=553e8bfa
Sig[6].Name=Exception Code
Sig[6].Value=c0000374
Sig[7].Name=Exception Offset
Sig[7].Value=00000000000bfc22
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.1
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=2057
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=f939
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=f9399bc399d6d052b26ea256c153c76f
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=b3a4
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=b3a471efd46b0b5a26ee3a921cdfe1c7
UI[2]=C:\Windows\explorer.exe
UI[3]=Windows Explorer has stopped working
UI[4]=Windows can check online for a solution to the problem and try to restart the program.
UI[5]=Check online for a solution and restart the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Windows\explorer.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\kernel32.dll
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[5]=C:\Windows\system32\msvcrt.dll
LoadedModule[6]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[7]=C:\Windows\system32\RPCRT4.dll
LoadedModule[8]=C:\Windows\system32\GDI32.dll
LoadedModule[9]=C:\Windows\system32\USER32.dll
LoadedModule[10]=C:\Windows\system32\LPK.dll
LoadedModule[11]=C:\Windows\system32\USP10.dll
LoadedModule[12]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[13]=C:\Windows\system32\SHELL32.dll
LoadedModule[14]=C:\Windows\system32\ole32.dll
LoadedModule[15]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[16]=C:\Windows\system32\EXPLORERFRAME.dll
LoadedModule[17]=C:\Windows\system32\DUser.dll
LoadedModule[18]=C:\Windows\system32\DUI70.dll
LoadedModule[19]=C:\Windows\system32\IMM32.dll
LoadedModule[20]=C:\Windows\system32\MSCTF.dll
LoadedModule[21]=C:\Windows\system32\UxTheme.dll
LoadedModule[22]=C:\Windows\system32\POWRPROF.dll
LoadedModule[23]=C:\Windows\system32\SETUPAPI.dll
LoadedModule[24]=C:\Windows\system32\CFGMGR32.dll
LoadedModule[25]=C:\Windows\system32\DEVOBJ.dll
LoadedModule[26]=C:\Windows\system32\dwmapi.dll
LoadedModule[27]=C:\Windows\system32\slc.dll
LoadedModule[28]=C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.18834_none_2b26557a71eb7442\gdiplus.dll
LoadedModule[29]=C:\Windows\system32\Secur32.dll
LoadedModule[30]=C:\Windows\system32\SSPICLI.DLL
LoadedModule[31]=C:\Windows\system32\PROPSYS.dll
LoadedModule[32]=C:\Windows\system32\WINSTA.dll
LoadedModule[33]=C:\Program Files\MaxTo\MaxTo.Hook64.dll
LoadedModule[34]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18807_none_fa381d5f175bfb52\COMCTL32.dll
LoadedModule[35]=C:\Windows\system32\MSVCR120.dll
LoadedModule[36]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[37]=C:\Windows\system32\WindowsCodecs.dll
LoadedModule[38]=C:\Windows\system32\profapi.dll
LoadedModule[39]=C:\Windows\system32\apphelp.dll
LoadedModule[40]=C:\Windows\system32\CLBCatQ.DLL
LoadedModule[41]=C:\Program Files\Common Files\TortoiseOverlays\TortoiseOverlays.dll
LoadedModule[42]=C:\Program Files\TortoiseSVN\bin\TortoiseStub.dll
LoadedModule[43]=C:\Program Files\TortoiseSVN\bin\TortoiseSVN.dll
LoadedModule[44]=C:\Windows\system32\WININET.dll
LoadedModule[45]=C:\Windows\system32\api-ms-win-downlevel-user32-l1-1-0.dll
LoadedModule[46]=C:\Windows\system32\api-ms-win-downlevel-shlwapi-l1-1-0.dll
LoadedModule[47]=C:\Windows\system32\api-ms-win-downlevel-version-l1-1-0.dll
LoadedModule[48]=C:\Windows\system32\version.DLL
LoadedModule[49]=C:\Windows\system32\api-ms-win-downlevel-normaliz-l1-1-0.dll
LoadedModule[50]=C:\Windows\system32\normaliz.DLL
LoadedModule[51]=C:\Windows\system32\iertutil.dll
LoadedModule[52]=C:\Windows\system32\api-ms-win-downlevel-advapi32-l1-1-0.dll
LoadedModule[53]=C:\Windows\system32\USERENV.dll
LoadedModule[54]=C:\Program Files\TortoiseSVN\bin\libsvn_tsvn.dll
LoadedModule[55]=C:\Program Files\TortoiseSVN\bin\libapr_tsvn.dll
LoadedModule[56]=C:\Windows\system32\WS2_32.dll
LoadedModule[57]=C:\Windows\system32\NSI.dll
LoadedModule[58]=C:\Windows\system32\MSWSOCK.dll
LoadedModule[59]=C:\Windows\system32\MSVCR100.dll
LoadedModule[60]=C:\Program Files\TortoiseSVN\bin\libaprutil_tsvn.dll
LoadedModule[61]=C:\Windows\system32\WLDAP32.dll
LoadedModule[62]=C:\Program Files\TortoiseSVN\bin\intl3_tsvn.dll
LoadedModule[63]=C:\Program Files\TortoiseSVN\bin\libsasl.dll
LoadedModule[64]=C:\Windows\system32\CRYPT32.dll
LoadedModule[65]=C:\Windows\system32\MSASN1.dll
LoadedModule[66]=C:\Windows\system32\MSVCP100.dll
LoadedModule[67]=C:\Program Files\TortoiseGit\bin\TortoiseGitStub.dll
LoadedModule[68]=C:\Program Files\TortoiseGit\bin\TortoiseGit.dll
LoadedModule[69]=C:\Program Files\TortoiseGit\bin\libgit2_tgit.dll
LoadedModule[70]=C:\Program Files\TortoiseGit\bin\zlib1_tgit.dll
LoadedModule[71]=C:\Windows\system32\WINHTTP.dll
LoadedModule[72]=C:\Windows\system32\webio.dll
LoadedModule[73]=C:\Program Files\TortoiseGit\bin\gitdll.dll
LoadedModule[74]=C:\Windows\system32\MSVCP120.dll
LoadedModule[75]=C:\Windows\system32\CRYPTSP.dll
LoadedModule[76]=C:\Windows\system32\rsaenh.dll
LoadedModule[77]=C:\Program Files\TortoiseGit\bin\crshhndl.dll
LoadedModule[78]=C:\Program Files (x86)\Acronis\TrueImageHome\tishell64.dll
LoadedModule[79]=C:\Windows\system32\comdlg32.dll
LoadedModule[80]=C:\Windows\system32\MPR.dll
LoadedModule[81]=C:\Windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.6229_none_88dcc0bf2fb1b808\MSVCP80.dll
LoadedModule[82]=C:\Windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.6229_none_88dcc0bf2fb1b808\MSVCR80.dll
LoadedModule[83]=C:\Windows\system32\dbghelp.dll
LoadedModule[84]=C:\Windows\system32\IconCodecService.dll
LoadedModule[85]=C:\Windows\system32\EhStorShell.dll
LoadedModule[86]=C:\Windows\System32\cscui.dll
LoadedModule[87]=C:\Windows\System32\CSCDLL.dll
LoadedModule[88]=C:\Windows\system32\CSCAPI.dll
LoadedModule[89]=C:\Windows\system32\RpcRtRemote.dll
LoadedModule[90]=C:\Windows\system32\SndVolSSO.DLL
LoadedModule[91]=C:\Windows\system32\HID.DLL
LoadedModule[92]=C:\Windows\System32\MMDevApi.dll
LoadedModule[93]=C:\Windows\system32\timedate.cpl
LoadedModule[94]=C:\Windows\system32\ATL.DLL
LoadedModule[95]=C:\Windows\system32\actxprxy.dll
LoadedModule[96]=C:\Windows\system32\ntmarta.dll
LoadedModule[97]=C:\Windows\System32\shdocvw.dll
LoadedModule[98]=C:\Windows\system32\LINKINFO.dll
LoadedModule[99]=C:\Windows\system32\msiltcfg.dll
LoadedModule[100]=C:\Windows\system32\msi.dll
LoadedModule[101]=C:\Windows\System32\gameux.dll
LoadedModule[102]=C:\Windows\System32\XmlLite.dll
LoadedModule[103]=C:\Windows\System32\wer.dll
LoadedModule[104]=C:\Windows\System32\shacct.dll
LoadedModule[105]=C:\Windows\system32\SAMLIB.dll
LoadedModule[106]=C:\Windows\system32\samcli.dll
LoadedModule[107]=C:\Windows\system32\netutils.dll
LoadedModule[108]=C:\Windows\system32\MsftEdit.dll
LoadedModule[109]=C:\Windows\system32\msls31.dll
LoadedModule[110]=C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll
LoadedModule[111]=C:\Windows\system32\authui.dll
LoadedModule[112]=C:\Windows\system32\CRYPTUI.dll
LoadedModule[113]=C:\Windows\system32\thumbcache.dll
LoadedModule[114]=C:\Windows\system32\PSAPI.DLL
LoadedModule[115]=C:\Windows\system32\NetworkExplorer.dll
LoadedModule[116]=C:\Windows\System32\UIAnimation.dll
LoadedModule[117]=C:\Windows\system32\pfmapi_A1C.dll
LoadedModule[118]=C:\Windows\System32\drprov.dll
LoadedModule[119]=C:\Windows\System32\ntlanman.dll
LoadedModule[120]=C:\Windows\System32\davclnt.dll
LoadedModule[121]=C:\Windows\System32\DAVHLPR.dll
LoadedModule[122]=C:\Windows\system32\SXS.DLL
LoadedModule[123]=C:\Windows\system32\urlmon.dll
LoadedModule[124]=C:\Windows\system32\api-ms-win-downlevel-ole32-l1-1-0.dll
LoadedModule[125]=C:\Windows\system32\msutb.dll
LoadedModule[126]=C:\Windows\system32\api-ms-win-downlevel-shlwapi-l2-1-0.dll
LoadedModule[127]=C:\Program Files\Internet Explorer\ieproxy.dll
LoadedModule[128]=C:\Windows\system32\stobject.dll
LoadedModule[129]=C:\Windows\system32\BatMeter.dll
LoadedModule[130]=C:\Windows\system32\WTSAPI32.dll
LoadedModule[131]=C:\Windows\system32\es.dll
LoadedModule[132]=C:\Windows\system32\prnfldr.dll
LoadedModule[133]=C:\Windows\system32\WINSPOOL.DRV
LoadedModule[134]=C:\Windows\system32\AUDIOSES.DLL
LoadedModule[135]=C:\Windows\system32\dxp.dll
LoadedModule[136]=C:\Windows\system32\Syncreg.dll
LoadedModule[137]=C:\Windows\ehome\ehSSO.dll
LoadedModule[138]=C:\Windows\System32\netshell.dll
LoadedModule[139]=C:\Windows\System32\IPHLPAPI.DLL
LoadedModule[140]=C:\Windows\System32\WINNSI.DLL
LoadedModule[141]=C:\Windows\System32\nlaapi.dll
LoadedModule[142]=C:\Windows\System32\AltTab.dll
LoadedModule[143]=C:\Windows\system32\wpdshserviceobj.dll
LoadedModule[144]=C:\Windows\system32\PortableDeviceTypes.dll
LoadedModule[145]=C:\Windows\system32\PortableDeviceApi.dll
LoadedModule[146]=C:\Windows\system32\ntshrui.dll
LoadedModule[147]=C:\Windows\system32\srvcli.dll
LoadedModule[148]=C:\Windows\system32\WINTRUST.dll
LoadedModule[149]=C:\Windows\system32\mssprxy.dll
LoadedModule[150]=C:\Windows\system32\taskschd.dll
LoadedModule[151]=C:\Windows\System32\pnidui.dll
LoadedModule[152]=C:\Windows\System32\QUtil.dll
LoadedModule[153]=C:\Windows\System32\wevtapi.dll
LoadedModule[154]=C:\Windows\system32\dhcpcsvc.DLL
LoadedModule[155]=C:\Windows\system32\dhcpcsvc6.DLL
LoadedModule[156]=C:\Windows\system32\credssp.dll
LoadedModule[157]=C:\Windows\System32\npmproxy.dll
LoadedModule[158]=C:\Windows\System32\cscobj.dll
LoadedModule[159]=C:\Windows\System32\srchadmin.dll
LoadedModule[160]=C:\Windows\system32\Wlanapi.dll
LoadedModule[161]=C:\Windows\system32\wlanutil.dll
LoadedModule[162]=C:\Windows\system32\wwanapi.dll
LoadedModule[163]=C:\Windows\system32\wwapi.dll
LoadedModule[164]=C:\Windows\System32\QAgent.dll
LoadedModule[165]=C:\Windows\System32\bthprops.cpl
LoadedModule[166]=C:\Windows\System32\SyncCenter.dll
LoadedModule[167]=C:\Windows\System32\Actioncenter.dll
LoadedModule[168]=C:\Windows\system32\imapi2.dll
LoadedModule[169]=C:\Windows\System32\hgcpl.dll
LoadedModule[170]=C:\Windows\System32\provsvc.dll
LoadedModule[171]=C:\Windows\System32\netprofm.dll
LoadedModule[172]=C:\Windows\system32\wkscli.dll
LoadedModule[173]=C:\Windows\system32\fxsst.dll
LoadedModule[174]=C:\Windows\system32\FXSAPI.dll
LoadedModule[175]=C:\Windows\system32\FXSRESM.DLL
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Windows Explorer
AppPath=C:\Windows\explorer.exe

**Comment by paul-777** [comment] 2015-06-04 09:54
Seems to be happening more generally that just running internet links - also affect running local paths to open explorer windows e.g. Win+R, c:\temp, OK

**Comment by vegardlarsen** [comment] 2015-06-04 10:27
Thanks for the report. I am on my way out the door, but I will have a look at this as soon as I can.

**Comment by Gunni** [comment] 2015-06-26 13:00
Yes, happens to me aswell, does not seem to be bound to just using the run dialog, even just opening the run dialog and cancelling/exiting/escaping it makes explorer restart aswell.

**Comment by theor** [comment] 2015-06-27 23:00
Repro'd here too, the only thing keeping me from buying it.

**Comment by vegardlarsen** [comment] 2015-07-23 17:18
OK, so I have a fresh Windows 7 SP 1 VM ready. 

1. Install Maxto (2015.03.1). 
2. Win+R, "www.google.co.uk", Enter
3. Launches perfectly.
4. Reboot
5. Repeat 2, still works.

I don't know how else to reproduce this, so unless someone can send me a VM image where this happens, I am at a loss.

**Comment by paul-777** [comment] 2015-07-23 18:25
You need to repeat 2-3 several times - can I have seen it take up to 15 times before it crashes, other times it will go in 2 or 3

**Comment by vegardlarsen** [comment] 2015-07-23 19:01
@paul-777 Noted. I will try it again quite a few more times tomorrow when I am back on the machine where the VMs are running. From the comments above I understood it as if the problem happened every time.

**Comment by vegardlarsen** [comment] 2015-07-24 06:37
@paul-777 Good morning. I've tried this a good 40 times now (with launching various websites, iexplore directly, and so on), and still no crash. I'm now updating the Windows installation with all available updates (it was a fresh VM, it will take a while). It may be helpful to have a printout of your Task Manager's Processes tab to see if I can spot something suspicious that may help me reproduce this?

**Comment by paul-777** [comment] 2015-07-24 11:15
I have switched to an alternative product this issue was a deal breaker for me. But to give some clues

 

System runs fully patched Windows 7 x64 Ultimate

ATI R9 graphics connected to 4K display

Kapserksy 2015 (although I tried with protection paused as well)

Samsung SSD software

TrueImage

TrueCrypt

Logitech Setpoint

Renesas USB3 card

Realtek graphics

**Comment by vegardlarsen** [comment] 2015-07-27 12:12
@paul-777 Interesting. I know another customer with this problem has TrueCrypt installed as well. Do you have a encrypted system drive?

@Gunni @theor Do you have TrueCrypt installed as well?

**Comment by vegardlarsen** [comment] 2015-07-27 13:13
I have successfully reproduced this crash in a VM. The culprit seems to be TrueCrypt. Working on it.

**Comment by Gunni** [comment] 2015-07-27 13:15
I have TrueCrypt on all my computers, system encryption is not enabled.

**Comment by vegardlarsen** [comment] 2015-07-27 13:39
And after a reboot to install a debugger in that VM, the crash was no longer reproducible. I am confident TrueCrypt is the problem, and will work more on this tomorrow.

**Comment by paul-777** [comment] 2015-07-27 17:18
Not the system drive - I just have truecrypt containers for drives

**Comment by vegardlarsen** [comment] 2015-07-28 06:53
Again, this has proven worse to debug than I anticipated. While it crashed consistently, I tried to install a remote debugger on that machine, which required a reboot. After a reboot, it didn't crash anymore. Now I have a Autohotkey script running, which does these steps in a loop, so it opens IE to a website every 10 seconds, and then closes it again. I'll leave this running for a while to see (with a debugger attached to explorer).

**Comment by vegardlarsen** [comment] 2015-07-28 07:15
And I think I have it. When getting a window handle for the newly activated window, sometimes the received window handle is null. The process didn't anticipate this being the case, and attempted operations on that window handle (while running inside explorer's process), which caused explorer to crash. I'll leave my test setup running with the fix in place for a few more hours to be sure, but this seems to have fixed it.

**Comment by vegardlarsen** [comment] 2015-07-28 11:44
Besides that it seemed to work for a while, the problem came back after rigorous stress-testing. It happens very irregularly, and is therefore very hard to fix. The problem I fixed before could have been caused by a problem with the debugger (it was showing 0 as the value for more items that should have had a value).

I'll be working more with this bug to see if we can figure it out. However, I am afraid it won't be fixed for the Windows 10 release tomorrow.

**Comment by vrillco** [comment] 2015-10-31 12:33
I believe I'm having the same problem.  I'm not too sure what to give you for debugging info, so here goes nothing:

I am running MaxTo 2015.7.1.0 (trial version) on a Windows 7 x64, fully patched, freshly installed a week ago.  What seems to happen is when I use the Win+R shortcut and run a command, once in a while Explorer.exe will crash and restart.  I use Win+R quite a lot, probably once a minute while working, so the crash is also happening quite often, at least 2-3 times per hour.  It seems more likely to crash after a 5 minute break.

I am using the preset 2x3 layout on a 3840x2160 display.  Taskbar is at the bottom and there are usually 15 to 20 windows open (browsers, Explorer windows, notepad, putty etc).  I do not use TrueCrypt, UAC is disabled and my account is a local administrator of course.  This machine is not joined to any domain;

I have tried both active and passive mode, which did not seem to make a difference.  I've killed any non-essential background apps and services, which did not help either.  Even with an empty desktop, no windows open, just occasionally hitting Win+R and launching a command line or putty instance occasionally crashes Explorer.exe.  If I exit MaxTo, I have no more crashes, nor did I have any before installing MaxTo.

It's been a while since I did any Windows programming so I am a bit rusty, but if I can be of any assistance, please let me know.

**Comment by woodpile72** [comment] 2016-02-11 17:16
I'm having the same issue as vrillco - using Win-R causes crashes of explorer.  At any given time, I have 5-10 file explorer windows open and losing those because I used Win-R...  Bad.

It doesn't seem these issues are getting attention or being solved, so I'm not sure this is a good investment.  I'd be happy to pay, but between this and the odd resizing of windows after sleep, I can't do it.  I'd pay more if it all worked well, but it just doesn't.

**Comment by vegardlarsen** [comment] 2016-02-12 07:46
@woodpile72 I have had 3 separate attempts at fixing this issue, but so far I haven't been able to reproduce it on any of my machines, much less figure out why it is crashing. I have tried setting Windows 7 up in fresh virtual machines multiple times, and it just doesn't want to crash on the machines I try.

Please be assured that this is a high priority issue for me, but when I can't get it to crash myself, figuring it out is really difficult.

**Comment by tbrox** [comment] 2016-06-07 09:52
My trial just expired. Was really starting to like it, but I'm absolutely plagued by this problem, and will not put money into it while this problem is still here. Let me know if there is anything I can do to help you troubleshoot. I do use truecrypt, btw.

**Comment by vegardlarsen** [comment] 2016-06-07 10:57
@tbrox I'm afraid there is no progress, as I cannot figure out what is happening, nor reproduce it reliably on any machines I have access to. I am working on a large restructuring of MaxTo, and I hope that it may "fix itself" due to the way MaxTo will end up working then, but I really have no idea about what is causing this.

**Comment by fkesgin** [comment] 2017-03-30 11:25
I am having the same issue in here. I recently purchased the product and actually very happy but this random crash issue is very frustrating. Is there anything you can do about it?

**Comment by vegardlarsen** [comment] 2017-03-31 06:15
At the moment I don't know what is happening, and it is very hard to reproduce. If you can somehow manage to figure out what it is on your machine that makes it crash, that would make it a lot easier to figure out.

**Comment by fkesgin** [comment] 2017-03-31 14:39
I am attaching a output of crash dump of explorer.exe when MaxTo crashed explorer when I hit Win+R a few several times. Maybe it can give a clue.

[maxToExplorerCrashDumpOutput.TXT](https://github.com/digitalcreations/MaxTo/files/885977/maxToExplorerCrashDumpOutput.TXT)

**Comment by vegardlarsen** [comment] 2017-04-01 09:56
Hi, that crash dump actually gave me something of value. Can you try disabling window transparency in the options and see if the issue goes away? (I know of another bug that may not keep that setting in place between restarts of MaxTo)

**Comment by fkesgin** [comment] 2017-04-03 07:18
Actually transparency was already disabled when I get the first crash dump. I re-enabled it and disabled again to make sure it is properly set. This time when hit WIN+R and explorer.exe has stooped working,the fault has changed. I am attaching the new crash dump analysis. Hope this helps.

[maxToExplorerCrashDumpOutput_2.txt](https://github.com/digitalcreations/MaxTo/files/889204/maxToExplorerCrashDumpOutput_2.txt)

**Comment by vegardlarsen** [comment] 2017-04-04 19:57
This seems to be more typical of what I have seen of this crash before. MaxTo is nowhere to be found in that crash dump, but there is something that may indicate that this is a null reference somewhere; `NULL_CLASS_PTR_DEREFERENCE_c0000005_dui70.dll!Library::SimpleVector_unsigned_char_::resize`.

These crash dumps are useful; so if you can get any more, and you can see them changing, I am happy to look at them.

**Comment by fkesgin** [comment] 2017-08-10 15:08
Hi,

Another frustrating error for me and event log error is attached. If you are able to provide PDB files maybe I can use them to investigate the error. 
[maxToExplorerCrashDumpOutput_3txt.txt](https://github.com/digitalcreations/MaxTo/files/1215371/maxToExplorerCrashDumpOutput_3txt.txt)

**Comment by vegardlarsen** [comment] 2018-05-25 07:48
I have a nagging suspicion that this will be fixed in the 2.0.0-alpha.3 preview release (see #220 for details on how to try it out). We have severly limited which windows MaxTo will attempt to subclass, meaning that in the case of explorer there are a bunch of windows MaxTo now won't touch at all. This could very well prevent this crash.

I am closing this issue for now, but if you experience it with any of the 2.0.0 releases, please let me know.

**Closed by vegardlarsen** 2018-05-25 07:48 UTC
Labels: bug
