### ISSUE TITLE
Certain windows remain in semi-transparent state after drag and release.

### ISSUE THREAD

**Issue by jaystarkey** [digitalcreations/MaxTo#683] opened 2020-12-12 08:05 UTC
**Describe the bug**
Window drag and release causes certain applications, including Microsoft Outlook of Microsoft Office 365, to remain semi-transparent.

**To Reproduce**
Drag certain windows with left mouse click and drag, reliably Microsoft Office 365 Outlook but also happened with certain settings windows (not sure which ones), and release.  This will result in the window remaining 50% transparent, the same as during dragging.

**Expected behavior**
Expect window to return to 0% transparency after release.

**Screenshots**
![image](https://user-images.githubusercontent.com/1691371/101978826-bc381c00-3c0c-11eb-86d8-dc9466f93dff.png)

**System information:**
Windows Home 10 1909
MaxTo 2.1.5

**Additional context**
Started happening 2-3 weeks ago.  Just now realized it was MaxTo that was causing the issue.

**Comment by vegardlarsen** [comment] 2020-12-14 11:18
Thank you for reporting your issue. This is a duplicate of #676, and I am therefore closing this issue.

**Closed by vegardlarsen** 2020-12-14 11:18 UTC
Labels: duplicate
