### ISSUE TITLE
License revokes after each reboot.

### ISSUE THREAD

**Issue by desjani** [digitalcreations/MaxTo#495] opened 2019-11-11 15:16 UTC
After every reboot, upon login MaxTo errors with the following log:

```2019-11-11 08:13:53 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #12068)
2019-11-11 08:13:59 [Core@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\jatrits\AppData\Roaming\MaxTo"
2019-11-11 08:14:00 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #12068)
2019-11-11 08:14:00 [Core@2.0.1.499] [Information] Read shims from "C:\Users\jatrits\AppData\Local\MaxTo\shims.json"
2019-11-11 08:14:00 [Core@2.0.1.499] [Information] Squirrel-installed app, so rewriting CLI batch file.
2019-11-11 08:14:01 [Core@2.0.1.499] [Warning] Could not update application
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Squirrel.EasyModeMixin.<UpdateApp>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Update.UpdateService.<InitializeAsync>d__9.MoveNext()
2019-11-11 08:14:01 [Server@2.0.1.499] [Information] Logger setup (online logging: True, process #5948)
2019-11-11 08:14:01 [Core@2.0.1.499] [Information] Server up and running, client connected.
2019-11-11 08:14:02 [CompanionX64@2.0.1.499] [Information] Logger setup (online logging: True, process #6164)
2019-11-11 08:14:02 [Core@2.0.1.499] [Information] 4 processes started
2019-11-11 08:14:02 [CompanionX64@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\jatrits\AppData\Roaming\MaxTo"
2019-11-11 08:14:02 [CompanionX86@2.0.1.499] [Information] Logger setup (online logging: True, process #24024)
2019-11-11 08:14:02 [CompanionX64@2.0.1.499] [Information] Read shims from "C:\Users\jatrits\AppData\Local\MaxTo\shims.json"
2019-11-11 08:14:02 [CompanionX86@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\jatrits\AppData\Roaming\MaxTo"
2019-11-11 08:14:02 [CompanionX64@2.0.1.499] [Information] Enabled hook
2019-11-11 08:14:03 [CompanionX86@2.0.1.499] [Information] Read shims from "C:\Users\jatrits\AppData\Local\MaxTo\shims.json"
2019-11-11 08:14:03 [CompanionX86@2.0.1.499] [Information] Enabled hook
2019-11-11 08:14:03 [UserInterface@2.0.1.499] [Information] Logger setup (online logging: True, process #11544)
2019-11-11 08:14:03 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.ViewModels.NotificationIconViewModel"
2019-11-11 08:14:04 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.GettingStarted.Welcome.WelcomeViewModel"
2019-11-11 08:14:04 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.GettingStarted.WizardViewModel"```

and the license key has to be re-entered.

**Comment by vegardlarsen** [comment] 2019-11-12 14:52
Are you behind a proxy server or similar setup?

We did actually discover a bug in the licensing system today that could lead to the license key getting removed because of any unknown error during a specific phase of checking the license, which in some cases could include dropped HTTP connections.

I am assigning this to 2.1.0-alpha.2, which will probably fix your issue when it is released.

**Comment by desjani** [comment] 2019-11-12 15:00
I am behind an Ironport system too. Can I get a list of http address it
phones to and see if it's getting filtered out?

**Comment by vegardlarsen** [comment] 2019-11-13 12:21
@desjani It connects to https://maxto.net, so whitelisting that domain should help.

**Comment by vegardlarsen** [comment] 2019-11-13 14:56
I have implemented a fix for this, and hopefully this should work better in version 2.1.0-alpha.2.

**Closed** 2019-11-13 14:57 UTC

**Comment by nizmow** [comment] 2019-11-14 11:44
I've installed 2.1.0-alpha.2 and I get the same behaviour (also a regression with rendering the initial setup screen, no text AA or acceleration, but that's presumably another issue!). Additional information:

* When I restart the application and go through the setup wizard, then open the settings and view my license information, it's blank (even though I've just entered my key!). Adding license information in the settings doesn't help, I still get the onboarding when I restart.
* Possibly something unique to my system which I thought I should mention: I have previously tried MaxTo on a trial but didn't purchase. I'm not sure which version I tried, but the trial expired April 5th, 2019. It tells me this every time I start up. Perhaps that's a clue?

Thanks for looking into it, I appreciate it!

**Comment by vegardlarsen** [comment] 2019-11-14 11:49
@nizmow Can you try pasting your license key into Notepad, and saving it as `%AppData%\MaxTo\license.txt`? Does that solve the issue, or is it still present?

**Comment by nizmow** [comment] 2019-11-14 13:05
@vegardlarsen that has indeed solved the issue!

Another thing occurred to me: perhaps something strange is happening due to roaming profiles? Perhaps permissions? I believe my whole `%AppData%` folder is on the network.

**Comment by vegardlarsen** [comment] 2019-11-18 08:19
@nizmow I am not really sure what causes this issue. It seems that MaxTo is unable to write the license file to disk, or that the file is deleted somehow. 2.0.0-alpha.2 fixed a bug where due to internet connectivity issues, the file could be erroneously deleted, but if the file now stays in place I know that isn't the issue.
