### ISSUE TITLE
Assinging a Move Window Command to a Numbered Vitual Desktop does not work.

### ISSUE THREAD

**Issue by ccsRoo** [digitalcreations/MaxTo#675] opened 2020-11-29 08:24 UTC
Greetigns,

After updating to 2.1.4 my Move Window commands that reference Virtual Desktops no longer work and they return the error "Virtual desktops are only supported on Windows 10." 

My machine is running Windows 10 Pro 20H2.

The commands work fine if I set them to "Use Default (current virtual desktop)", but setting to any of the other vitrual desktop  options returns the same error.

I coppied the commands and ran them in the command line and it gives the same result.

Regards.

![image](https://user-images.githubusercontent.com/75196889/100536950-950d4200-323d-11eb-8ce3-cd6340191d89.png)

**Comment by vegardlarsen** [comment] 2020-11-30 09:34
Hi @ccsRoo, thank you for creating your issue. This has the same root cause as issue #669, so I am closing your issue as a duplicate of that.

**Closed by vegardlarsen** 2020-11-30 09:34 UTC
