### ISSUE TITLE
MaxTo doesn't work as expected with RDP sessions.

### ISSUE THREAD

**Issue by mmiller678** [digitalcreations/MaxTo#445] opened 2019-07-18 14:02 UTC
MaxTo doesn't work with RDP sessions.  It seems to have an issue with identifying monitors.  The older version worked fine.

**To Reproduce**
1. Start and RDP session to your workstation (be sure under Display choose Use all my monitors for remote session)
2. Notice your MaxTo settings are completely gone (unlike the older version)
3. Setup two screens (i.e. monitors) and click use regions.  
4. Notice regions don't work.  Open up settings - see regions are missing

**Expected behavior**
In the old version the settings stayed in place whether you were logged in locally or via RDP

**System information:**
 - Windows version: 10
 - MaxTo version: 2.0.1. 

**Hardware**
My local and remote setups are the same in terms of monitors and sizes and resolutions.

**Comment by vegardlarsen** [comment] 2019-07-22 20:30
Thank you for the feedback. This issue will be fixed in version 2.1; it was caused by MaxTo being unable to read a configuration file from disk because of consecutive `\` characters in the file path. Windows will gladly normalize and accept a file path with consecutive `\` characters in the path. However, the consecutive backslashes are removed when MaxTo queries for the files it wrote; and therefore MaxTo cannot "find" the file.

This issue has already been corrected in the source, and I am therefore closing this for version 2.1.0. The issue is likely related to another issue I have already closed for that milestone, but I couldn't find it after a quick search.

**Closed by vegardlarsen** 2019-07-22 20:30 UTC
Labels: bug
