### ISSUE TITLE
Microsoft PowerToys is crashing with MaxTo running

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#577] opened 2020-05-22 12:53 UTC
**Describe the bug**
[Microsoft PowerToys](https://github.com/microsoft/PowerToys) is crashing with MaxTo running.

**To Reproduce**
1. Have MaxTo 2.1.0-beta2 running
1. Start PowerToys
1. Try to change any setting within PowerToys window

**Expected behavior**
No crash.

**System information:**
- Windows version: Windows 10 1909 18363.836
- MaxTo version: 2.1.0-beta2

**Additional context**
No entries in log file of MaxTo.

**Comment by vegardlarsen** [comment] 2020-06-18 08:38
Another customer has reported via e-mail that if MaxTo and PowerToys are both set to start with Windows, PowerToys will reveal MaxTo's hidden "message-only" windows on start-up.

**Comment by vegardlarsen** [comment] 2020-08-07 06:44
I've added a compatibility shim for PowerToys, that should help with the crashing issue. You'll need to go into Settings, Compatibility and hit the Update button for MaxTo to update its compatibility shims.

It may take some time before the shim becomes available in the app (due to caching). [Direct link](https://maxto.net/shim/powertoys).

**Comment by vegardlarsen** [comment] 2020-08-07 06:46
I have been unable to reproduce the hidden windows showing, however. I am therefore closing this issue.

**Closed by vegardlarsen** 2020-08-07 06:46 UTC
Labels: compatibility
