### ISSUE TITLE
Continous Resize with application windows

### ISSUE THREAD

**Issue by Palgar** [digitalcreations/MaxTo#492] opened 2019-11-09 06:57 UTC
Application windows will not remain at the region size of the current monitor over RDP, but revert to their region size of the physical monitor. 
    Physical machine: dual 2560x1440 monitors.
    RDP Connection: single 4k monitor
    Both monitors use same region template of just a single vertical break giving a left-right sides of monitors.  Same template used for the RDP session. 

Reproduce:
Connect over RDP to physical machine.  Start any two apps.  Place app 1 in region 1 and maximize, place app 2 in region 2 and maximize.  Click back on app1.  App1 resizes to the maximum height of the physical monitor, not the RDP monitor.  Maximum App1, it goes to proper (4k height) until you change apps and switch back.   The monitor setting of Number, Properties or Settings.

**Expected behavior**
The regions should work as full size regardless of the screen sizes underneath.

**System information:**
 - Windows version: 10 insider edition 19018
 - MaxTo version :2.1.0-alpha1

**Comment by vegardlarsen** [comment] 2019-11-11 13:47
@Palgar I think this is just an issue with 2.1.0-alpha.1. Please try downgrading to 2.0.1 to see if the issues disappear. See issue #487, as I think this is a duplicate of that issue. Feel free to comment here if the issues still appear after dowgrading.

**Closed by vegardlarsen** 2019-11-11 13:47 UTC
