### ISSUE TITLE
F11 "Full screen" not snapping to virtual screen

### ISSUE THREAD

**Issue by electricfriends** [digitalcreations/MaxTo#232] opened 2018-06-25 08:42 UTC
**Problem**
When using full screen mode (F11) in browsers (Chrome, Firefox), the browser window spans across the whole physical screen.

**Expected**
Expected the full screen to display within the bounds of the new virtual region.

**Benefits**
Possibility to display web pages or web apps in regions without browser tabs, address bar, and windows title bar.

**Comment by vegardlarsen** [comment] 2018-06-25 08:53
Intercepting full-screen apps (such as video players and such) have not been a design goal for MaxTo, and technically it seems to be quite a bit more difficult to do. The reason for that is that full-screen windows are basically just windows that remove their borders and place themselves to cover the entire monitor; there is no "full-screen window" concept in Windows (maybe excluding full-screen games, which I am not familiar enough with to state explicitly will work).

We can probably intercept certain windows going full-screen through subclassing, but it is not a fool-proof way to do this.

**Comment by vegardlarsen** [comment] 2018-10-05 08:44
I am closing this as by design.

**Closed by vegardlarsen** 2018-10-05 08:44 UTC
