### ISSUE TITLE
Trying to snap behind toolbar docked on the right hand side of the screen

### ISSUE THREAD

**Issue by gnychis** [digitalcreations/MaxTo#152] opened 2016-10-05 19:36 UTC
I am trialing the Pro version of MaxTo.

In Windows, my taskbar/toolbar is docked to the right hand side of my screen.  After my computer boots up cleanly (MaxTo set to start on boot), MaxTo draws my grid behind the taskbar.  This means if I snap to things, they snap behind the taskbar:

![image](https://cloud.githubusercontent.com/assets/1406044/19128455/69c010d2-8b11-11e6-9edf-f671826af3ed.png)

If I kill MaxTo and start it again, it will properly not overlay under my taskbar.

I am on Windows 10 Pro, version 10.0.10586 Build 10586

**Comment by vegardlarsen** [comment] 2016-10-06 13:47
This is unfortunate, and probably a bug. Can you try unlocking the taskbar, and dragging it to a different location before dragging it back? Does MaxTo adjust its regions correctly then?

**Comment by gnychis** [comment] 2016-10-12 15:35
Hi there, I tried moving the task bar and moving it back and MaxTo does not adjust its regions, the windows are still stuck behind the taskbar.

**Comment by atollis** [comment] 2018-05-08 00:00
I have a similar issue, my taskbar is docked on top.
I have not identified the cause/trigger but eventually maxTo starts maximizing behind the taskbar.
After Windows starts and after a maxTo restart it behaves correctly.

**Comment by vegardlarsen** [comment] 2018-05-08 07:00
I have an idea as to what causes this; and it has been the cause of many different bugs in MaxTo. The problem appears to be a caching bug in `System.Windows.Forms.Screen`, which causes it to remember intermediate states (e.g. the size of the work area before the taskbar appears) even though the actual state has changed.

We are working around this by completely avoiding that way of getting the screen dimensions in the next release of MaxTo.

**Comment by atollis** [comment] 2018-05-13 23:27
what sort of time frame are we looking at for the next release? is it closer to a month or 6 months?

**Comment by vegardlarsen** [comment] 2018-05-14 12:57
Closer to a month. :)

Pop me an e-mail on the support address.

**Comment by vegardlarsen** [comment] 2018-05-24 12:54
This issue should be fixed in the preview release (2.0.0-alpha.2). See #220.

**Closed by vegardlarsen** 2018-05-24 12:54 UTC
