### ISSUE TITLE
"HotkeyAlreadyRegisteredException" leads to MaxTo crash... 

### ISSUE THREAD

**Issue by gnychis** [digitalcreations/MaxTo#280] opened 2018-11-14 15:40 UTC
I went to go modify the "Move window left" recipe to Alt+a.  It didn't throw me an error.  So I went to modify "Move window right" to Alt+d and then MaxTo crashed.  I looked at the logs, and the root cause might be that the hotkey was already registered... but an exception wasn't thrown, and the next hotkey I tried it just crashed.

```
2018-11-14 10:29:55 [MaxTo.Core@2.0.0.331] [Information] Logger setup (online logging: True, process #11448)
2018-11-14 10:29:55 [MaxTo.Core@2.0.0.331] [Fatal] Unhandled exception "HotkeyAlreadyRegisteredException" at "   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
MaxTo.Core.Keyboard.HotkeyAlreadyRegisteredException: Hotkey combination already registered: Windows+NumPad2
   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2018-11-14 10:29:55 [MaxTo.Core@2.0.0.331] [Information] Logger setup (online logging: True, process #11448)
2018-11-14 10:29:55 [MaxTo.Core@2.0.0.331] [Fatal] Unhandled exception "HotkeyAlreadyRegisteredException" at "   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
MaxTo.Core.Keyboard.HotkeyAlreadyRegisteredException: Hotkey combination already registered: Windows+NumPad2
   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2018-11-14 10:29:55 [MaxTo.Core@2.0.0.331] [Fatal] Unhandled exception "HotkeyAlreadyRegisteredException" at "   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
MaxTo.Core.Keyboard.HotkeyAlreadyRegisteredException: Hotkey combination already registered: Windows+NumPad2
   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2018-11-14 10:29:55 [MaxTo.Core@2.0.0.331] [Fatal] Unhandled exception "HotkeyAlreadyRegisteredException" at "   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
MaxTo.Core.Keyboard.HotkeyAlreadyRegisteredException: Hotkey combination already registered: Windows+NumPad2
   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2018-11-14 10:29:55 [MaxTo.Core@2.0.0.331] [Fatal] Unhandled exception "HotkeyAlreadyRegisteredException" at "   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
MaxTo.Core.Keyboard.HotkeyAlreadyRegisteredException: Hotkey combination already registered: Windows+NumPad2
   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2018-11-14 10:29:55 [MaxTo.Core@2.0.0.331] [Fatal] Unhandled exception "HotkeyAlreadyRegisteredException" at "   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
MaxTo.Core.Keyboard.HotkeyAlreadyRegisteredException: Hotkey combination already registered: Windows+NumPad2
   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2018-11-14 10:29:55 [MaxTo.Core@2.0.0.331] [Fatal] Unhandled exception "HotkeyAlreadyRegisteredException" at "   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
MaxTo.Core.Keyboard.HotkeyAlreadyRegisteredException: Hotkey combination already registered: Windows+NumPad2
   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass0_0`1.<Subscribe>b__0(Object sender, Message message)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at MaxTo.Core.Communication.NamedPipeClient.WorkerOnProgress(Object sender, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2018-11-14 10:29:59 [MaxTo.UI@2.0.0.331] [Information] Activated "MaxTo.UI.Components.Settings.Recipes.Index.IndexViewModel"
2018-11-14 10:30:02 [MaxTo.UI@2.0.0.331] [Information] Deactivated "MaxTo.UI.Components.Settings.Language.LanguageViewModel". Closed: True
2018-11-14 10:30:02 [MaxTo.UI@2.0.0.331] [Information] Deactivated "MaxTo.UI.Components.Settings.Recipes.Index.IndexViewModel". Closed: True
2018-11-14 10:30:02 [MaxTo.UI@2.0.0.331] [Information] Deactivated "MaxTo.UI.Components.Settings.Recipes.RecipesViewModel". Closed: True
2018-11-14 10:30:02 [MaxTo.UI@2.0.0.331] [Information] Deactivated "MaxTo.UI.Components.Settings.SettingsViewModel". Closed: True
2018-11-14 10:30:06 [MaxTo.UI@2.0.0.331] [Information] Activated "MaxTo.UI.Components.Settings.Recipes.Index.IndexViewModel"
2018-11-14 10:30:06 [MaxTo.UI@2.0.0.331] [Information] Activated "MaxTo.UI.Components.Settings.Recipes.RecipesViewModel"
2018-11-14 10:30:06 [MaxTo.UI@2.0.0.331] [Information] Activated "MaxTo.UI.Components.Settings.SettingsViewModel"
2018-11-14 10:30:06 [MaxTo.UI@2.0.0.331] [Information] Deactivated "MaxTo.UI.Components.Settings.Recipes.Index.IndexViewModel". Closed: False
2018-11-14 10:30:06 [MaxTo.UI@2.0.0.331] [Information] Deactivated "MaxTo.UI.Components.Settings.Recipes.RecipesViewModel". Closed: False
2018-11-14 10:30:06 [MaxTo.UI@2.0.0.331] [Information] Activated "MaxTo.UI.Components.Settings.Language.LanguageViewModel"
2018-11-14 10:30:11 [MaxTo.UI@2.0.0.331] [Information] Deactivated "MaxTo.UI.Components.Settings.Language.LanguageViewModel". Closed: False
2018-11-14 10:30:11 [MaxTo.UI@2.0.0.331] [Information] Activated "MaxTo.UI.Components.Settings.Recipes.Index.IndexViewModel"
2018-11-14 10:30:11 [MaxTo.UI@2.0.0.331] [Information] Activated "MaxTo.UI.Components.Settings.Recipes.RecipesViewModel"
2018-11-14 10:30:13 [MaxTo.UI@2.0.0.331] [Information] Deactivated "MaxTo.UI.Components.Settings.Recipes.Index.IndexViewModel". Closed: False
2018-11-14 10:30:14 [MaxTo.UI@2.0.0.331] [Fatal] Unhandled exception "IOException" at "   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at MaxTo.Core.Communication.NamedPipeClient.<Send>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.NamedPipeMessageBusAdapter.<Publish>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MaxTo.UI.App.Main()"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at MaxTo.Core.Communication.NamedPipeClient.<Send>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.NamedPipeMessageBusAdapter.<Publish>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MaxTo.UI.App.Main()
```

**Comment by vegardlarsen** [comment] 2018-11-15 10:05
Thank you for the report. I will investigate the cause of this, I am not entirely sure what causes it. I probably won't have time until after beta.3 to look at it, however.

**Comment by bojordan** [comment] 2018-11-15 21:29
I see the same behavior. Pretty sure this worked correctly before I configured MaxTo to run with elevation, though I can't say 100%.

**Comment by vegardlarsen** [comment] 2018-12-07 09:54
This issue was fixed in beta.4, which is out now.

**Closed by vegardlarsen** 2018-12-07 09:54 UTC
Labels: bug
