### ISSUE TITLE
Adobe Acrobat Issue

### ISSUE THREAD

**Issue by seelenfrieden** [digitalcreations/MaxTo#31] opened 2015-01-05 19:43 UTC
If i open Adobe Acrobat this screen appears:

Adobe Acrobat Pro has issues that makes it impossible for maxto to work properly.

therefore maxto has disabled these dfeatures for ... : 
Snap to edge
drag and maximize

**Comment by vegardlarsen** [comment] 2015-01-06 08:07
@seelenfrieden Unfortunately there does not appear to be anything we can do about this. Acrobat Reader has been put on a compatibility list to prevent MaxTo from doing certain things that either crash Acrobat Reader or makes it unusable in some form. I suspect Acrobat Reader disallows the actions MaxTo needs to prevent people from copying content from DRM-protected PDFs, but I am unsure. All I know for sure is that MaxTo cannot work with Acrobat Reader.

**Comment by llinfeng** [comment] 2015-02-08 19:42
Hi Vegard,

Not sure if the following content should be helpful to overcome the Adobe issue.

[[Excerpt from URL: http://www.nurgo-software.com/support/aquasnap-faq]]

This is a known issue which is caused by Adobe Reader itself. For security reasons, the recent versions of Adobe Reader use a sandbox that isolate Adobe Reader from other applications like AquaSnap. The solution to this problem is to disable this sandbox.

To do this on Adobe Reader X:

    Open Adobe Reader.
    Choose Edit > Preferences.
    In the Categories list on the left, select General.
    Disable Enable Protected Mode at startup.
    Restart Adobe Reader.

To do this on Adobe Reader XI:

    Open Adobe Reader.
    Choose Edit > Preferences.
    In the Categories list on the left, select Security (Enhanced).
    Disable Enable Protected Mode at startup.
    Restart Adobe Reader.

You can find out more about the protected mode of Adobe Reader on this page.

**Comment by vegardlarsen** [comment] 2015-02-08 20:40
I have tested this now, and it seems you are right. I did not know about this setting until now, and it seems it should probably not have been left on by default by Adobe.

However, most people who have Adobe Reader will not have this setting turned off, so MaxTo's default attitude of "I won't touch this" will still stand. To make MaxTo Adobe Reader work well together, you will need to follow the steps above, and then remove the two entries from the `shims.xml` file in the MaxTo folder: `<windowclass>AcrobatSDIWindow</windowclass>`.

I will probably have to add this to a FAQ on the website. Could be fun, with only one Frequently Asked Question. :)

Thanks for letting me know.

**Comment by seelenfrieden** [comment] 2015-02-09 10:20
which two entries do you mean? This:

 

    <process>ManicTime</process>

    <process>ManicTimeClient</process>

 

 

 

Von: Vegard Andreas Larsen [mailto:notifications@github.com] 
Gesendet: Sonntag, 8. Februar 2015 21:41
An: digitalcreations/MaxTo
Cc: seelenfrieden
Betreff: Re: [MaxTo] Adobe Acrobat Issue (#31)

 

I have tested this now, and it seems you are right. I did not know about this setting until now, and it seems it should probably not have been left on by default by Adobe.

However, most people who have Adobe Reader will not have this setting turned off, so MaxTo's default attitude of "I won't touch this" will still stand. To make MaxTo Adobe Reader work well together, you will need to follow the steps above, and then remove the two entries from the shims.xml file in the MaxTo folder: <windowclass>AcrobatSDIWindow</windowclass>.

I will probably have to add this to a FAQ on the website. Could be fun, with only one Frequently Asked Question. :)

Thanks for letting me know.

**Comment by vegardlarsen** [comment] 2015-02-09 10:22
@seelenfrieden None of those. You need to look for `AcrobatSDIWindow`. There should be two of those entries. Then you need to make the preference changes outlined above.

**Comment by llinfeng** [comment] 2015-02-09 13:24
@seelenfrieden The two entries/lines to be removed are on line `20` and `37` on my machine.

**Comment by 57thkafka** [comment] 2015-04-05 12:31
@llinfeng Thanks very much for this, it works perfectly. Now I can have my 4-vertical split including Acrobat Pro.
@vegardlarsen I was referring to Acrobat Pro, not Acrobat Reader, and the Pro version does not have that security setting enabled by default, so once I edited shims.xml, maxto worked fine with Acrobat Pro. Is there any way you can distinguish between the Reader and Pro versions in your compatibility list?

**Comment by vegardlarsen** [comment] 2015-04-06 08:43
@57thkafka Yes, instead of targetting the window class, you could instead use `<process>AcroRd32</process>`  for Adobe Reader, and the equivalent process name for Acrobat Pro (the process name is the name of the executable without the `.exe` extension, you can find it in the Details tab of Task Manager when it is running).

**Comment by dhilgarth** [comment] 2015-12-02 12:25
I think targeting the AcroRd32 process instead of the AcrobatSDIWindow window class should be the default setting on new installations and upgrades.

**Comment by vegardlarsen** [comment] 2015-12-02 12:26
Maybe, but this also affects Adobe Acrobat, so it is not that clear-cut. Maybe I should split this out into two different shims.

**Comment by dhilgarth** [comment] 2015-12-02 12:29
The point is: By default, the sandbox is enabled in the reader and disabled in Pro. So, in my opinion, the "it just works" path for the majority of clients would be to have a shim for Acrobat Reader but not for Acrobat Pro.

**Comment by vegardlarsen** [comment] 2015-12-02 12:37
You are right. I was unaware that the sandbox was disabled in Pro. I'll have this fixed in the next release.

**Comment by dhilgarth** [comment] 2015-12-02 12:38
Great, thanks!

**Comment by davidermined** [comment] 2018-02-25 14:02
@vegardlarsen 
What do you mean exactly when you say 'remove the entry'?
Do you mean that every line, that contains the 'AcrobatSDI...'-String needs to be removed or other lines below it as well? Also in order to find 'shims.xml' in the first place, I had to google where it is, leading me to another 'issue' where it's location was specified to be at 'Program Files (x86)' (I finally found it at 'Program Files', though). That might be obvious for you, but it's not obvious, that it wouldn't be in %appdata%, %roaming% or God knows where else developers hide their config files on Windows.

Also, the option to untick 'enable protected mode at startup' is no longer there in the current version of Adobe Reader. (And I never changed anything there, that wouldn't be default)

Could please finally write the FAQ already and properly document this?
Whenever I reinstall Windows, I'm tired of trying to remember how to make this work, concluding, that I've forgotten it after all, googling it, stumbling on this 'issue' again, trying to follow a discussion, I'm not really at all interested in, finding an obscure Adobe Reader setting, googling for another isssue to figure out where the file is, figure out again how to get Admin privileges for editing a config file, cursing myself, because I edited the file, before closing MaxTo (which is in the wrong order) and then despairing, because it still doesn't work, after a reboot, although the 'shims.xml'-file has been changed. The Windows experience is not supposed to include 'config file'-edits, that's what Linux is for.

**Comment by vegardlarsen** [comment] 2018-02-26 07:17
Hi @davidermined. This feature wasn't really designed as a "user setting" kind of feature, but more of a "here is a list of programs that MaxTo knows how to work around issues in". Therefore it is placed in MaxTo's installation directory instead of %LocalAppData%, where MaxTo stores most of its settings.

We do have an [entry that explains this](https://maxto.net/shim/Details/acrobat_reader), but it is too hard to find. 

We are also changing how this works in a future release of MaxTo, which will let you enable/disable the Adobe Reader shim directly from MaxTo itself.

The setting in Adobe Reader is here (top left): 

![image](https://user-images.githubusercontent.com/436508/36657568-6929a08c-1acd-11e8-9fdd-2697f9f31be8.png)

**Comment by davidermined** [comment] 2018-02-27 12:54
Thank you. I missed, that there were two different instructions. My program says 'Adobe Acrobat Reader DC', so that's presumably equivalent to XI. It works again, now.

**Comment by vegardlarsen** [comment] 2018-05-23 12:48
This is now [documented here](https://maxto.net/shim/Details/acrobat_reader), and therefore I am closing this issue.

**Closed by vegardlarsen** 2018-05-23 12:48 UTC
Labels: wontfix
