### ISSUE TITLE
Application paths are treated as arguments

### ISSUE THREAD

**Issue by heystenner** [digitalcreations/MaxTo#357] opened 2019-03-09 16:02 UTC
**Describe the bug**
When I launch an application with a recipe, the path I specified in recipies gets passed on to the application as an argument. I can see this especially in browsers, where the application path appears in the address bar.

**To Reproduce**
- I specify an application path in a recipe, like C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
![grafik](https://user-images.githubusercontent.com/47742121/54073769-49f21500-428b-11e9-8faa-f09391fa2596.png)
- I run the recipe with the specified shortcut (CTRL+ALT+M in my case, no other shortcuts for that on my system afik).
- The app window opens.
- There are two tab windows open: files/ and %28x86%29/Google/Chrome/Application/chrome.exe
![grafik](https://user-images.githubusercontent.com/47742121/54073796-90e00a80-428b-11e9-8962-e413c6b4ff00.png)
- If I specify an argument, like http://trello.com - it will open the two tabs above mentioned + the domain I specified.
- Same thing happens with other apps:
![grafik](https://user-images.githubusercontent.com/47742121/54073835-fcc27300-428b-11e9-837d-6c013c4ec2f8.png)

**Expected behavior**
The application was supposed to open, nothing else.

**System information:**
 - Windows 10 Version 1803 build  17134.590
 - MaxTo version 2.0.0-rc2

**Additional context**

Log file:
`2019-03-09 16:59:36 [Core@2.0.0.470] [Information] Executing recipe '"Grafikdesign"' with 1 ingredients
2019-03-09 16:59:36 [Core@2.0.0.470] [Information] Recipe '"Grafikdesign"' executed successfully.`

SquirrelSetup.log: none

**Comment by vegardlarsen** [comment] 2019-03-11 11:03
Thank you for the detailed error report. This error appears only in specific situations:

1. MaxTo is running elevated
2. The path to the executable contains spaces.

The issue is that we are using a method called [`CreateProcessWithTokenW`](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createprocesswithtokenw) to start the executable without elevation. That method accepts the program arguments in a somewhat special format: `<executable path> <arguments>` (the `lpCommandLine` parameter). Unfortunately the documentation we looked at when implementing this left out this important detail from the documentation:

> If lpApplicationName is NULL, the first white space–delimited token of the command line specifies the module name. If you are **using a long file name that contains a space, use quoted strings to indicate where the file name ends and the arguments begin** (see the explanation for the lpApplicationName parameter).

We didn't catch this earlier, because we regularly use `notepad` as our test recipe target, which does not have a space in its path.

I have fixed this issue locally and it will be in the next build.

**Closed** 2019-03-11 11:04 UTC
Labels: bug
