### ISSUE TITLE
Not snapping if taskbar is located at top

### ISSUE THREAD

**Issue by khongi** [digitalcreations/MaxTo#433] opened 2019-06-21 07:15 UTC
**Describe the bug**
If the windows taskbar is located at the top of the screen, then dragging the window to top edge (on top of the taskbar) and releasing does not reposition/resize the window.

**To Reproduce**
1. Set windows taskbar to top position
2. Split screen to left right halves.
3. Grab a window with the mouse and drag it to left/right top to maximize.

**Expected behavior**
The window should fill either left or right half of the screen

**Screenshots**
![maxto_top_taskbar_bug](https://user-images.githubusercontent.com/11983684/59904866-ebe5d980-9404-11e9-9f13-b72ac9027eb0.png)

**System information:**
 - Windows version: 10 1903
 - MaxTo version 2.0.1 Stable channel

**Comment by vegardlarsen** [comment] 2019-06-21 10:50
I cannot reproduce this issue. Have you retried after a reboot?

**Comment by vegardlarsen** [comment] 2019-11-20 10:42
Closing because of no feedback from @khongi.

**Closed by vegardlarsen** 2019-11-20 10:42 UTC
