### ISSUE TITLE
Second monitor, ultrawide, thinks the screen is actually further over to the right.

### ISSUE THREAD

**Issue by grebarton** [digitalcreations/MaxTo#158] opened 2016-11-29 18:44 UTC
My main, standard ratio, monitor is fine. Maxto finds the edge of the screens no problem.
But on the ultrawide it seems to think that the screen it has to work with is about 15% over to the right so off the screen. It does not realise there is 15% of the screen uncovered by it.
![maxto error](https://cloud.githubusercontent.com/assets/10588271/20723789/d5872a58-b663-11e6-84fe-c2c099ace0b8.png)

**Comment by rickskirch** [comment] 2016-11-29 21:20
I appear to be having this issue as well with a 4k HDR Tv used as a second monitor.  I can see in the config file it sees two monitors, but when I go to change regions, there is no Changing Regions menu, Monitor or Region number, or a Split menu on the HDR Tv (second monitor).  I thought maybe i could define the region size in the config file, but I don't see how.

**Comment by vegardlarsen** [comment] 2016-11-30 09:12
Is the monitor were this problem occurs perhaps a high-DPI monitor? Are the actual regions also affected, i.e. if you maximize a window to a region on that screen, does the window meet the left edge?

**Comment by grebarton** [comment] 2016-11-30 16:09
I have found the issue and it is between MaxTo and the feature within the Display settings. Both monitors are 1440 but one is ultrawide as well. On the regular monitor, I had the "Change the size of text, apps and other items:" set to 125% but it was 100% or normal on the ultrawide. Now I have set them both to 100% MaxTo is reading the screen space correctly. Seems very interesting as to why this is happening but there you go. MaxTo is too useful to me to not use so I will keep them both at 100% instead.

**Comment by rickskirch** [comment] 2016-12-01 00:18
It is a high DPI Monitor/Television.  So I played some more.  This behavior happens after startup is complete. I cannot maximize any apps on that monitor while MaxTo is open.  But if I close MaxTo, I can maximize apps, and they maximize appropriately (they fill the screen with no bleed to the left or right).  If I then reopen MaxTo, I can maximize with no bleed.  In addition, i can now see the bottom of the Split Vertical/Split horizontal/Remove (grayed out) buttons in the upper right hand corner.  Now, on my main laptop screen, it says the approximate size is 1536x864.  My resolution for that main laptop screen is 3840x2160.  On the second monitor now that i can see the approximate size is 3277x1728 with the resolution being 4096x2160. Even if I reduce the second monitor to 3840x2160 i still get a reported approximate size of 3072x1728 in the upper right hand corner.  If i were to extrapolate by the location of the buttons and what it is reporting, it would seem that it thinks my monitor is 4 times the size with the actual real estate being in the lower left hand corner.  After all of this I did what George said he did above.  That worked, but my laptop (main screen) is now so small i cannot read it.  It was at 200% with the monitor being at 100%.  As opposed to George, I cannot work like that.  So is there a way to fix this through the configuration? Or maybe tell MaxTo to no worry about monitor 1 (laptop screen)  and only apply the items to monitor 2?  Maybe if it didn't read the properties of monitor 1 it wouldn't attempt to apply them to monitor 2?  I hope this helps.

**Comment by vegardlarsen** [comment] 2016-12-01 14:10
This is a well-known issue. It is caused by MaxTo lacking what is known as "per-monitor DPI awareness", which is currently not supported in Windows Forms, which MaxTo is based on. We are working on a larger update that will solve this problem.

Note that this should only affect region setup, if you start maximizing windows, you should see them aligning correctly to the monitor edges, effectively scaling up what you see to match the monitor.

This is tracked in #30, so I am closing this issue.

**Closed by vegardlarsen** 2016-12-01 14:10 UTC
