### ISSUE TITLE
Modern apps windows are not "de-maximized" when detached from the region

### ISSUE THREAD

**Issue by gorbunovav** [digitalcreations/MaxTo#422] opened 2019-06-03 20:58 UTC
**Describe the bug**
It looks like all windows are staying in the "maximized" state after being fit into the region (via maximization).

Classic apps windows are "restored" when you detach them from the region (they resize to the previous size). It is not ideal but allows them to be attached to the new region without issues.

Modern apps are not "restored" on detach, instead, they will be restored on the attempt to fit into the new region (the maximization will be called and it will work as "restore" since the window is already "maximized").

**To Reproduce**
1. Define some regions
2. Take the modern "Calculator" or the "Settings" app (not maximized)
3. Drag it to the top margin of some region and drop - it will be fit into that region
4. Try to drag it to the top of another region
5. The window will jump to the previous position/size (to the pre-first region fitting state)

**Expected behavior**
The window will be fit into the new region.

**System information:**
 - Windows version: 10 Pro 1903, Build 19362.145
 - MaxTo version: 2.0.1

**Comment by vegardlarsen** [comment] 2019-06-05 09:18
Thank you for notifying me of this issue. I haven't noticed this before. I am looking into why this appears to happen, right now I cannot figure out anything besides it seems like the window is not getting subclassed properly.

**Comment by vegardlarsen** [comment] 2019-10-24 11:14
I have managed to track down and fix this issue. It was caused by UWP windows having a flag set (`WS_POPUP`) that we've previously interpreted as being off-limits for MaxTo. This fix will be in the first preview release of 2.1.0. (Hopefully soon)

**Closed** 2019-10-24 11:15 UTC
Labels: bug
