### ISSUE TITLE
MaxTo doesn't work with Virtual Desktops by Dexpot

### ISSUE THREAD

**Issue by Xsteel21** [digitalcreations/MaxTo#718] opened 2021-04-17 22:18 UTC
Hello,
i have installed MaxTo and virtual desktops by Dexpot (Win 10 64bit), but it seems not to work.
I cannot define different regions in virtual desktops, the regions will be the same for all desktops.
In orginal virtual desktops by Win10 it works fine, but they are uncomfortable to use.
Could you please try to verify this situation or make it work with Dexpot in future?

Thank you!

**Comment by vegardlarsen** [comment] 2021-04-18 06:12
@Xsteel21 Thank you for writing. Can you try updating to version 2.2.0-beta.2? The issue with virtual desktops should be solved in that version. The easiest way to update is to change your update channel to "Beta" in MaxTo's settings (the Updates tab).

This is a duplicate of #669, so I am closing it.

**Closed by vegardlarsen** 2021-04-18 06:12 UTC

**Comment by Xsteel21** [comment] 2021-04-18 20:29
Hello,

 

thank you für answering.

I've tested it already in 2.2.0-beta2 and it doesn't work so far with Dexpot (not Windows) virtual desktops!

I'd read #669 before…

 

 

Von: Vegard Andreas Larsen ***@***.***> 
Gesendet: Sonntag, 18. April 2021 08:13
An: digitalcreations/MaxTo ***@***.***>
Cc: Xsteel21 ***@***.***>; Mention ***@***.***>
Betreff: Re: [digitalcreations/MaxTo] MaxTo doesn't work with Virtual Desktops by Dexpot (#718)

 

@Xsteel21 <https://github.com/Xsteel21>  Thank you for writing. Can you try updating to version 2.2.0-beta.2? The issue with virtual desktops should be solved in that version. The easiest way to update is to change your update channel to "Beta" in MaxTo's settings (the Updates tab).

This is a duplicate of #669 <https://github.com/digitalcreations/MaxTo/issues/669> , so I am closing it.

**Comment by vegardlarsen** [comment] 2021-04-19 17:33
Thank you for the clarification. I apologize for misunderstanding. We cannot support Dexpot, as it does not appear to use any of the built-in Windows capabilities regarding virtual desktops. This makes it impossible for us to handle this in any good way, and considering Dexpot's userbase is so small compared to Windows, it really does not make sense for us to invest the required time and energy into such support.
