### ISSUE TITLE
Intermittent Triple Monitor issue after resuming from Standby or Screensaver

### ISSUE THREAD

**Issue by rjstep01** [digitalcreations/MaxTo#195] opened 2017-10-16 23:15 UTC
This may be related to Issue #128.

I have 3 monitors in extended desktop mode [#1 - DisplayPort]-[#3 DVI]-[#2 HDMI].  The left monitor (#1) is divided in two vertical regions.  The other monitors have a single region each.

When I start MaxTo, everything works fine.  I can open a window and using the hotkeys move my window left or right across all three monitors.

Sometimes (I have noticed it particularly after resuming from going into standby or when I've had to wake up the screen after inactivity timeout), one or more monitors is forgotten by MaxTo.  For example, I might be able to use the MaxTo hotkeys to move the window between the middle (#3) and right (#2) monitor, but not the left monitor (#1).  Sometimes only the middle monitor is recognized.  Sometimes the middle monitor seems to be divided into two regions (the configuration from the left monitor).

Exiting and restarting MaxTo resolves the issue.  The problem is intermittent but frequent.

I am running Windows 10, v1703.

**Comment by vegardlarsen** [comment] 2017-10-23 06:38
Thanks for reporting this. I am pretty sure this is caused by [this bug in `Screen.AllScreens`](https://stackoverflow.com/questions/5020559/screen-allscreen-is-not-giving-the-correct-monitor-count).

Due to how often this functionality is used in the current release of MaxTo, this will not be fixed until we get our large rewrite out the door. Hopefully, the first alpha will be sometime in November. For that release we have rewritten this entire functionality without relying on the `Screen.AllScreens` bug. Watch this issue tracker for an update when the alpha is ready.

I am closing this as this has already been fixed in a future release.

**Closed by vegardlarsen** 2017-10-23 06:38 UTC
