### ISSUE TITLE
LocalBridge.exe - Bad Image

### ISSUE THREAD

**Issue by slyfelber** [digitalcreations/MaxTo#503] opened 2019-11-20 10:36 UTC
**Application popup: LocalBridge.exe - Bad Image**
Approximately every 10 minutes there is an application popup from MaxTo with the following message:

Application popup: LocalBridge.exe - Bad Image : %localappdata%\MaxTo\app-2.0.1\MaxTo.Hook.x64.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f. 

This popup message appears 3 times and can be confirmed with ok.
The application itself works.

I uninstalled the MaxTo application removed the %localappdata%\MaxTo folder, restarted the client and reinstalled MaxTo.
Unfortunately the error messages are still pop-up.

**To Reproduce**
1. Running application in the background
2. Without any intervention, the error message popups appear.

**Expected behavior**
I want to avoid this error messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/57987010/69231533-88193580-0b89-11ea-94dc-fbea1418ec9a.png)

**System information:**
 - Windows version: [10, 1903]
 - MaxTo version [2.0.1]

**Additional context**
[SquirrelSetup.log](https://github.com/digitalcreations/MaxTo/files/3868725/SquirrelSetup.log)
[maxto20191118.log](https://github.com/digitalcreations/MaxTo/files/3868733/maxto20191118.log)

**Comment by vegardlarsen** [comment] 2019-11-20 10:37
Hi @slyfelber,

and thank you for reporting this. This is a duplicate of #415. That issue has a full workaround and explanation of what is happening.

I am closing this issue as a duplicate.

**Closed by vegardlarsen** 2019-11-20 10:37 UTC
