### ISSUE TITLE
Custom region setting lost on reboot in v2.2.0

### ISSUE THREAD

**Issue by nrz0** [digitalcreations/MaxTo#745] opened 2021-07-11 03:03 UTC
I'm having the same issue described in bug #375, but in version 2.2.0 on Windows 10 v21H1 (build 19043.1083).

This bug has been closed out and the workaround to set the monitor settings to "Properties" had no affect.  However, apparently unlike the initial issue, this _only_ happens on Restart.  I can Exit the app from the Notification Area and reopen it and it will remember my custom region then, at least until the next Restart.

**Comment by Cavia** [comment] 2021-07-13 07:23
Hello,

I second the problem exactly as described by nrz0.

**Comment by vegardlarsen** [comment] 2021-07-13 18:47
This is a duplicate of issue #739. Please continue the discussion there.

**Closed as completed by vegardlarsen** 2021-07-13 18:47 UTC
Labels: duplicate
