### ISSUE TITLE
MaxTo not Windows 1909 compliant

### ISSUE THREAD

**Issue by enCiphered** [digitalcreations/MaxTo#504] opened 2019-11-20 23:42 UTC
**Describe the bug**
MaxTo is not working since I installed the Windows 10 1909 update a few days ago.
Everytime I start it, an error message pops up that "Max.To.Hook.x64.dll does not work under Windows..."
I´m using the latest stable Max.To version

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.1

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

This link is wrong! I can´t provide a log file

**Comment by vegardlarsen** [comment] 2019-11-23 18:52
This issue is a duplicate of issue #415, which has a proper workaround and an explanation.

PS! The paths above are valid on all Windows systems, they contain environment variables that are not very well known.

**Closed by vegardlarsen** 2019-11-23 18:52 UTC
