### ISSUE TITLE
Unable to focus on window or move window

### ISSUE THREAD

**Issue by bumbeen** [digitalcreations/MaxTo#614] opened 2020-09-16 21:58 UTC
Hi. I'm trying to build a recipe that starts outlook, then moves it to a specific region on my 2nd virtual desktop. I am unable to get it to do this, no matter what combination of options and ingredients I use in a recipe.

This is on the latest beta version, because the stable version does not work on my computer. I have a 5120x1440 monitor and a 1920x1080 monitor.

I have tried:
Wait for program to be ready
Window to wait for
Bring to front
Timeout in seconds
Focus on window before move window step
search for window in move window step - via process name and window title.

Every one of these options fails in one way or another. The only thing that actually works out of all this, is starting outlook. 

I have log snippets for all of them, which would you like first?

**Comment by vegardlarsen** [comment] 2020-09-17 13:21
I am assuming that this is a duplicate of your other issue; #615. Please let me know if that is not the case.

**Closed by vegardlarsen** 2020-09-17 13:21 UTC
