### ISSUE TITLE
Regions won't change across virtual desktops.

### ISSUE THREAD

**Issue by TylerJms7** [digitalcreations/MaxTo#719] opened 2021-04-19 14:01 UTC
I have 3 different virtual desktops for various work. When I change the regions on one desktop they stay the same across all of them no matter what settings I change. I have the setting "checked" that should allow different regions for different desktops. 

Windows version 20H2 OS BUILD 19042.928

[config.txt](https://github.com/digitalcreations/MaxTo/files/6336595/config.txt)

**Comment by vegardlarsen** [comment] 2021-04-20 19:17
Please update to version 2.2.0-beta.2. The quickest way to update is to set your Update channel to Beta in MaxTo's settings (under Updates). Please let me know if the problem is still present in that version.

I am closing this as a duplicate of #669.

**Closed by vegardlarsen** 2021-04-20 19:17 UTC
Labels: duplicate
