### ISSUE TITLE
GameBarFT.exe

### ISSUE THREAD

**Issue by RaphaelKomander** [digitalcreations/MaxTo#472] opened 2019-09-20 08:42 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**
 - Windows version: [e.g. 10, 8, 8.1]
 - MaxTo version [e.g. 22]

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`
[Screenshot](https://drive.google.com/open?id=1BQHijksZEZLWmYBYB4wnpFUZXCBpET5M)

**Comment by RaphaelKomander** [comment] 2019-09-20 08:43
Please have a look at the screenshot - linked. Thx!

**Comment by vegardlarsen** [comment] 2019-09-20 12:52
Hi @RaphaelKomander. This is a duplicate of issue #415. Please see that issue for a workaround (resetting GameBarFT from Add/remove programs in Windows settings).

**Closed by vegardlarsen** 2019-09-20 12:52 UTC
