### ISSUE TITLE
Maxto Doesn't work after new systemstart

### ISSUE THREAD

**Issue by RhinoFox** [digitalcreations/MaxTo#741] opened 2021-06-17 11:56 UTC
After newstart of the system MaxTo doesn't snap to the regions. Even if i change presets, no region is recognized. It only sees two full-screen regions of the two monitors (different dimensions and DPI).
After exiting MaxTo and make a fresh start, everyting works fine. I experience this several times for the past week now.

When I only 
logoff and logon, no problem.

Image = Logging off taskmanager history (MaxTo start at logon)

![afbeelding](https://user-images.githubusercontent.com/69254507/122391327-2bebe280-cf73-11eb-83cc-fa1cf34bc7d0.png)

Win 10 21H1 19043.1052 NL
Maxto 2.20

[purefox_startup_741.zip](https://github.com/digitalcreations/MaxTo/files/6669957/purefox_startup_741.zip)

**Comment by RhinoFox** [comment] 2021-06-18 10:30
After a simple exit/restart of MaxTo, it still has no regions. But then it does respond to setting the regions. When I, after a newstart, don't give it an exit, but try to set the regions correctly and then exit/restart MaxTo, it works correctly.

It seems that after a newstart of the system, the last used regions are not kept.

**Comment by e46hgbcvbe45** [comment] 2021-06-19 02:04
Same issue for me, on each restart I need to set a dummy region the copy the content of the old monitor json in the new json to get my region back

**Comment by vegardlarsen** [comment] 2021-06-21 18:59
I believe this is a duplicate of issue #739, so I am closing this issue.

You can use this as a workaround for now: turn off "Use different regions on each virtual desktop" in the Settings, under Monitor.

**Closed as completed by vegardlarsen** 2021-06-21 18:59 UTC
Labels: duplicate
