### ISSUE TITLE
Cannot Exchange License on Site

### ISSUE THREAD

**Issue by Vaccano** [digitalcreations/MaxTo#524] opened 2020-01-02 22:13 UTC
**Describe the bug**
I wanted to install Max To on my new machine.  When I wen to download, it told me I needed to exchange my license key.

When I try to do that, it gives an error.

**To Reproduce**
1. Go to https://maxto.net/en/license/exchange 
2. Enter you Registered To information
3. Enter your license key
4. An error is shown

**Expected behavior**
I expected the new license key to be shown (or have an option to download the old version).

**System information:**
 - Chrome (Latest version)

**Additional context**
I last downloaded Max To a long time ago.  Maybe that license is no longer valid?

**Comment by vegardlarsen** [comment] 2020-01-03 12:54
@Vaccano What error do you receive? Usually this is caused by not entering the information in your "Registered to" field correctly; depending on when you bought your license this could either be an e-mail address or your name. The information should be in your license e-mail.

If you are having trouble you can contact us at support@maxto.net, and we will figure it out.

Closing this issue.

**Closed by vegardlarsen** 2020-01-03 12:54 UTC
