### ISSUE TITLE
Cant use virtual desktop recipes on Windows 10

### ISSUE THREAD

**Issue by YenTsunim** [digitalcreations/MaxTo#709] opened 2021-03-01 18:43 UTC
**Describe the bug**
When I try to move a window to the next virtual desktop I get the message "Could not execute recipe
Virtual desktops are only supported on Windows 10".

I installed MaxTo on 2 different PC's with Windows 10 Pro and on both PC's I encountered this issue.

**To Reproduce**
Use the default recipe "Move window to next virtual desktop" on a Windows 10 Pro.

**Expected behavior**
Moving the window to the next virtual desktop.

**Screenshots**
![recipe-notification](https://user-images.githubusercontent.com/77784227/109541558-3bc6e000-7ac4-11eb-82a2-dc0f2b4e2e7c.jpg)

**System information:**
- Windows version PC1: 2004 (OS Build 19041.804)
- Windows version PC2: 20h2 (Build 19042.804)
- MaxTo version on both PC's: 2.1.5

**Additional context**
[log.log](https://github.com/digitalcreations/MaxTo/files/6063733/log.log)
[config.json.txt](https://github.com/digitalcreations/MaxTo/files/6063752/config.json.txt)

**Comment by vegardlarsen** [comment] 2021-03-01 19:03
Thank you for your issue. This is a duplicate of issue #669. It has been fixed in version 2.2.0-beta.1. To upgrade, go into Settings, Updates, and set your "Release channel" to Beta, then check for updates. :)

**Closed by vegardlarsen** 2021-03-01 19:03 UTC
